### ISSUE TITLE
Investigate CI / CD migration to GitHub

### ISSUE THREAD

**Issue by waliid** [SRGSSR/pillarbox-apple#1003]
**As a Pillarbox developer**, I would like to understand what the best option is for our CI/CD.

# Acceptance criteria

- Find at least one solution that is suitable for our project.

# Tasks

- [x] Understand what the **AIS Team** has [achieved](https://srgssr-ch.atlassian.net/wiki/spaces/RTS/pages/1054344888/iOS+CI+setup) so far.
- [x] Contact at least one member of the **PlayNext** team to see if they are interested in investigating `Tart` with us.
- [x] Collect information about `Tart` and its environment (how it works).
- [x] Configure a small project in a local development environment.
- [x] ~Try to determine the costs associated with `Tart`.~
- [x] ~Identify the resources required with `Tart`.~
- [x] ~Determine how long `Tart` takes to:~
    - [x] ~Create a VM, start the VM and run a build.~
    - [x] ~Start a VM and run a build.~
- [x] Try to use externally hosted runners once self-hosted runners are working properly (GitHub runners, Bitrise, Macstadium, etc.).
- [x] Find how we can save build artifacts for later inspection (e.g. detailed logs) after a VM has been destroyed.
- [x] ~List any additional hardware that we could ask to buy.~

**Comment by waliid** [comment]
Firstly, I set up a CI on a single machine with a single GitHub runner, using a **Tart** virtual machine. The problem was that there was no parallelization, which meant that workflows took a long time to complete.

Then, I made the process more complex by adding a second runner on the same machine. The problem was that I had to manage concurrent writes for certain jobs, such as the iOS and tvOS tests, which write to the same folder (Derived Data).

Finally, I added two GitHub runners on another machine, so I now had two runners on the first machine and two on the second. The issue, was that my first job started a virtual machine on the first machine, but the second job could potentially use the second machine, which had no knowledge of the virtual machine; as a result, my workflow was failing.

I then tried to group my machines together using Orchard. The next issue, was that I couldn't use `scp`, because with **Orchard** only an **SSH** connection is possible. I got round this limitation by compressing the files and folders I wanted to send, sending them via **SSH** and then decompressing them on the fly. However, this solution proved to be very slow.

So I opted for another approach using **labels**. The first and second machines each have a specific *label* for the different files.

The problem with this solution is that once the first job starts on one machine, the entire workflow remains confined to that machine until the end, which prevents the resources of the other machines from being used.

**Comment by waliid** [comment]
Running tests simultaneously causes a failure because both jobs (test-ios and test-tvos) attempt to write to the same location.

![Image](https://github.com/user-attachments/assets/d65cb79a-db97-439b-99d6-a6ce48941eda)

To bypass this issue, one solution is to update our Fastfile to separate the derived data into two distinct directories as show below:

```ruby
def run_package_tests(platform_id, scheme_name)
  output_path = "fastlane/test_output_#{platform_id}"
  derived_data_path = "#{Dir.home}/Library/Developer/Xcode/DerivedData/#{platform_id}"
  FileUtils.mkdir_p(output_path)
  FileUtils.mkdir_p(derived_data_path)
  run_tests(
    scheme: scheme_name,
    device: DEVICES[platform_id],
    package_path: '.',
    result_bundle: true,
    output_directory: output_path,
    derived_data_path: derived_data_path,
    number_of_retries: 3,
    fail_build: false,
    xcargs: '-testLanguage en -testRegion en_US'
  )
  trainer(
    path: output_path,
    output_remove_retry_attempts: true,
    fail_build: false
  )
end
```

**Comment by waliid** [comment]
Here are the explanatory sketches of the approaches attempted so far. The first approach consists of running the runners on a physical machine, while the second, which I find much simpler and is based on [Tartelet](https://github.com/shapehq/tartelet), consists of letting the VMs creating the runners.

> [!NOTE]
> The second approach is under investigation.

| **Approach** | **Description** | **Diagram** |  
|----|----|----|  
| Runners on physical machine | The runners are installed on a physical machine, and GitHub Actions handle the creation, starting, running, and shutting down of the VMs. | ![Image](https://github.com/user-attachments/assets/5a6af444-b3a0-4ba2-a0a3-e61503aee6e5) |  
| Runners on virtual machine  | Tartelet is responsible for managing the VMs and creating ephemeral GitHub runners. |  ![Image](https://github.com/user-attachments/assets/147754a9-6eec-457a-a4aa-7fe99742e7b1) |

**Comment by waliid** [comment]
The tests are taking too long time before failing in my opinion. I think it would be a good idea to set a shorter timeout for some tests.

![Image](https://github.com/user-attachments/assets/8890eacf-647b-4bc7-b2af-9d9dd7bc5464)

**Comment by defagos** [comment]
| Step | Self-hosted runner | GitHub runner |
|--------|--------|--------|
| Code quality | Cell | Cell |
| Documentation | Cell | Cell |
| Archive iOS | Cell | Cell |
| Archive tvOS | Cell | Cell |
| Tests iOS | Cell | Cell | 
| Tests tvOS | Cell | Cell |

**Comment by defagos** [comment]
We have investigated GitHub-hosted runners and they work pretty well, especially since our repository is public. There is no need to focus our effort on Tart and related questions.

We are still investigating caching between builds. Provided our dependencies can be retrieved fast caching seem counterproductive, as more time is added when a cache is created (2min30 when caching SPM sources).

To make dependency retrieval even faster we delivered a Commanders Act binary [repository mirror](https://github.com/SRGSSR/commanders-act-apple). This shaves off quite some time during package resolution and retrieval.

**Comment by defagos** [comment]
We tested different caching strategies:

- Using the standard cache action to cache package sources.
- Using the [`xcode-cache`](https://github.com/marketplace/actions/xcode-cache) action to cache package sources as well as DerivedData.

None of them really makes our current pipeline faster (sometimes derived data is used, sometimes not). This also requires more configuration and possible fastlane configuration changes (e.g. reusing a folder reconstructed from cache).

For the moment we therefore won't introduce any caching in our pipeline.

**Comment by defagos** [comment]
Actual integration will be performed in #1068.

**Comment by defagos** [comment]
There is no need to set microphone permissions on GitHub runners, unlike self-hosted ones we created with Tart in the past.
