### ISSUE TITLE
`VideoView` undesired implicit animations

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#1006]
**As a developer integrating Pillarbox** I want to be able to animate `VideoView`s without glitches, especially during rotations, translations or size changes.

Even if some issues were fixed in https://github.com/SRGSSR/pillarbox-apple/pull/726, we recently updated our Podcastator sandbox project and found that the video background animation during player expansion / collapsing is lagging behind.

# Acceptance criteria

- The Podcastator animation glitch is fixed.
- Rotation animations are correct.
- SRF news animations are correct.

# Tasks

- [x] Fix the issue.
- [x] Test rotation in Pillarbox demo.
- [x] Test behavior in Podcastator.
- [x] Test all PiP scenarios manually (see #612).
- [x] Test SRF app behavior.

**Comment by defagos** [comment]
Attempting to synchronize `CALayer` animations like we did in #726 is doomed to fail. But we can store the view and its layer instead of the layer alone in our custom picture in picture manager class. This way we can have the view use `AVPlayerLayer` as backing layer class, which should solve this issue.

This needs further testing of course.
