### ISSUE TITLE
Revisit system video view Picture in Picture support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#1015]
**As an app developer** I want to be able to use Picture in Picture with any layout configuration, as for `VideoView`, without it being interrupted and without any video layer being lost.

# Acceptance criteria

- The `VideoView` PiP demos are provided for `SystemVideoView` as well.
- All possible use cases work equally well with `SystemVideoView`.

# Tasks

- [x] Update PiP-related demos with corresponding system video view entries.
- [x] Adopt similar strategy as `VideoView` to fix issues.
- [x] Go through all PiP use cases (see #612) and ensure nothing is broken.
- [x] Check memory profile.
- [x] Check behavior on tvOS 16, 17 and 18.
- [x] Check behavior on iOS 16, 17 and 18.
- [x] Improve documentation if needed (some restrictions are already documented in the PiP article).
- [x] Document that auto-switch to PiP does not work when multiple PiP-supporting system video views are displayed at the same time.

**Comment by defagos** [comment]
A few remarks:

- We previously did not implement PiP dismissal for our inline system video view demo. Dismissal is in fact possible but should occur after PiP started, otherwise the system might pause playback for some reason. We have updated our documentation and demos accordingly.
- During our implementation we wanted to add a `Player` parameter to PiP delegate / lifecycle methods. When several PiP-enabled views are displayed at the same time, the implementation theoretically doesn't know which player PiP is started for. We thus thought this additional piece of information could be helpful (e.g. so that implementations can pause other players), but discovered during implementation that this was adding a lot of unnecessary complexity. This should not be an issue, though, as PiP should really be enabled for one view at a time, which means that implementation must know the current player identity already.
