### ISSUE TITLE
Add unbuffered examples to showcase

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#103]
**As a demo user** I want to have more examples of unbuffered audio playback.

# Acceptance criteria

- Unbuffered examples have been added to the showcase.

# Tasks

- [x] Add unbuffered AOD example.
- [x] Add audio livestream example.
- [ ] Improve stream / media constants names (e.g. include hls / mp3).
