### ISSUE TITLE
Ensure correct playback state when removing items

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#105]
**As a Pillarbox client** I want to have clean playback state I can rely on, also when playlist management is involved.

# Acceptance criteria

- Playback states make sense also when items are removed from the player.

# Tasks

- [ ] Write unit test in which player items are removed while playing and decide which state should be reached.
- [ ] Fix the implementation if needed.
- [ ] Write other meaningful unit tests.

**Comment by defagos** [comment]
Done in #106. Closed as duplicated.
