### ISSUE TITLE
Resource loading overhaul

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#106]
**As a Pillarbox user** I want all contents to be playable and to be correctly informed of errors which might happen.

# Acceptance criteria

- All examples play...
- ... except those with errors which display a proper error message.
- Network errors are correctly reported when no network is available, for all examples.

# Context

As discovered in #95 the current approach to load URNs with a resource loader is doomed to fail. Instead, when playing SRG SSR content, we need to load the URL outside the resource loader, as we do in Letterbox today. We must then build and supply a corresponding item to the queue player.

# Tasks

- [x] Implement `AVPlayerItem` placeholder for errors.
- [x] Implement `PlayerItem` loading from a URN and delivering an `AVPlayerItem` with a pipeline. Use loading and failure placeholder items to deal with initial state and metadata retrieval failure.
- [x] Aggregate `AVPlayerItem`s delivered by `PlayerItem` as they are updated.
- [x] Implement trivial `PlayerItem` loading from a URL.
- [x] Introduce `AccumulateLatestMany` to aggregate changes.
- [x] Update `AVQueuePlayer` with diffing strategy (insert before methods required).
- [x] Retrieve metadata before creating the item (will fix MP3 playback issues).
- [x] Check whether `inferringMoves` can be useful to preserve existing items while moved. In other words check that moved items are not deallocated (else preserve them temporarily) and that, if the current item is moved, playback continues without interruption.
- [x] Add setter for all items at once.
- [x] Deal with resource loader ordering (if two contents are played and the second one is obtained first the player might skip to it directly).
- [x] Implement `currentItem` publisher (simple pipe) with associated lane.
- [x] Write UT for resource loader ordering (use current item publisher in tests).
- [x] Apply short buffer / keep up with live behavior for live items only.
- [x] Add playlist demo example with errors.
- [x] Check all examples.
- [x] Fix `AccumulateLatestMany` implementation to avoid `AnyPublisher` in parameters (have type constraints instead). This avoids forcing callers to erase the type when calling the method.
- [x] Test with AirPlay (tvOS 16.1 most likely).
- [x] Check memory and network profiles.

**Comment by defagos** [comment]
`inferringMoves` is not needed when applying diffs to update the player queue.

**Comment by defagos** [comment]
Rough sketch of how resource loading is fixed to load metadata before delivering items to the player (knowing the extension to use):

- `AVPlayerItem` is now wrapped by `PlayerItem` which contains a publisher responsible of delivering the player item.
- The pipeline initially delivers a `LoadingPlayerItem` and a `FailingPlayerItem` in case of an error. Both have been implemented with dedicated dummy resource loaders.
- If a player item is successfully delivered the publishers are all wired to the player itself so that the `AVQueuePlayer` queue can be updated accordingly. This is done by using `AccumulateLatestMany` borrowed from [my article](http://defagos.github.io/declarative_reactive_programming_with_combine).
- Any change to the stored items property (insertion, removal) a pipeline update.
- The update is performed by using the current item as pivot, gathering all items after it, and calculating the diff between existing items in the `AVQueuePlayer` and the updated items. If the current item has disappeared we consume the items after it until we find a common item, in which case we update from there recursively.
- All other mutations through the public player API (insertions, removals, moves) trigger mutations of the stored items and thus consistently go through the same update pipeline.
-

**Comment by defagos** [comment]
There is still an issue with the current item selected at the beginning of playback, which can be reproduced as follows:

- Create a playlist with two URNs.
- Add a delay for media composition delivery based on a URN, delivering a large delay for the first URN in the playlist and none for the second one.
- Play the playlist.

If we observe `currentItem` changes we see that for some reason the current item is moved to the second item. We will need to figure out whether this is an `AVQueuePlayer` bug (some issues related to queue management were namely fixed in 16.1) or whether we can do something to mitigate the problem.

**Comment by defagos** [comment]
I found the issue: Merging could be aggressive by removing the current item to update it (e.g. between loading and loaded items), which would make the player `currentItem` automatically move to the next item.

To fix this issue I applied the following approach:

- Introduce a unique `id` attached to each `PlayerItem` delivery pipelines, marking items delivered by it so that they can be matched when replaced. This `id` is for internal purposes only and is forced unwrap to mark incorrect use as a programming error.
- Use the id to identify the pivot item.
- Use the id to identify current item updates and deal with them first to avoid removing and inserting its replacement (which would trigger a move to the next item).

**Comment by defagos** [comment]
I still need to write a unit test to validate this fix, likely as follows:

- Create a resource loader delivering an item slowly.
- Create a playlist with two items, the first one delivered slowly, the second one a simple URL.
- Verify that the current item is the first one.

**Comment by defagos** [comment]
iOS 16.1 RC again breaks error forward through the resource loader after having fixed it in betas. The failing item strategy applied in this task therefore fails to deliver items encountered during metadata retrieval properly.

This issue is not a regression on our side but needs to be addressed, see #114.
