### ISSUE TITLE
Migrate CI / CD to GitHub Actions

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#1068]
**As a Pillarbox developer** I want a reliable CI orchestrated using GitHub Actions.

## Acceptance criteria

- All existing CI tasks can be run through GitHub Actions on self-hosted hardware.
- Tasks perform in reasonable time.

## Tasks

- [x] Update scripts to be run with pkgx.
- [x] Create dedicated workflows.
- [x] Replace private configuration repository with GitHub secrets (p12 certificate and associated password, p8, other info).
- [x] Make repository structure simpler (e.g. no more need for symlinks to `.env`).
- [x] Create workflow for nightly / release demo builds.
- [x] Ensure steps fail correctly (e.g. if one test fails the test step must fail). See this [example](https://github.com/SRGSSR/pillarbox-apple/actions/runs/12071546327/job/33663541846).
- [x] Update repository configuration.
- [x] Archive or delete existing configurations on Team City. 
- [x] Archive private configuration repository (update `Fastfile` accordingly).
- [x] Inform other teams we have left the TeamCity CI.
- [x] Use `yml` for file extensions consistently.

**Comment by defagos** [comment]
For the moment we decided not to fix any macOS / tool version and to always use the latest versions available. Best practices would probably recommend to fix versions but we'll see if this is really an issue and adjust accordingly (it never really was with our old CI pipeline).

**Comment by defagos** [comment]
We discussed about updating our scripts to ZSH (now the default on macOS) but this will be delayed [until shellcheck supports it](https://github.com/koalaman/shellcheck/issues/809).

**Comment by defagos** [comment]
We disabled the triggers on TeamCity but retained the configurations. We will remove them at a later time.
