### ISSUE TITLE
Cleanup Makefile targets

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#1077]
**As a developer** I want `make` to only return commands I can run on my machine.

## Acceptance criteria

- All `make` commands run on a local development machine (not a CI agent).

## Tasks

- [ ] Transform Makefile targets that cannot be run locally into scripts that are run by CI workflows only.
- [ ] Update make target documentation.
- [ ] Check that remaining commands work locally.
- [ ] Add `xcodes` to tools installed via pkgx.
