### ISSUE TITLE
Make UT more reliable

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#108]
**As a developer** I need to have a reliable CI.

# Acceptance criteria

- Tests pass successfully on an CI agent.
- Test suites pass reliably and do not need to be restarted to pass.

# Tasks

- [ ] Discuss simulator list / naming scheme with @pyby to be able to run tests on predictable OS versions.
- [ ] Log simulator OS used if possible (could also have a temporary unit test assert that version >= 16.1 until Xcode 14.1 is officially released).
- [ ] Update configuration for iOS.
- [ ] Update configuration for tvOS.
- [ ] Check if the time to boot the server is too long (20 seconds) and might explain why some test timeouts had to be increased to 20 seconds (and whether we can therefore lower this value or make the tests run more reliably).

**Comment by defagos** [comment]
I confirm that running the tests on iPhone 13 with iOS 16.0 on my machine produced similar issues to those encountered on CI agents. Forcing to iPhone 14 is likely a good thing.

**Comment by defagos** [comment]
Local stream delivery had a few issues which were fixed in https://github.com/SRGSSR/pillarbox-apple/pull/126. Unit tests are now reliable. 16.1 is not required.

We can therefore close this issue.
