### ISSUE TITLE
Improve test suite robustness

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#1080]
**As a Pillarbox developer** I want CI workflows to run as fast as possible.

## Hints

Look for `::error` in build logs on GitHub. Some examples of tests that recently failed:

- `testPausedDvrStream`
- `testPlayerSetToNil`
- `testPlayerChange`
- `testPlaylistEnd`
- `testPreferredAudibleLanguageIsPreservedBetweenItems`
- `testMediaSelectionReset`
- `PlayerItemTrackerMetricPublisherTests.testPlaylist()`
- `MetadataPublisherTests.testEntirePlayback()`
- `ProgressTrackerTimeTests.testEntirePlayback()`
- `ProgressTrackerProgressTests.testEntirePlayback()`
- `ErrorTests.testInvalidStream()`
- `CurrentItemTests.testCurrentItemWithMiddleFailedItem()`

## Acceptance criteria

- The test suites have been optimized to run faster and reliably.

## Tasks

- [x] Try to serialize execution and see if tests run better.
- [x] Try to execute test suites separately (player, analytics, core business, etc.) and see if some test suites have more issues.
- [x] Optimize unit tests so that they run faster.
- [x] Improve tests that might still be flaky.

**Comment by defagos** [comment]
I tried to force [GitHub Actions formatting for xcbeautify](https://github.com/cpisciotta/xcbeautify?tab=readme-ov-file#github-actions) but this does not make failing expectations more visible in logs. Reverted.

**Comment by defagos** [comment]
We tested several different approaches in combination:

- Serialization with `parallel_testing` delivers the best stability at the expense of some execution time.
- Similar parameters like `disable_concurrent_testing`, `max_concurrent_simulators` (set to a minimum meaningful value of 2) do not deliver significant stability improvements.
- Replacement of _expect equal / similar_ with _expect at least equal / similar_ to avoid hardcoded timeouts which might more easily be reached on CI agents. This can be an improvement, especially if we want to further reduce the job time.
- Rewrite of some tests with arbitrary long delays (e.g. analytics tests which wait 5 seconds). This can be an improvement, especially if we want to further reduce the job time.
- Simplification of tests relying on time comparison (loosen tolerances or simple comparison to `nil` values). This can be an improvement.
- Use of alternative HTTP servers or related settings (e.g. using `http-server` from npm or HTTP version settings). No significant change.
- [Disable TCP / UDP network offloading](https://discord.com/channels/@me/1041985801443086368/1315659239619821659), manually or using a [corresponding action](https://github.com/marketplace/actions/tune-github-hosted-runner-network). Does not seem to improve the situation.
- Global Nimble timeout increase. This makes things worse.
- Enabling `skip_package_dependencies_resolution` and `skip_package_dependencies_resolution` to avoid repeated SPM resolution appearing in the logs. Does not change anything (still visible in the logs).

Note that the most problematic test target is PillarboxPlayer, other targets are much more stable.
