### ISSUE TITLE
Deliver unit test metadata locally only

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#110]
**As a developer** I want to avoid retrieving unit test metadata over the network.

# Acceptance criteria

- Unit test metadata is delivered locally.
- Unit tests pass even if no network is available.

# Tasks

- [ ] Deliver media composition with a custom `URLProtocol` redirecting to the the local Python server.
- [x] ~Deliver MP3 on-demand sample stream locally.~
- [x] ~Deliver MP3 livestream locally.~
- [ ] Deliver token locally (append to unprotected local streams).
- [ ] Have dummy test streams (stream1.m3u8 etc.) also exist and be valid locally (otherwise tests using them will fail as the player automatically consumes them on failure).

**Comment by defagos** [comment]
Local MP3 delivery does not work for on-demand content, see #297. Livestream delivery is probably complicated anyway. Crossed off the list for the moment.
