### ISSUE TITLE
Akamai token-protected content playback

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#111]
**As a user** I want to be able to play token-protected content, e.g. streams from the SwissTXT livecenter.

Remark: RSI resources are declared to require an Akamai token but in fact don't.

# Acceptance criteria

- SwissTXT livecenter streams can be played.

# Tasks

- [x] Add resource loader (start from code removed in #106).
- [x] Update player item pipeline to retrieve token if required.
- [x] ~Add example to demo (if a long-living example exists).~
- [x] Check behavior with simulated slow network (see #81).
- [x] Check behavior without network.
- [x] Check behavior in playlists.
- [x] Check AirPlay behavior. ⚠️ _Checked but several issues found_

**Comment by defagos** [comment]
Examples are only found for SwissTXT nowadays AFAIK and are short-lived. I won't therefore add one to the demo.

**Comment by defagos** [comment]
I checked AirPlay behavior and found several issues:

- Errors are reported without any friendly message.
- If a token needs to be retrieved behavior is sometimes unreliable, especially if AirPlay casting has been enabled before playback is started. In other cases everything seems fine.
- The behavior is even worse in playlists, where sometimes next / previous buttons are not working or the slider not displaying the correct range.
- If AirPlay casting is enabled before playback is actually started the reported range might be incorrectly empty (known issue already mitigated in Letterbox).
- The behavior is better if AirPlay is stated after playback, but backward navigation still has issues.

Investigating and fixing these issues is out of scope but should be a priority. Maybe we need to report issues to Apple as well but this requires many sample projects.
