### ISSUE TITLE
Improve playlist demo

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#112]
**As a developer or user of the library** I want to be able to test playlist capabilities extensively in the demo as well.

# Acceptance criteria

A playlist demo is available with advanced features, like:

- A list of the items in the playlist.
- The current item clearly identified.
- Addition / deletion / reordering of items with list gestures.

# Tasks

- [x] Create dedicated layout for the playlist example.
- [x] Display items and current item (maybe adding a description to the sample streams is required).
- [x] Implement add / delete / reorder.
- [x] Implement shuffle.
- [x] Implement reload with other items (pool of items from which some are pulled randomly).

**Comment by waliid** [comment]
# Add new item

![Image](https://user-images.githubusercontent.com/3347810/209672454-3aa5bbc6-8a2f-4022-b32d-09ef6bf7f81e.jpg)

![Image](https://user-images.githubusercontent.com/3347810/209672513-929620db-a3a5-4c47-9e1a-9c6ab81f7178.jpg)


# Display current item

![Image](https://user-images.githubusercontent.com/3347810/209673025-1992c8d0-a7bc-4e4e-bf1d-34d3938c1d0c.jpg)


# Delete

![Image](https://user-images.githubusercontent.com/3347810/209672745-05913e05-4e8f-45c5-8a8b-21998078366d.jpg)


# Reorder

![Image](https://user-images.githubusercontent.com/3347810/209672781-452429c2-cd1f-47f4-89ce-500a1f645aa9.jpg)


# Shuffle

![Image](https://user-images.githubusercontent.com/3347810/209672833-bd3e1bca-d32b-4859-aa01-6fbe5502db0e.jpg)


# Reload with other items

![Image](https://user-images.githubusercontent.com/3347810/209672911-260287db-292f-465b-8eb5-e610cc5c4fda.jpg)

**Comment by defagos** [comment]
As expected implementing and using the playlist demo made us learn about our existing implementation. We performed the following changes:

- To ensure better overall AirPlay stability (see #134) we implemented a strategy where the first item of the `AVQueuePlayer` is updated first, before the other items are appended a bit later. With the playlist demo we realized there was an issue in the implementation when moving an item (externally the playlist was correct but the player was restarting playback). To fix this issue we had to implement a better strategy to update the queue player items when either the source list is updated or a source is updated (e.g. transitioning from the loading to the loaded state).
- For convenience The `advanceToNextItem()`, `returnToPreviousItem()` and `skipToLive()` methods now return no boolean, making them easy to use as button actions. Methods still exist to know whether these actions are possible and, if they aren't, calling the above corresponding listed methods has no effect.
- We introduced a method to skip to a playlist item index directly. Unlike the above methods this method throws when an invalid index is provided.
- Knowing the current player item is not really useful, as such items provide no meaningful services (e.g. associated media metadata that an app could use). To make it easier to connect a playlist player item with an external data source for the playlist, managed by the app, it therefore appeared that the current index is far more interesting, as it allows to loosely couple medias loaded into the player with metadata managed by the app and used to load the player in the first place. The playlist demo shows how both can be synchronized in a real-life example.
- We removed `@MainActor` globally, as it was introduced unnecessary friction in code using `Player`. We might restore it when SDKs better annotate their code for main actor support (e.g. SwiftUI [button actions](https://forums.swift.org/t/converting-function-value-of-type-mainactor-to-void-loses-global-actor-mainactor/59155)) but currently this just adds frustration in API usage with no real significant benefit (we namely mostly use Combine for the implementation anyway).
- We improved `RawPlayer.replaceItems(with:)` implementation which was incorrectly crashing when updating the queue with an item list containing the current item. We also improved the implementation to avoid updates when not necessary. The implementation was clearly lacking tests but is now covered well.
-
