### ISSUE TITLE
DRM-protected content playback

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#113]
**As a user** I want to be able to play DRM-protected content, e.g. TV livestreams.

# Acceptance criteria

- Livestreams and TV series play fine.

# Tasks

- [x] Add ~resource loader (start from code removed in #106)~ content key session.
- [x] Update player item pipeline to retrieve license and certificate if required.
- [x] Ensure errors are correctly reported.
- [x] Add TV livestream examples to demo.
- [x] Check behavior with simulated slow network (see #81).
- [x] Check behavior in playlists.
- [x] Check AirPlay behavior.
- [x] Check network and memory profile.
- [ ] Not related: Push AirPlay basic test code on a separate branch afterwards.

**Comment by defagos** [comment]
We must use `AVContentKeySession` since DRM key resource loading with `AVAssetResourceLoader` is deprecated.

Some remarks:

- `AVContentKeySession` must not be short-lived, otherwise the `AVContentKeySessionDelegate` will not be called.
- If `AVContentKeySession.processContentKeyRequest(withIdentifier:initializationData:)` is supplied a valid stream URL (most notably ending with `m3u8`) then the `AVContentKeyRequest` identifier will be set to this value. Otherwise the `skd` URL is used.
- `AVContentKeyRequest.makeStreamingContentKeyRequestData(forApp:contentIdentifier:)` needs an identifier, otherwise it fails with an error. The identifier seems quite arbitrary in our case at the moment.
