### ISSUE TITLE
Improve error management

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#117]
**As a user** I want errors to be reported to me in the best possible way.

# Acceptance criteria

- Error management is improved further.

# Tasks

- [ ] Improve error comparison and update error-checking UTs (cast to `NSError` and compare domain, code and localized string?).
- [ ] Improve error management by listening to [failed item playback notifications](https://developer.apple.com/library/archive/technotes/tn2436/_index.html). The error is in the associated `userInfo` dictionary.
- [ ] Improve error management in playlists when navigating back (open playlist example containing errors, the 2nd failing item is skipped when navigating forward but not backward).

**Comment by defagos** [comment]
I guess we need to extract the error information from the `errorLog()` if available. Any other attempt I made was unsuccessful. Fortunately all information is available in the log and requires minimal parsing to be converted back to an error.

**Comment by defagos** [comment]
Best practices were discussed in a [WWDC talk](https://developer.apple.com/videos/play/wwdc2017/514).

**Comment by defagos** [comment]
There is a bug with the error log when navigating back to a failed item in a queue (i.e. replacing the current item with an item which previously failed). The error log is cleared so that we cannot access detailed information (even if the item `error` property says to look at the error log).

I attempted to write a unit test but without success. The obvious solution is to cache the error when extracted the first time using an associated object.

**Comment by defagos** [comment]
To reproduce the LIVE issue:

- Put a breakpoint in the LIVE button code.
- Move to the second item in the failed playlist example.

**Comment by defagos** [comment]
Test stream cleanup was really buggy. As a result the DVR stream would get messy if older chunks still existed. Two issues with the cleanup code:

- The criterium to look for matching processes was wrong.
- We should wait for the processes to disappear before cleaning the directory (safer).

**Comment by defagos** [comment]
`NSError` wrapping is really required when passing errors to the resource loader, otherwise the result is unreliable (works in the simulator but not on device). Easy to check by removing wrapping from `finishLoadingReliably(with:)` implementation.

**Comment by defagos** [comment]
On tvOS executing `testMoveFromInvalidIndex` leads to the following Nimble warning logged to the console:

```
[Nimble Warning]: If you're getting stuck on a debugger breakpoint for a fatal error while using throwAssertion(), please disable 'Debug Executable' in your scheme. Go to 'Edit Scheme > Test > Info' and uncheck 'Debug Executable'. If you've already done that, suppress this warning by setting `NimbleEnvironment.activeInstance.suppressTVOSAssertionWarning = true`. This is required because the standard methods of catching assertions (mach APIs) are unavailable for tvOS. Instead, the same mechanism the debugger uses is the fallback method for tvOS.
```

Disabling _Debug Executable_ is not so practical for everyday use. But maybe there is a better approach.
