### ISSUE TITLE
Skip to live button

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#119]
**As a user** I can return to live conditions when playing a livestream supporting DVR.

# Acceptance criteria

- The user can skip to the live for livestreams with DVR only.
- A corresponding player API is available.

# Tasks

- [ ] Implement `canSkipToLive` API.
- [ ] Implement `skipToLive` API.
- [ ] Add skip button to demo player.

**Comment by defagos** [comment]
Testing aync seek or skip methods currently requires a workaround, see #122.
