### ISSUE TITLE
Decouple progress from player

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#121]
**As a user** I want the player to perform as little updates as possible to preserve battery life while still delivering updates at appropriate pace.

# Acceptance criteria

- Progress updates are reduced to 0.1 second.
- Only the slider gets updated.
- Same for skip buttons and sliders.

# Tasks

This requires a bit of investigation but might be possible:

- [x] Remove progress updates from the player to avoid publishing global changes for the whole player while progress is updated.
- [x] Store the progress at the slider level and use a publisher to update it with 0.1 second interval.
- [x] Ensure correct behavior when changing the attached player.
- [x] Make progress information a read-only property on the player with which the user can peek at the current progress (but which is not a stored updated property).
- [x] Check with playground (only slider updates should be noticed while playback is advancing).
- [x] Do the same for progress views.
- [x] Display target time as elapsed time while seeking.
- [x] Check memory and Timelane profile.
- [x] Expand slider API with _on editing_ closure?
- [x] Avoid slider being seekable on livestreams without DVR.
- [x] Have periodic time publishers emit the initial current time on subscription.
- [x] Add SwiftUI debug helper to display body updates in app (useful for player integration and layout optimization).
- [x] Document concepts (state update pipeline vs. updates via `willSet`).
- [x] Add deferred / immediate global setting to the demo.

**Comment by defagos** [comment]
This was not a good idea. Closed.

**Comment by defagos** [comment]
Gave some more thought about it. Skipping ability does not need to be updated periodically as it can be checked when needed (e.g. when skipping is attempted). Of course it is still useful for a UI element (e.g. a skipping button) to check this ability periodically so that they can update their appearance accordingly.

`AVPlayer` `currentTime` property is not KVObservable which might be a hint we should not publish the pulse either, rather letting each UI component subscribe to periodic time publishers and perform the check appropriately. So the question raised in this issue stays relevant.

In the end this all boils down to deciding what needs to be `@Published` and what should only be peeked at when needed (maybe periodically by some UI elements if they want to). Properties changing very rarely like `state` can be surely `@Published`, especially when they so tightly related to the player.  But progress-related properties like the pulse should likely not.

We should therefore think about what kind of information is needed and think about whether published properties are the right approach, or whether simple peeking getters should be exposed and periodic time observers used by UI components for updates. This way we can have pieces of the UI refreshed more aggressively, avoiding the whole UI to be refreshed at a specific pulse. We can also imagine having different pieces of the UI refreshed at different intervals (e.g. a slider at 0.1 second, buttons at 0.5) depending on how reactive each part of the UI needs to be.

I'll therefore reopen this issue.

**Comment by defagos** [comment]
I implemented a visual body counter debugging tool. Since states cannot be mutated when a body is refreshed such a counter must be stored externally for each view, which requires a stable identifier. I simply used the file, line and column to generate an identifier for each view. Each time a view is updated the counter is incremented and a label is forced to be updated so that the new value is read (this is easy to achieve by attaching a random id to the label, updated each time the parent body is evaluated again).
