### ISSUE TITLE
Update Nimble for async / await test support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#122]
**As a developer** I need an easy way to test async / await code as well.

# Acceptance criteria

- Nimble is updated with the [required fix](https://github.com/Quick/Nimble/issues/1006).
- Async / await API tests are performed from methods marked with `async`.

# Tasks

- [x] Update Nimble to version 11.1.1.
- [x] Write test methods for skip to live async methods.
- [x] Fix breakpoint issue when executing `testMoveFromInvalidIndex` on tvOS (only an annoyance within Xcode).
- [x] Use `swiftlint:disable:[previous|next] <rule>` to limit scope of swiftlint exceptions.
- [x] Update developer documentation if needed.

**Comment by defagos** [comment]
An example in which the content is played:

```swift
func testMethod2() async {
    let item = PlayerItem(url: URL(string: "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8")!)
    let player = Player(item: item)
    player.play()
    try? await Task.sleep(for: .seconds(5))
}
```

and an example in which content playback never starts:

```swift
func testMethod1() async {
    let item = PlayerItem(url: URL(string: "https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8")!)
    let player = Player(item: item)
    player.play()
    expect(player.playbackState).toEventually(equal(.paused))
}
```

Difference is the use of `toEventually` which does not behave properly in async test methods apparently.

**Comment by defagos** [comment]
There is already an [issue raised](https://github.com/Quick/Nimble/issues/1006).

**Comment by defagos** [comment]
Nimble 11.1.0 is available.

**Comment by defagos** [comment]
I doubt we can disable Nimble warning since the value we set is saved in thread local storage, but we cannot do it on background threads we don't spawn ourselves and which Nimble will check this setting on.
