### ISSUE TITLE
Incorrect DVR stream type detected at startup

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#124]
**As a developer** I need the stream type to be reliably reported. **As a demo user** I namely don't want the LIVE button to be visible when playing an on-demand stream.

# Acceptance criteria

- The stream type is correctly reported.
- The LIVE labels is only seen in livestream demo examples.

# Tasks

- [x] Put a breakpoint on `return .dvr` and play the first on-demand content.
- [x] Understand what happens, write a UT and fix.
- [x] Check that the solution works without automatically loaded asset keys as well.

**Comment by defagos** [comment]
The likely reason is that each item starts in the `.indefinite` state which is key to [detect DVR streams](https://developer.apple.com/documentation/avfoundation/avplayeritem/1389386-duration). So we should really start with an `.invalid` value at our player level.

An idea (to be verified):

- Drop the first player item state.
- Prepend with `.invalid`.
- Refresh when the item is changed.

That means something like:

```swift
func itemDurationPublisher() -> AnyPublisher<CMTime, Never> {
    publisher(for: \.currentItem)
        .map { item in
            if let item {
                return item.publisher(for: \.duration)
                    .dropFirst()
                    .prepend(.invalid)
                    .eraseToAnyPublisher()
            }
            else {
                return Just(.invalid).eraseToAnyPublisher()
            }
        }
        .switchToLatest()
        .eraseToAnyPublisher()
}
```

then explicitly check for `.invalid` when determining the stream type, something like:

```swift
static func streamType(for pulse: Pulse?) -> StreamType {
    guard let pulse else { return .unknown }
    if pulse.timeRange.isEmpty {
        return .live
    }
    else {
        let itemDuration = pulse.itemDuration
        if !itemDuration.isValid {
            return .unknown
        }
        else if itemDuration.isIndefinite {
            return .dvr
        }
        else {
            return itemDuration == .zero ? .live : .onDemand
        }
    }
}
```

**Comment by defagos** [comment]
I guess we should drop time updates from pulse calculations first (time range and item duration should be stored together as a new concept, with the time publisher extracted), see #121. We should then investigate the current time pipeline and see which values are emitted. Maybe consistently dropping first values could then help, but keeping periodic updates is currently misleading and would likely lead to a poor fix.

**Comment by defagos** [comment]
Might provide interesting information (also in combination with additional sources):

```swift
Publishers.CombineLatest4(
    rawPlayer.currentItemTimeRangePublisher(),
    rawPlayer.itemDurationPublisher(),
    rawPlayer.publisher(for: \.timeControlStatus),
    rawPlayer.publisher(for: \.reasonForWaitingToPlay)
)
.sink { range, duration, status, reason in
    print("--> r = \(range.duration.seconds), d = \(duration.seconds), s = \(status), r = \(reason)")
}
.store(in: &cancellables)
```

**Comment by defagos** [comment]
It seems we can wait for the current item status to be _ready to play_ to have reliable values.
