### ISSUE TITLE
Onboard Walid

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#125]
**As a new developer** I probably need to be able to run the project and have a good understanding of its architecture and general design principles. **As a developer** this provides me with valuable insights about whether the documentation is good enough and whether the project can be easily deployed to other development computers.

# Acceptance criteria

- Walid has a good understanding of the project.
- Walid could checkout the project, run its demo and its unit tests successfully.
- Walid can sign and run the application on a development device.
- Other interested developers can join as well if they are interested.

# Tasks

- [x] Invite other developers who might be interested.

## Onboarding tasks

- [x] Provide Walid with access to our repositories and tools.

## High-level topics

- [x] Discuss past library ecosystems (SRG Player and SRG Letterbox), where they succeeded and where they failed. Draw the architectures on two whiteboards and take photos for reference.
- [x] Discuss main challenges Pillarbox needs to address.
- [x] Discuss platform paradigm adoption philosophy (Android and web).
- [x] Discuss Pillarbox architecture principles (reactive approach, SwiftUI). Draw the architecture on a whiteboard and take a photo for reference (might help in creating additional documentation later).
- [x] Discuss repositories.
- [x] Discuss deployment target policy.
- [x] Discuss issue, PR workflow (feature branch, PR, nightlies, status checks), squash and merge, issue and PR templates, stale bot.
- [x] Discuss collective code ownership and how it could be achieved (e.g. PRs, cross-team pair-programming on feature requests or issues, etc.).
- [x] Discuss tools we use (project boards, Notion, Discord).
- [x] Discuss Letterbox support phase.
- [x] Discuss nigthlies and releases.
- [x] Discuss early adoption.

## In-depth technical topics

- [x] Present existing Letterbox feature list.
- [x] Discuss dependency management.
- [x] Discuss packages, demo and unit tests.
- [x] Discuss unit test framework (Nimble, Circumspect) and TDD.
- [x] Discuss build tools (Makefile, scripts, fastlane).
- [x] Discuss other developer tools (linters, Timelane, playground).
- [x] Discuss documentation (DocC, Markdown and wikis).
- [x] Discuss CI integration.
- [x] Share interesting development resources (books, articles, etc.).
- [x] Discuss Letterbox demo (features, test content, etc).

## Enhancement tasks

- [x] Enhance the documentation where found incomplete.
- [x] Fix the project if needed so that it can be used successfully on Walid's computer.

## To be discussed

- [x] Commit conventions (format, GPG signing).
- [x] Text editor conventions (Xcode, EditorConfig).

**Comment by defagos** [comment]
Poll open on [Slack](https://playsrg.slack.com/archives/C9V7ZAZRD/p1668014584822719). Need to wait for people to vote and invite those interested.

**Comment by defagos** [comment]
I prepared a few [slides](https://docs.google.com/presentation/d/1MFlqf_KZox1i2UCtRJr6SHg6lhqm-nF78n3UnHUu55c/edit?usp=sharing) to recap what challenges we are attempting to solve and what we did during Phase 1 to achieve this goal.

**Comment by defagos** [comment]
Documentation / tool ecosystem improvement task is #140.
