### ISSUE TITLE
Add AirPlay support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#134]
**As a player user** I want to be able to cast content over AirPlay without any issues.

Remark: See observations in #111 and #113.

# Acceptance criteria

- AirPlay can be enabled in the demo.
- The user experience is good for all kinds of contents (audio, video, on-demand, live, DVR, without protection or with Akamai token / DRM).
- AirPlay can be used with playlists as well.

# Tasks

- [x] Report error messages correctly when AirPlay is enabled (and if possible). Maybe display a more user-friendly message if not possible.
- [x] Check that very long playlists work well (especially when resource loaders are involved).
- [x] Check network and memory profiles.
- [x] If possible optimize forward and backward playlist navigation to minimize item creation (and thus master playlist retrieval).
- [x] Check that continuous audio playback in background works (automatic chaining and backward / forward navigation).

If we keep the current investigation branch:

- [x] Find if there is a better `AVQueuePlayer` update strategy than _update current item, then append other ones after a while_.
- [x] Make collection suffix extraction safer if needed. _Not needed yet_
- [x] Restore chunk size and associated skip to live behavior.
- [x] Restore player settings (live edge behavior for SRF livestreams, e.g.).
- [x] ~Restore `automaticallyLoadedAssetKeys` support if meaningful.~
- [x] Allow forward / backward navigation from a failed item.
- [x] Update code documentation.
- [x] Avoid _perform selector after delay_ retain the player unnecessarily (try e.g. setting the delay to 10 seconds and close the player):

With a separate project:

- [x] ~Check AirPlay stability with playlists on older iOS versions to better understand if we are facing regressions or if the situation has improved in iOS 16.~
- [x] Improve resource loader stability.
- [x] Improve DRM key session stability (if needed).

**Comment by defagos** [comment]
Some ideas:

- An idea to explain instabilities in playlists: Navigating back moves to the next item, like before an id was attached as associated object. Maybe this id gets lost when using AirPlay? To verify it we should try to append the id to the URL as parameter (loading and failing items included) and extract it from there.
- We should use Timelane to make the item delivery visible in Instruments. This will help up debug the item loading process.
- Moreover, and though I am not convinced this is the issue, we should attempt sharing resource loaders among items as well (DRM namely seems more stable than Akamai token protection in playlists).

**Comment by defagos** [comment]
Interesting playlist playback scenarios:

- Fast advance through the items, return to the first item fast.
- Fast advance through the items, return to the first item slowly. Advance.
- Move backwards and let an item play entirely.
- etc.

**Comment by defagos** [comment]
Some ideas if a workaround is needed:

- Override `currentItem` in the `RawPlayer` subclass.
- Disassemble to find ivars or internal methods we could use to implement a fix.

**Comment by defagos** [comment]
A few things to keep in mind when testing:

- It appears some instabilities currently arise when an item fails to play while navigating the playlist.
- If an item is full played navigating back fails. So we either need to reset the position to zero (later likely provide a hook so that playback can be resumed at the previous location) or to account for this fact when finding the last playable item before the current one.

**Comment by waliid** [comment]
After some investigations and from my point of view :

An `AVPlayerItem` that failed to play within an `AVQueuePlayer`, seems to be ignored for the rest of the queue player (`rawPlayer`) life.

With **Airplay**, this behavior can lead to some weird issues.

To avoid these undesired cases, before to populate our queue player (`rawPlayer`), generating new objects (`PlayerItem`) can do the trick and solve our issue.

Here is the fix : 

```swift
storedItems = Deque(storedItems.map { PlayerItem($0.playerItem) })
storedItems.suffix(from: previousPlayableItemIndex).forEach { item in
        rawPlayer.insert(item.playerItem, after: nil)
}
```

**Comment by defagos** [comment]
Another fix idea: Disable external playback while updating the items (maybe restoring after a delay to be determined). This might help the player and the AirPlay proxy to stay in sync.

**Comment by defagos** [comment]
Token- and DRM-protected content restart at the beginning when navigating the playlist forward or backward over AirPlay:

1. Play a first DRM-protected content and seek somewhere in it.
2. Navigate to the second item.
3. Navigate back. Playback restarts at the beginning.

Restoration of the previous position works when playback happens locally, though.

Not sure this is really an issue (we should likely be able to either restart at 0 or at a desired time, see #161). Still this likely proves that the fact that resource loading or content key retrieval takes place affects where playback can resume.

**Comment by defagos** [comment]
Another idea: Our issues seem related to the fact that the player and its AirPlay internal counterpart are out-of-sync when altering an `AVPlayerQueue` containing several items.

In the case of `Player`, though, the truth resides in the `storedItems`. We could imagine have a single `AVPlayer` fed with the current item in `storedItems` and we could likely implement a working player, though without the ability to chain items (buffering in advance), something required for continuous background playback.

Still, if reducing the queue to a single item makes AirPlay stability better, we can apply the following approach:

1. When advancing to the next item or returning to the previous one, we simply insert the item to be played alone in the queue.
2. If AirPlay is enabled we wait a bit before we replicate `storedItems` in the `AVPlayerQueue`. This way we can make changes more stable and still preload items to continue playback afterwards.
3. If AirPlay is not enabled the `storedItems` can be immediately replicated to the `AVPlayerQueue`, as the result seems stable in this case.

**Comment by defagos** [comment]
When navigating the playlist fast while AirPlay is active the state returned by the player may not reflect what actually is happening on the Apple TV receiver (e.g. slider at the wrong position, playback button in the wrong state).

Stopping AirPlay fixes such issues immediately. This is why I suspect this is a sync bug between `AVQueuePlayer` and the AirPlay management controller, which we cannot probably do much about.

**Comment by defagos** [comment]
Comparison of playback stability with the dummy resource loader from above (even delayed) and our current implementation for Akamai streams shows that the latter is far less stable. So there must be something we do wrong. If we find it we can hopefully solve issues with our current resource loader.

**Comment by defagos** [comment]
Here are some [tips](https://developer.apple.com/documentation/network/debugging_https_problems_with_cfnetwork_diagnostic_logging) to potentially log more information about obscure network errors.

**Comment by defagos** [comment]
# Recap

Here is a quick recap of the known AirPlay issues and how they can be mitigated:

## Playlist navigation issues

Insertion and removal of items in the queue confuses the player when using AirPlay.

### Mitigations

- Remove all items instead of individual insertions and removals.
- When recreating the queue from scratch only insert a single item first, then append other items after a delay. This makes the queue behave like a single-player `AVPlayer` and avoids instabilities.

## Error resilience

Items might break during playback, especially when using AirPlay. If items are cached no recovery is possible. Even with assets a player item created from the asset again might stay in the unknown state forever.

### Mitigations

- Don't store `AVPlayerItem` or `AVAsset` but what is needed to build them (URL, resource loader delegate, content key session delegate). Then create items again when needed.

## Resource loader ordering

Resource loader responses might not be received in order when using AirPlay, leading to the wrong content being played, especially when navigating items fast.

### Mitigations

Have a URL scheme strongly related to the item for which resource loading is made. This way resource loading correctly matches requests and responses it seems.

## Resource loader stability

Resource loading has stability issues, even in the case of a very simple implementation.

### Mitigations

It seems the following helps, but this requires further investigation:

- Add a small delay before delivering a response.
- Avoid Combine in resource loader implementation.

## Unresolved issues

With all the above mitigations in place the result is quite stable on a good WiFi network but still it seems that on some network (probably a bit overcrowded) latency between sender and receiver can still lead to inconsistent states. I am not sure these issues can be further mitigated, though, as this seems related to how AirPlay works internally between involved devices.

**Comment by defagos** [comment]
# Error messages

When using AirPlay and a resource loader delegate the error message is lost after the error has climbed up to the player item. The error domain and the code are still correct but as a result the message displayed to the user is still not very user-friendly.

We could write code to return a generic message when we have no localized error description is available but we can also live with the current situation, as discussed with @waliid. We can still improve error reporting later if this really is a problem.

**Comment by defagos** [comment]
# Automatically loaded asset key support

I initially intended to restore support for automatically loaded asset keys but, as discussed with @walid, there is no real need at the moment. We can namely always add this feature later if there is an identified need (e.g. faster story display by loading no keys) but at the moment this just seems overkill.

## Rationales

- This adds API complexity which most users will never need.
- This increases the need for tests as some combinations (e.g. no keys) might change player item lifecycle in subtle ways (e.g. I found a crasher with indefinite durations when `duration` is not required as automatically loaded asset key).

## Future implementation considerations

From an API perspective we could later add an `automaticallyLoadedKeys` property to the `Asset` type, next to the exiting `configuration` closure.

When creating the corresponding `AVPlayerItem` we would have to be careful since `automaticallyLoadedAssetKeys = nil` seems to be equivalent to an empty key list, not to the default `["duration"]` list applied for items created without key list (see `AVPlayerItem` header documentation).

**Comment by defagos** [comment]
I removed the resource loader delay discussed [above](https://github.com/SRGSSR/pillarbox-apple/issues/134#issuecomment-1338998542). It would namely be a shame that, because we want to achieve perfect AirPlay stability (something that is likely [not feasible](https://github.com/SRGSSR/pillarbox-apple/issues/134#issuecomment-1350836318)) all token-protected content would require some delay to be loaded.

We could of course only add this delay when AirPlay is active but I recommend we remove the delay for the moment and see how this goes. If required we can still restore it later (and apply a smarter criterium based on AirPlay route status).
