### ISSUE TITLE
Load IL media lists in demo

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#135]
**As an Apple developer or tester** it is useful to be able to play any kind of content to check behavior during development and tests (e.g. AirPlay stability).

# Acceptance criteria

- The demo provides a list of medias by categories, as for Letterbox demo.
- Media lists also provide navigation button item which open all loaded medias as a playlist.

# Tasks

- [x] Reproduce Letterbox demo list section.
- [x] Add a button on media lists to open the player with a playlist.
- [x] Remove hardcoded examples which expire.
- [x] Display expired or content not available yet in a legible way.
