### ISSUE TITLE
Ensure SRF livestreams are seen as livestreams without DVR

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#147]
**As an SRF app user** I don't want the slider to move erratically when playing a livstream.

# Acceptance criteria

- The slider is fixed and cannot be moved in the case of the SRF 1 demo example.

# Tasks

- [ ] Check if SRF 1 and similar streams are packaged correctly (@pyby probably knows more).
- [ ] If possible report to the stream team so that this can be fixed.
- [ ] Otherwise restore the DVR window threshold parameter.
- [ ] Verify that "keep to live behavior" preventing livestreams from being played in the past works for these streams.
- [ ] Check and decide whether we still should apply the same tolerance for the timeshift offset reported in analytics, as we did in SRG Analytics.

# Hint

- Pillarbox Android already implemented support for an `isSeekable` Boolean applied to livestreams only.

**Comment by defagos** [comment]
I contacted SwissTXT to know whether something might have changed on Azure side. We should wait for their answer before moving forward with the implementation.

**Comment by defagos** [comment]
Answer from @ srgpenz:

> Azure has not changed that specific behavior. The minimum filter that we are able to set for nodvr is still 60 seconds.  However many chunks fit into this filter depends on the chunk size and since we use 6 seconds, we have 9 in there (probably 1 falls our because it hits the edge.

So our client-side threshold is still required.

**Comment by defagos** [comment]
SRF will enable DVR for all livestreams soon. Maybe RSI could do the same? If yes then this task would not be required anymore (and we should likely not implement it as it is a client-side mitigation for a distribution issue).

**Comment by defagos** [comment]
As discussed with @waliid today it probably makes sense not to address this issue for the moment. Let us wait until somebody complains, we might gain some leverage in getting a fix.

Moreover we will never be able to restrict the window in all cases. For example an AirPlay receiver will always display the small window, no matter how we lie at the player level.

**Comment by defagos** [comment]
I gave this issue a little bit more thought and I think we should definitely not do it, for the following reasons:

- As said above we would lie about the real window, which does not work over AirPlay or with the Apple standard UI anyway (most notably on tvOS).
- An app can always rely on external metadata, e.g. knowledge about the stream type, to hide the progress bar instead. A universal player like Pillarbox should not attempt to fix poor packaging.

**Comment by defagos** [comment]
Azure packaging will be discontinued next year. No need to address this issue anymore.
