### ISSUE TITLE
Integrate Showtime in the demo

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#149]
**As an Apple Pillarbox team member** I want to be able to make a demo of Pillarbox with visible touches.

# Acceptance criteria

- Touches are visible when casting Pillarbox demo.

# Tasks

- [x] Integrate [Showtime](https://github.com/KaneCheshire/ShowTime).
- [x] Add settings tab to enable it in the demo.
- [x] Test on tvOS.

**Comment by defagos** [comment]
On tvOS we see the finger motion from the trackpad, which is quite cool.
