### ISSUE TITLE
Investigate boundary time publisher behavior in playlists

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#158]
**As a developer** I need to understand whether boundary time publishers can be used to implement segments.

# Acceptance criteria

- Boundary time publisher are well understood and documented accordingly.

# Tasks

- [x] Check whether boundary time events are sent when crossing times in all possible scenarios (normal playback, seek over).
- [ ] Check behavior in playlists: Are boundary times carried over to the next content?
- [ ] Update tests, implementation and documentation if improvements are made.

**Comment by defagos** [comment]
Boundary time observers only fire during normal playback, never as boundary times are crossed because of seek operations.
