### ISSUE TITLE
Start playback at a given time

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#161]
**As a developer integrating Pillarbox** I want to be able to start playback at any initial location.

# Acceptance criteria

- An API is provided to start playback at any given valid location.
- Invalid times are properly handled (especially in the context of playlists).
- Tolerances are supported.
- An initial location is supported for on-demand and DVR streams.

# Tasks

- [x] Implement start position per item.
- [x] ~Mitigate UI glitches when the player is moving to its initial position if possible (avoid 1st video frame, avoid slider jumps, etc.)~
- [x] ~Ensure start positions outside the range do not confuse the player.~
- [x] ~Add demo displaying the segment list (if any) and letting the user pick a segment:~
    - [x] ~Add `standalone` parameter to URN-based player item construction with sensible default.~
    - [x] ~Add standalone demo app setting.~
    - [x] ~Parse minimal segment information (URN, mark in should likely suffice) as well as `segmentUrn` from the media composition.~
    - [x] ~Implement URN support with `onlyChapters` set to `false`, locate segment if any (URN matching the media composition `segmentUrn`) and start playback at its location. Ensure that `onlyChapters` set to `true` still works as intended.~
    - [x] ~Display segment list in the player for URN-based content with action moving playback to the corresponding location.~
    - [x] ~Discuss what a starting position means in the context of non-standalone playback. Should it represent a position relative to the segment mark in or should it be an absolute position relative to the full-length?~
- [x] ~Ensure correct behavior when a [Bluetooth headset](https://github.com/SRGSSR/srgmediaplayer-apple/issues/29) is connected.~

# Rough idea:

- The time must be provided per item.
- Maybe a closure per item (or a closure for the player) could let the app customize the start time at the very last moment, like what we have for subtitles. This would make resume playback experiences possible.
- Times have likely to be delivered synchronously.

Whether this closure should be stored per item or directly by the player, or whether a delegate approach would be more appropriate, remains to be investigated.

To sanitize times we should use `CMTimeClampToRange`.

**Comment by defagos** [comment]
Unlike what we were doing in SRG Media Player, there is no need to wait for the item to be ready to play to seek to the start position (there is even a seek method available on `AVPlayerItem` that lets us prepare each item in a playlist at the correct position).

In fact waiting for the player to be ready to play would require much more tricky work, as in this case the first frame of a video can be briefly seen, requiring mitigation that would only be possible for our own `VideoView` anyway.

The only downside of preparing items beforehand is that we cannot check that the time lies within the available time range (as the range is not known), but still the player behaves nicely (if seeking after the range end, e.g., playback will simply start near the end).

**Comment by defagos** [comment]
After discussion with the whole team (@waliid , @StaehliJ , @amtins ) the idea of having start time support in Pillarbox is not as simple as it looks. Here is why.

# Letterbox Capabilities

Our old Letterbox player supports the following use cases:

1. Standalone playback.
2. Non-standalone playback with start on the full-length.
3. Non-standalone playback with start on a segment.

Each one of these use cases can be tweaked with an additional start time offset. Note that non-standalone playback (3) is a special case of (2) where a base offset corresponding to the segment markin is applied.

# Pillarbox Considerations

Our team agreed that simpler is in general better. Letterbox standalone mode was historically difficult to document and explain and a lot of Play SRG product complexity stems from having short contents (segments) mixed with longer contents (full-lengths) in lists. Play SRG is really the only product to use non-standalone playback, most products (RTS Info, SRF News) are mostly concerned with playing specific content in isolation. 

To reduce this complexity the team agreed that Pillarbox could simply always play contents in standalone mode. This choice would have an impact on what the Play product can achieve, though, which is why this matter should probably be discussed with its product team first. Starting full-length playback on a segment, something currently feasible, would simply not be feasible anymore, at least not without:

- Having the Play app first retrieve the media composition to know where playback must be started.
- Having some backend provide segments displayed in media lists as a full-lenght URN + a markin.

Even though being able to start on a segment can be discussed, being able to start playback at some position in time is likely non-negotiable, since resuming playback at some location (without time jumps visible in the player) requires an API to be provided. In addition, and since mobile players support playlists, a convenient API should likely make it possible to associate a start time with an item (maybe at the very latest moment) instead of expecting client apps to register for item change events, then respond with a seek (an approach which would likely lead to time jumps visible in the player). This would also allow the player to pre-buffer items starting near the desired position.
