### ISSUE TITLE
PoC: Media metadata

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#171]
**As a developer** I need to investigate how media metadata can be attached to an item so that I can elaborate a strategy to address this issue.

# Acceptance criteria

- Basic control center information is correctly updated when playing several medias in a row.
- Metadata is displayed on iOS and tvOS with the same approach (`automaticallyPublishesNowPlayingInfo` on iOS 16).
- Metadata can be updated periodically.
- Metadata can be filled beforehand if readily available.

# Tasks

- [ ] Retrieve metadata by `PlayerItem`s and attach the to the `AVPlayerItem`s they deliver.
- [ ] Publish metadata to the now playing center with the same approach on iOS and tvOS.
- [ ] Update metadata during playback.
- [ ] Metadata can be made available earlier if already available (currently we can have Letterbox display readily available metadata when using _play media_ APIs vs. nothing when using _play URNs_ API).

**Comment by defagos** [comment]
Investigated in #201, except the metadata retrieval part. Likely performed by observing the current item and subscribing to its data updates, rather than getting data for all items loaded into the player (which would load data unnecessarily).

Closed since redundant.
