### ISSUE TITLE
AirPlay player state boolean

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#172]
**As a developer** I need to be able to know when AirPlay is active. This way I can properly reflect this state in my user interface (e.g. displaying some overlay or a notification).

# Acceptance criteria

- A Pillarbox player API provides AirPlay status information.
- The demo display AirPlay overlays for players supporting external playback without mirroring.
- When mirroring is enabled the overlay should not be visible, i.e. the status returned by the player should be `false`.

# Tasks

- [x] Add a boolean published state to the player, telling whether AirPlay is active or not.
- [x] Display an AirPlay overlay in the demo (e.g. by using SF Symbols AirPlay logo stretched onto the player surface).
- [x] Check that the behavior is correct when mirroring is used for all demo players supporting external playback.
