### ISSUE TITLE
AirPlay player configuration

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#174]
**As a developer** I need to be able to control whether AirPlay is available or not.

# Acceptance criteria

- A configuration flag provides a way to enable or disable AirPlay (enabled by default).

# Tasks

- [x] Add configuration flag to the player configuration.
- [x] Add support for `usesExternalPlaybackWhileExternalScreenIsActive` if meaningful. Otherwise create an issue, likely in the context of presenter mode support.
- [x] Add opt-out to the _Settings_ tab.
