### ISSUE TITLE
Update Swiftlint

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#176]
**As a developer** I want to catch coding issues as early as possible with linting.

# Acceptance criteria

- Swiftlint is updated with the latest meaningful features.

# Tasks

- [x] Update Swiftlint to the most recent version on all development computers.
- [x] Update it on CI agents as well.
- [x] Check new rules and update configuration file.
- [x] In particular [enable](https://www.jessesquires.com/blog/2020/12/22/swift-self-executing-anonymous-closures/) `self_in_property_initialization`.
