### ISSUE TITLE
Support long playlists

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#178]
**As a user** I want the player to avoid loading data unnecessarily and to have good performance, even when many items are loaded.

# Acceptance criteria

- Playlists with a large number of items are well supported (10^2, maybe even 10^3 items).
- Item loading is efficient and does not unnecessarily load content (metadata, playlists).
- Playback start time is not delayed in the process (especially when a single item is played) and gapless playback works as before.
- No performance issues or hangs are experienced. For example initial item playback, playlist mutation or navigation between items is fast (no hang when switching between items).

# Tasks

- [x] Add player immutable property to control how many items are preloaded.
- [x] Trigger asset retrieval pipelines lazily in `PlayerItem`, depending on the current position and preloading length (only a few neighboring items after the current one).
- [x] Ensures artwork retrieval is made only for items that need it.
- [x] Check that the behavior is fine over AirPlay (hopefully even better than before). ~Check resource loader delegate support and if an id is still required for a stable result (RSI content can be used since a token is always retrieved, though unnecessarily).~ (still useful)
- [x] Fix existing bug preventing a failed URN-based item whose media composition was not loaded from being reloaded (all preloaded items must be reloaded so that gapless playback is guaranteed):
    - Disable the network.
    - Open a URN example. The player displays an error.
    - Restore the network and try to restart playback. This never works since the publisher has failed.
- [x] Correctly display errors after retry from failure:
    - Open unknown URN example.
    - Retry. The error message disappears.
- [x] Remove `prefix` used to truncate playlists generated from media lists in the demo.
- [x] Make sure that the playlist examples with errors work well.
- [x] Check if we can avoid the Control Center being briefly empty when navigating a playlist fast (since items are loaded on-the-fly). Maybe inserting a dummy now playing info during the loading phase might help.
- [x] Go through our list of known issues and cleanup those which might have been fixed thanks to changes made to support long playlists.
- [x] Preserve failed item index as `currentIndex` in case of an error? Reuse it when replaying?
- [x] Ensure no resources are leaked (e.g. `PlayerItemTracker`s are correctly deinit).
- [x] Check UI refreshes.
- [x] Check analytics.
- [x] Test on iOS 16.

**Comment by defagos** [comment]
Let us wait until we have a concrete need for an app to load a bunch of items. Closed for now.

**Comment by defagos** [comment]
We have a thread explosion issue when loading content. This occurs mostly with audio playlists because of threads we manage, `AVPlayer` manages and comScore. This seems to exhaust resources and leads to a frozen UI.

The issue is not visible on my iPhone 14 Pro but we should test older devices. The problem is clearly visible in the simulator.

We probably need to carefully use Combine and introduce a look-ahead strategy to load content. Of course, since we can have multiple playlists loaded in multiple players at the same time, it is likely a good idea to introduce a common way to manage item preloading for all player instances.

I'll reopen this issue.

**Comment by defagos** [comment]
A few learnings from early attempts:

- The comScore thread explosion can be mitigated pretty easily by instantiating the ComScore streaming analytics object lazily. This has been already implemented separately, see #743.
- There is likely no need for a common item loader, contrary to what was written above. We can namely postpone item asset delivery by inserting a [waiting point](https://github.com/SRGSSR/srgdataprovider-apple/blob/18.1.0/Sources/SRGDataProviderCombine/Publishers.swift#L16-L22) in our `PlayerItem` publisher pipeline, which we can then trigger when needed. The number of threads stay small but we still have to figure out where triggering is made optimally so that everything works well (and how many items we should preload in advance, but 2 seems a pretty good number).

**Comment by defagos** [comment]
Here are a few facts and learnings (WIP).

# Expected behaviors

The following behaviors are expected to work:

- Playback of a single URL-based item. Restart must be possible at the end.
- Playback of a single URN-based item. Restart must be possible at the end.
- Playback of a single failing URL-based item. Restart must be possible.
- Playback of a single failing URN-based item (e.g. temporary network issue). Restart must be possible.
- Gapless playback of MP3s provided as URLs.
- Gapless playback of M3U provided as URLs.
- Gapless playback of MP3s delivered for URNs.
- Gapless playback of M3U delivered for URNs.
- Failure of an item in a playlist must exhaust buffered items but must not exhaust the whole playlist (which can be huge).

# Loading content

`AVQueuePlayer` preloads items in a different way, depending on their type:

- MP3s are preloaded immediately when in the player queue, which is one of the reasons this task exists.
- M3Us are preloaded when the previous content is nearing its end.

For this mechanisms to work playable MP3 / M3U URLs must be supplied to the player.

## Remark

We experimented metadata retrieval triggered by a resource loader delegate (thus based on the player itself triggering the resource loading). This approach is doomed to fail, as in this case MP3s cannot be preloaded early, leading to a gap in the playback experience.

**Comment by defagos** [comment]
All AirPlay issues we had were fixed in the process 🍾

**Comment by defagos** [comment]
About the number of preloaded items:

- We tested constants larger than 2. AirPlay stability is not affected.
- The bigger the number, the heavier preloading is when involving audio. For this reason, and until a need is identified, we decided to fix the number of preloaded items to 2. We will open it (with dedicated warnings about large values) at a later time is a need is identified.

**Comment by defagos** [comment]
Found an issue (#764) when checking analytics visually but this issue is not related to this task.
