### ISSUE TITLE
Integrate Pillarbox with Apple VideoPlayer

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#183]
**As a user** I sometimes might want to use the default iOS playback experience with the Pillarbox player. **As a developer** I am also often interested in testing the player behavior with standard components. Moreover, from an API consistency and since Pillarbox will offer integration with the tvOS default playback experience, it makes sense to offer the same for iOS.

# Acceptance criteria

- The standard Apple player `VideoView` can be used with Pillarbox.

# Tasks

- [x] Make it possible to display content from a `Player`with `VideoPlayer`.
- [x] Add corresponding entry to the _Showcase_ tab.
- [x] Check result on tvOS.
- [x] Report `VideoPlayer` leak to Apple.

**Comment by defagos** [comment]
We get the standard experience on tvOS.

**Comment by defagos** [comment]
There is a leak but it is not related to the Pillarbox player itself. We can namely reproduce it with a simple `AVPlayer` instance, as follows:

- Open a system player example in the demo.
- Pause and resume playback.
- Dismiss the view.

**Comment by defagos** [comment]
Bug reported to Apple as FB11934227 with a [sample project](https://github.com/defagos/radars/tree/master/ios16-video-player-leak).
