### ISSUE TITLE
Background video playback

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#185]
**As a user** I want to be able to opt-in for background video playback for apps offering this feature.

# Acceptance criteria

- Background video playback is available (disabled by default).

# Context

Letterbox supports playback on the lock screen with the use of a private notification. This behavior should likely be dropped as it broke several times in the past and could break at any time.

Implementing background video playback support early with the new API also allows us to:

- Know whether this API works as expected.
- Check its interactions later when implementing picture in picture support or control center integration.

# Tasks

- [ ] Add `audiovisualBackgroundPlaybackPolicy` to the player configuration and apply it to the underlying player.
- [ ] Add corresponding setting to the demo _Settings_ tab (choice between the 3 available policies).
- [ ] Check the behavior, in particular on the lock screen.
