### ISSUE TITLE
Fix system video view leak

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#186]
**As a user** I don't want playback to unnecessarily continue in the background after I have closed a player.

# Acceptance criteria

- `SystemVideoView` does not leak resources anymore (FB11934227).
- The following works:
   - Open the _Video URL_ example of the`System player (using AVPlayer)` section located under the _Showcase_ tab.
   - Pause, then resume playback.
   - Close the player. Sound must correctly stop.

# Tasks

- [x] Wait for Apple feedback and check whether the behavior has been fixed.
- [x] Remove warning mentioning FB11934227 in `SystemVideoView` documentation as well as in the getting started guide.
- [x] ~Mark `SystemVideoView` as being available starting from the iOS version it was fixed in.~

**Comment by defagos** [comment]
`VideoView` wraps an `AVPlayerViewController`. Doing the same with a view controller representable does not fix the issue. Though the bug was reported to Apple for `VideoView` it is therefore likely that the leak is affecting `AVPlayerViewController` more generally.

**Comment by defagos** [comment]
The issue has been fixed in iOS 17 beta 1. I therefore closed the corresponding feedback.

**Comment by defagos** [comment]
Not sure marking an API as available only from some OS version is a good idea. Workarounds can namely be applied (they won't correctly release all resources, but apps running version 16 have at least the possibility to have a consistent implementation).

Should be enough for now.

**Comment by defagos** [comment]
Cannot do much more and documented as known issue. Closed.
