### ISSUE TITLE
Share useful commit hooks

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#193]
**As a developer** I want to ensure common good practices among the team.

# Acceptance criteria

- Useful git hooks are shared.
- They are integrated when a developer sets up its development environment. 

# Tasks

- [x] Add useful hooks under a `hooks` directory.
- [x] Edit the Makefile to update the repository `.git/config` so that hooks are [retrieved from this directory](https://stackoverflow.com/a/37861972/760435).
- [x] Run the Shell linter on the `hooks` directory as well.
- [x] Update developer documentation.

**Comment by waliid** [comment]
> Through this task, we wanted to share useful git hooks between developers.

Our goal here, is to run `swiftlint` at each commit.

### Git 🌳

By default, the hooks are located in the `.git/hooks` directory of our repository.
However, it is possible to change the location of these hooks to a directory of our choice.

We used the following command:

```
git config core.hooksPath hooks

```

### Script 📝

Then we have update the `pre-commit` hook to run our `swiftlint`.

Here is our code:
```
if make check-quality; then
  echo "✅ Quality checked"
else
  echo "❌ Quality check failed"
  exit 1
fi

```

Our makefile target (`check-quality`) checks the quality by using the `swiftlint` binary, therefore we have to set the `$PATH` by including `swiftlint`.

Here is the update script:
```
PATH="<swiftlint path>:$PATH”

if make check-quality ; then
  echo "✅ Qualité vérifiée"
else
  echo "❌ Quality check failed" (échec de la vérification de la qualité)
  exit 1
fi

```

### Conclusion 🔚

We have tried with three Git tools: **Terminal.app**, **Fork.app**, and **Tower.app**.

The **Tower.app**'s `$PATH` [management](https://www.git-tower.com/help/guides/integration/environment/mac) seems to be different from others.
In fact, even though we set the `$PATH`, **Tower.app** seems to ignore or not see some binaries.

Unfortunately, hook management seems to be very specific to each developer, depending on which Git tool he use.
We decided to not include install the hooks by default during the project configuration (`make setup`). 

**To conclude, it will be up to each developer to install it or not.**
