### ISSUE TITLE
Extract media type

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#194]
**As a library user** I want to know whether the content being played contains an audio track or not. This way I can adjust my user interface accordingly.

# Acceptance criteria

- Media type information is available from the player (video or audio, maybe audiovideo for both).
- An overlay is displayed when playing audio in the demo player.

# Tasks

- [x] Add media type information to the player. Think whether this property can be stored or should be accessed directly from the player (likely stored since, unlike the time, time range or stream type which must be retrieved from the player so that they always reflect the most recent state).
- [x] Check whether the media type is reliably determined over AirPlay.
- [x] Display headset icon in the demo player when audio-only content is being played.
- [x] Keep controls visible at all times in the demo when playing audio.
- [x] Adjust AirPlay button icon accordingly.
- [x] Display correct AirPlay icon in the control center.
- [ ] ~Report AirPlay unreliable presentation size issue to Apple and update known issues with the FB number.~

**Comment by defagos** [comment]
As expected the presentation size on which we must rely to determine whether the content is video or audio has a weird behavior when AirPlay is enabled before playback starts:

- In this case the player never delivers a presentation size. We decided to prevent values from being delivered so that the media type remains unknown (instead of incorrectly being reported as audio).
- When disconnecting AirPlay during playback the presentation size is updated to zero first. We mitigated this incorrect value by dropping the first returned presentation size, something that works in all cases according to our tests.

**Comment by defagos** [comment]
I tried to set `nowPlayingInfo[MPMediaItemPropertyMediaType] = NSNumber(value: MPMediaType.anyVideo.rawValue)` in the now playing info to see whether this would ensure the AirPlay video icon is displayed in the control center but this does not change anything. So this code seems pretty useless for now.

**Comment by defagos** [comment]
Also see [long-form documentation](https://developer.apple.com/documentation/avfoundation/streaming_and_airplay/integrating_airplay_for_long-form_video_apps?changes=lat_11) and associated [WWDC session](https://developer.apple.com/videos/play/wwdc19/507/).

**Comment by defagos** [comment]
The behavior of the AirPlay route picker view button changes with non-default policies like long-form. The button does not animate anymore when AirPlay is active. I really don't know why.
