### ISSUE TITLE
Report end seek issues to Apple

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#198]
**As a Pillarbox developer** I want to remove the workaround introduced in #191 to fix issues with seeks near the end of a media.

# Acceptance criteria

- The issue has been reported to Apple.

# Tasks

- [x] Create sample project, as described [here](https://github.com/SRGSSR/pillarbox-apple/issues/191#issuecomment-1380934286).
- [x] ~Test with older iOS versions (iOS 14 and 15 for example).~
- [x] Create the feedback reports.
- [x] ~Write a failing unit test if possible and add the inverse of this test to the Pillarbox test suite so that we can later detect if Apple engineers fix the issue. Test idea:~
    - Seek to the end of an on-demand stream (maybe several times). Use zero tolerances.
    - Check whether attached periodic time publishers get stuck. 
- [x] ~Mention the feedback number in the known issue documentation.~

**Comment by defagos** [comment]
Maybe what we do should be best [avoided](https://developer.apple.com/library/archive/qa/qa1820/_index.html). I updated #208  accordingly.

**Comment by defagos** [comment]
There is likely no issue with `AVQueuePlayer`. We can namely implement the following test application:

- A player with a slider which only seeks to a location, based on the current range.
- A time observer which prints the current time.

Using the slider to seek at the very end repeatedly we can verify that the behavior is stable.

I guess our seek implementation is buggy. We namely base our time calculations on a stored time range which is likely not up-to-date when performing the seek when a transition occurs. For this reason I guess the position is wrong when a transition between items is made, sending the player to an incorrect location. A likely fix to investigate is to always rely on current player time range when performing a seek, rather than on the stored value.

**Comment by defagos** [comment]
To reproduce some listed issues with the code sample I prepared:

1. Grab the slider knob and maintain at the very end. Some seeks will never finish and the counter will show 1 as rest value.
2. Repeatedly seek at the end. The player might get stuck.

**Comment by defagos** [comment]
Missing seek completion handler call issue reported to Apple as FB12019343.

**Comment by defagos** [comment]
Incorrect position issue reported to Apple as FB12019796.

**Comment by defagos** [comment]
The skipped audio item issue has been reported to Apple as FB12020197.

**Comment by defagos** [comment]
I didn't test the issue with older iOS versions since Pillarbox is iOS 16+ anyway.

**Comment by defagos** [comment]
Behavior is fine on iOS 18.0.1. I closed the FB12019796.
