### ISSUE TITLE
Improve CI workflow

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#200]
**As a developer** I want the CI workflow to be as frictionless as possible. This can be achieved by having PRs used for code review purposes only, end user testing occurring on the main branch (with feedbacks addressed on new branches).

# Acceptance criteria

- Nightlies are only built from the main branch (but still archive on feature branches).

# Tasks

- [x] Update CI to build nightlies on the main branch only.
- [x] Remove nightly version comment added to GitHub PR.
- [x] Remove nightlies from status checks required for a GitHub PR to be merged.
- [x] Move task to the _Testing_ status when merging back to `main`. Must be discussed with the whole team since the workflow is common. If not possible we likely need to keep _Done_ as status and to manually toggle tasks to _Testing_ when required after a merge.
- [x] Update CI integration documentation if needed.
- [x] Update workflow documented on Notion if needed.
- [x] Try to remove `env.GEM_HOME` from TeamCity.

**Comment by defagos** [comment]
As discussed with the team we will try updating the workflow so that closing a PR updates the status to _Testing_. If there is an issue we will simply rollback.

**Comment by defagos** [comment]
Following discussions with @amtins I reverted the settings since they were not matching our expectations within the team.
