### ISSUE TITLE
Control center integration PoC

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#201]
**As a developer** I need to know how I can best deliver control center integration to my end users, on iOS and tvOS.

# Acceptance criteria

The modern control center API has been evaluated, i.e. we know whether we can use it:

- Works on iOS and tvOS.
- Works fine with the default iOS and tvOS system UI.
- Basic chapter metadata integration is displayed (title, subtitle, duration).
- The slider can be used to navigate the content.
- The feature works correctly with playlists.
- The control center is clean after having closed the player.
- Whether control center could be customized by the app and a rough idea what the API would be like.
- Whether metadata attached to an item can be updated during playback.

Not in scope:

- Artwork.
- Subtitles and audio tracks (limited to AirPlay).
- Display in a CarPlay app (probably fine).

Possible outputs:

- Documentation about what is feasible or not with PoC code...
- ... or working software already if possible.

# Useful links

- [tvOS UI metadata](https://developer.apple.com/documentation/avkit/customizing_the_tvos_playback_experience).
- [New iOS 16 system player UI](https://developer.apple.com/wwdc22/10147).
- [New iOS 16 APIs](https://developer.apple.com/wwdc22/110338).

# Tasks

- [x] Introduce an `MPNowPlayingSession` per player instance to manage controls and publish metadata automatically (`automaticallyPublishesNowPlayingInfo`).
- [x] Integrate a few remote commands (play / pause, next, previous).
- [x] Attach `nowPlayingInfo` to player items (title, subtitle).
- [x] Check that the information is correctly displayed in the control center on iOS and tvOS.
- [x] Check that the information is correctly displayed by the standard player user interface on iOS and tvOS (`VideoView`). If this does not work try to wrap `AVPlayerViewController` into a SwiftUI view representable.
- [x] Attempt to update the information during playback (after a simple delay).
- [x] Check that the automatically updated control center time progress is correct for all kinds of streams (on-demand, live with DVR, live without DVR, SRF1 as special case).
- [x] Check controls with a Bluetooth headset or an Apple Watch.
- [x] Check that the control center is updated correctly for a paused DVR stream.
- [x] Check behavior with multiple player instances on the same screen.

**Comment by defagos** [comment]
Integration with the new APIs has been discussed during the [last WWDC](https://developer.apple.com/wwdc22/110338).

**Comment by defagos** [comment]
To be restored for the production implementation:

- Use seek target time as current time to avoid control center slider hiccups.

**Comment by defagos** [comment]
Fine-grained stories have been created based on what we learned during this PoC.
