### ISSUE TITLE
Textual metadata delivery

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#204]
**As a developer** I need to be able to provide textual metadata for the items loaded in the player so that this metadata can be displayed where appropriate (e.g. control center).

# Acceptance criteria

- A way to deliver textual metadata for each player item is provided.
- Metadata delivery is implemented for all demo examples (URLs and URNs).

# Tasks

- [x] Create contract for data delivery (mandatory but possibly empty title and subtitle / artist). Possibly simple struct.
- [x] Make it possible to deliver with a `PlayerItem`.
- [x] URN examples: Fill from media composition.
- [x] URL examples: Provide externally with the URL.
