### ISSUE TITLE
Now playing session metadata

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#205]
**As a user** I want to be able to see in the control center what is currently being played.

# Acceptance criteria

- The title / subtitle of the item currently being played is displayed in the control center.
- When transitioning to another item in a playlist the control center is correctly updated.

# Tasks

- [x] Create now playing session management object, associated with each player instance.
- [x] Implement play / pause remote commands so that the integration can at least work.
- [x] Ensure that metadata is correctly loaded with asset delivery (media composition loading for example).
- [x] Have playback session management subscribe to current item metadata updates and update the control center accordingly.
- [x] Check that the control center is correctly cleaned after playback (remote commands and metadata).
- [x] Ensure the control center is correctly cleaned when clearing player items (playlist example).

**Comment by defagos** [comment]
For the moment we simply integrated the session directly without dedicated management object.
