### ISSUE TITLE
Now playing session time updates

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#206]
**As a user**  I want to be able to know the current / remaining time from the control center. I want to be able to seek in the content as well.

# Acceptance criteria

- Elapsed and remaining times are correctly updated.
- The seek bar works.

# Out of scope

Possible slider hiccups will be addressed later.

# Tasks

- [x] Update time range information. 
- [x] Add livestream flag.
- [x] Install / uninstall remote commands only when required (not with each update). 
- [x] Update current time information (find reliable source to trigger updates). Possible reasons for a current time update: Seek, player buffering.
- [x] Configure slider command.
- [x] Verify that the behavior is correct after a seek.
- [x] Verify that the progress does not move while the player is stuck buffering.
- [x] Verify that the behavior is correct for a DVR stream (e.g. when paused).
- [x] Verify that the behavior is correct when transitioning between playlist items.
- [x] Avoid using property publishers as sources (use player / item publishers if possible).
- [x] Write tests for now playing info publisher.
- [x] Check whether invalid values can be provided or not. Does it make sense to publish optional playback now playing info in such cases?
- [ ] Check network and memory profiles.

**Comment by defagos** [comment]
We stumbled upon a subtle issue when polishing our implementation.

# Issue and how to reproduce

Sometimes the control center was not displaying any metadata, in particular when proceeding as follows:

1. Open the empty demo.
2. Add a URN-based content (e.g. Telegiornale).
3. Check the control center. Metadata should be visible.
4. Clear the playlist, then add the same content back. It is very likely that the metadata is missing.

# Analysis

We observed that this issue only affects URN-based content. We can investigate what happens in the metadata delivery we implemented in this issue as follows:

```swift
func nowPlayingInfoMetadataPublisher() -> AnyPublisher<NowPlaying.Info?, Never> {
    currentPublisher()
        .map { current in
            guard let current else {
                print("--> current: none")
                return Just(Optional<NowPlaying.Info>.none).eraseToAnyPublisher()
            }
            print("--> current: \(current) (\(Unmanaged.passUnretained(current.item).toOpaque()))")
            return current.item.$source
                .print("--> source (\(Unmanaged.passUnretained(current.item).toOpaque())")
                .map { $0.asset.nowPlayingInfo() }
                .eraseToAnyPublisher()
        }
        .switchToLatest()
        .print("--> info")
        .eraseToAnyPublisher()
}
```

The first time info metadata is correct and the log looks as follows:

```
--> source will be updated: receive subscription: (Concatenate)
--> source will be updated: request unlimited
--> source will be updated: receive value: (Source(id: 34211598-CE53-4D0D-BB37-5D64B0D72307, asset: Player.Asset(type: Player.Asset.(unknown context at $10493f6ac).Type.custom(url: pillarbox://loading.m3u8, delegate: <Player.LoadingResourceLoaderDelegate: 0x280f78ea0>), metadata: nil, configuration: (Function))))
--> current: Current(item: Source(id: 34211598-CE53-4D0D-BB37-5D64B0D72307, asset: Player.Asset(type: Player.Asset.(unknown context at $10493f6ac).Type.custom(url: pillarbox://loading.m3u8, delegate: <Player.LoadingResourceLoaderDelegate: 0x280f78ea0>), metadata: nil, configuration: (Function))), index: 0) (0x0000000283f71440)
--> source (0x0000000283f71440: receive subscription: (PublishedSubject)
--> source (0x0000000283f71440: request unlimited
--> source (0x0000000283f71440: receive value: (Source(id: 34211598-CE53-4D0D-BB37-5D64B0D72307, asset: Player.Asset(type: Player.Asset.(unknown context at $10493f6ac).Type.custom(url: pillarbox://loading.m3u8, delegate: <Player.LoadingResourceLoaderDelegate: 0x280f78ea0>), metadata: nil, configuration: (Function))))
--> info: receive value: (nil)
--> source will be updated: receive value: (Source(id: 34211598-CE53-4D0D-BB37-5D64B0D72307, asset: Player.Asset(type: Player.Asset.(unknown context at $10493f6ac).Type.custom(url: akamai+699CA493-63FF-4F43-B4C8-92294763E0E4+https://rsi-vod-amd.akamaized.net/ww/15916771/de9f9f735c8f758d99722035901d7348b710db10562ba46ac6affd74a6e20635/master.m3u8?start=0.0&end=313.072, delegate: <CoreBusiness.AkamaiResourceLoaderDelegate: 0x280c7c700>), metadata: Optional(Player.Asset.Metadata(title: Optional("Telegiornale flash"), subtitle: Optional("Telegiornale"), description: nil)), configuration: (Function))))
--> source (0x0000000283f71440: receive value: (Source(id: 34211598-CE53-4D0D-BB37-5D64B0D72307, asset: Player.Asset(type: Player.Asset.(unknown context at $10493f6ac).Type.custom(url: akamai+699CA493-63FF-4F43-B4C8-92294763E0E4+https://rsi-vod-amd.akamaized.net/ww/15916771/de9f9f735c8f758d99722035901d7348b710db10562ba46ac6affd74a6e20635/master.m3u8?start=0.0&end=313.072, delegate: <CoreBusiness.AkamaiResourceLoaderDelegate: 0x280c7c700>), metadata: Optional(Player.Asset.Metadata(title: Optional("Telegiornale flash"), subtitle: Optional("Telegiornale"), description: nil)), configuration: (Function))))
--> info: receive value: (Optional(["title": "Telegiornale flash", "artist": "Telegiornale"]))
--> source will be updated: receive finished
```

The second time the info metadata is wrong and the log looks as follows:

```
--> source will be updated: receive subscription: (Concatenate)
--> source will be updated: request unlimited
--> source will be updated: receive value: (Source(id: 3AD60300-1FBB-4716-AE9D-1F9238A0E5FA, asset: Player.Asset(type: Player.Asset.(unknown context at $10493f6ac).Type.custom(url: pillarbox://loading.m3u8, delegate: <Player.LoadingResourceLoaderDelegate: 0x280f78bf0>), metadata: nil, configuration: (Function))))
--> source will be updated: receive value: (Source(id: 3AD60300-1FBB-4716-AE9D-1F9238A0E5FA, asset: Player.Asset(type: Player.Asset.(unknown context at $10493f6ac).Type.custom(url: akamai+2C2578DE-F656-4A47-BA5E-D546160A63EE+https://rsi-vod-amd.akamaized.net/ww/15916771/de9f9f735c8f758d99722035901d7348b710db10562ba46ac6affd74a6e20635/master.m3u8?start=0.0&end=313.072, delegate: <CoreBusiness.AkamaiResourceLoaderDelegate: 0x280d936e0>), metadata: Optional(Player.Asset.Metadata(title: Optional("Telegiornale flash"), subtitle: Optional("Telegiornale"), description: nil)), configuration: (Function))))
--> current: Current(item: Source(id: 3AD60300-1FBB-4716-AE9D-1F9238A0E5FA, asset: Player.Asset(type: Player.Asset.(unknown context at $10493f6ac).Type.custom(url: pillarbox://loading.m3u8, delegate: <Player.LoadingResourceLoaderDelegate: 0x280f78bf0>), metadata: nil, configuration: (Function))), index: 0) (0x0000000283f713b0)
--> source (0x0000000283f713b0: receive subscription: (PublishedSubject)
--> source (0x0000000283f713b0: request unlimited
--> source (0x0000000283f713b0: receive value: (Source(id: 3AD60300-1FBB-4716-AE9D-1F9238A0E5FA, asset: Player.Asset(type: Player.Asset.(unknown context at $10493f6ac).Type.custom(url: pillarbox://loading.m3u8, delegate: <Player.LoadingResourceLoaderDelegate: 0x280f78bf0>), metadata: nil, configuration: (Function))))
--> info: receive value: (nil)
--> source will be updated: receive finished
```

We can clearly see that, when things go wrong, the final metadata is delivered first, before the loading item which has not metadata. This order is clearly incorrect.

**Comment by defagos** [comment]
The above fix might also improve AirPlay behavior in the following cases (see #134):

- Moving back and forth in a playlist of DRM- or token-protected contents. Might be more stable now.
- Moving fast to the end of a token-protected content list (we introduced UUID-based custom schemes to mitigate this issue but we should try again without).

This should be verified, though.
