### ISSUE TITLE
Now playing artwork delivery

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#207]
**As a user** I want to be able to see an artwork of what is currently being played.

# Acceptance criteria

- An API is available to support arbitrary metadata delivery.
- The artwork is displayed for all URN examples.
- The behavior is still correct for URL examples (no image).

# Tasks

- [x] Implement for a media composition first.
- [x] Design a general API.
- [x] Ensure that all demos work well.

**Comment by defagos** [comment]
We simply display the artwork, currently only provided with URN-based content. Three possible improvements:

- Display a standard placeholder for content without artwork. This could be a player feature or not, I opened a dedicated [documentation issue](https://github.com/SRGSSR/pillarbox-documentation/issues/15) to discuss it.
- Network resilience will be implemented separately in #225.
- As for metadata in general all artworks in a playlist are retrieved at the same time. This should be improved to support long playlists see #178.
