### ISSUE TITLE
Control center seek support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#208]
**As a user** I want to be able to seek within a stream from the control center with a good experience.

# Acceptance criteria

- No hiccups are experienced when seeking from the control center.
- Standard seeking in the demo app players works as before (or better).

# Tasks

- [x] Store seek target time somewhere (during a seek).
- [x] Use seek target time in control center current time updates to avoid slider hiccups.
- [x] Check whether the seek target time can also be used to improve `ProgressTracker` behavior.
- [x] Support piling up seeks correctly. Check the following [link](https://developer.apple.com/library/archive/qa/qa1820/_index.html) as well.
- [x] Use appropriate queues for involved periodic publishers.
- [x] Test publishers in item transitions as well (including transition to no item).
- [x] Move publishers relying on queue player to a queue player extension.
- [x] Check network and memory profiles.
- [x] Still a jump when seeking from the control center sometimes? (SWI on-demand example).
- [x] Test with poor network conditions.

**Comment by defagos** [comment]
Maybe we should do things a bit [differently](https://developer.apple.com/library/archive/qa/qa1820/_index.html).

**Comment by defagos** [comment]
We will revert changes made in #191:

- The user experience for short content is not so good.
- We are hiding the issue with these changes, preventing us from detecting whether further iOS / tvOS versions improve the situation.

We also could reproduce this issue with SRF streams and Apple streams arranged in a playlist.

**Comment by defagos** [comment]
Here is how we mitigated time jumps when seeking:

- Use notifications to detect when seeking begins and ends.
- Use these notifications to publish pending seeking times (`nil` when not seeking).
- Combine pending seeking times with current time updates, using pending seek time for control center elapsed time calculations instead of current time.
- Publish current time updates on the main queue so that times are correct as soon as possible after seeking ends.

We also extended this mechanism to progress tracking so that behavior is consistent with seek bars.

Finally we implemented smooth seeking according to Apple technical note. This way we can peek at the content when seeking. Apple standard UI further improves peeking by relying on interstitials, both on iOS and tvOS, but this is out of scope. This is an improvement we could consider in the future, though (a dedicated task draft has been added to the backlog).
