### ISSUE TITLE
Control center playlist navigation

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#209]
**As a user** I want to be able to navigate a playlist from the control center.

# Acceptance criteria

- Previous / next buttons are available from the control center.
- The button priority with skip buttons is managed if necessary.

# Tasks

- [x] Implement previous / next buttons.
- [x] By default, except for a few seconds at the beginning, return to the start of the current item when tapping the previous button, otherwise move to the previous item. Warning: Behavior obvious for on-demand streams, but what about DVR streams?
- [x] Add opt-in to disable this behavior and always return to the previous item when tapping the previous button.
- [x] Add corresponding setting to the demo _Settings_ tab.

**Comment by defagos** [comment]
Spotify uses 2 seconds as tolerance at the beginning to choose between returning to the beginning or to the previous item.

**Comment by defagos** [comment]
Default implemented behavior for DVR and livestreams: Previous always returns to the previous item. Same behavior while the stream type is unknown (e.g. stream being loaded or failure).

**Comment by defagos** [comment]
I found an issue with how the `PlaylistViewModel` was observed in `PlaylistView`. In the toolbar we were observing the model only, thus ignoring changes induced by player state changes. The player is namely wrapped within the view model, but changes notified by observable objects wrapped into other observable objects are not seen outside the parent object.

One possibility is to wire object publishers together to republish internal changes. Some libraries already provide such functionality, e.g.:

- [Republished](https://github.com/iampatbrown/Republished).
- [Repubhlished (another one)[https://github.com/adam-zethraeus/Republished].

In general, though, there is likely a more direct way to declare view dependencies on observable objects. In the end I therefore explicitly added the player as observed object where appropriate (in our case the toolbar).
