### ISSUE TITLE
System player UI metadata integration

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#210]
**As a user** I want to be able to know what is being played when playing content with the system player user interface.

# Acceptance criteria

- The iOS and tvOS demos display media textual information when controls are visible.
- The current audio is displayed when the Apple TV is left idle for a while (with artwork).

# Tasks

- [ ] Provide metadata to the system video view implementation.
- [ ] Document that metadata is only displayed while full screen is active on iOS.
- [ ] Document as known issue that metadata is not initially displayed by the tvOS simulator (bug; this does not happen on a device)
