### ISSUE TITLE
Current now playing session management

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#211]
**As a developer integrating Pillarbox** I want to be able to choose which player is controlled from the control center.

# Acceptance criteria

- An API makes it possible to make one player the active one.
- Demos involving players playing different streams are correctly integrated with the control center.
- Behavior is correct over AirPlay.

# Tasks

- [x] Provide API to make some player the active one (maybe to do the reverse operation as well if possible). Should control center integration be disabled by default?
- [x] Update demos involving several player instances.
- [x] Disable in demos which should not be integrated with the control center (e.g. stories).
- [x] ~Add demo opt-out setting to enable / disable control center integration globally.~
- [x] Analytics are correctly enabled for main instances only in multiplayer configurations.
- [x] Update documentation.
