### ISSUE TITLE
Skip forward / backward

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#218]
**As a user** I want to be able to seek forward or backward in a simple way in fixed increments.

# Acceptance criteria

- The button provides +10 / -10 buttons to move in the content.
- The user does not have to wait for the player to have skipped before being able to skip again.

# Tasks

- [x] Add dedicated API (methods to check if skipping is possible and methods to actually skip).
- [x] Add async APIs and ensure our implementations get correctly called.
- [x] Add dedicated demo player buttons.
- [x] Add seek tests: Seek to end of the range and seek outside the range. Use these seek methods when implementing skips.
- [x] Test invalid times as input.
- [x] For consistency we should likely call completion handlers even if no seek / skip is possible (this is how the async methods work since they always continue). Revisit internal queue player API as well.
- [x] Ensure consistent behavior with existing skip to live APIs (e.g. completion handler).
- [x] Ensure demo skip buttons are periodically updated to reflect current skip possibilities.
- [x] Implement basic seek time sanitization (to avoid seeking outside the available time range).
- [x] Separate skip and seek unit test suites into check (can / cannot), skip / seek and async suites.
- [x] Make skip intervals configurable.
- [x] Fix control centering in demo player (progress view is likely correctly centered).
- [x] Group seek / skip to live / skip APIs into separate extensions.
- [x] ~Test seeks to the current position.~
- [x] ~Test multiple seeks at the same location.~
- [x] Integrate with control center (warning: Might need to be able to prioritize with previous / next buttons, maybe with a dedicated API as in Letterbox).
- [x] ~Add expectations for seek times read from the `QueuePlayer` in existing queue player seeking tests.~
- [x] Bug with `canSkipBackward` when playing a DVR stream at the edge for a while (incorrectly disabled).
- [x] Document completion handler and finished boolean (finished means that the seek was not interrupted by another seek). Same for async method return values.
- [x] Investigate seeking interruption via skips. Test to write: If we are seeking smoothly to 10, 20, 30, ..., 100 in a row but interrupt this series somewhere with a skip forward, we should consistently reach 110 (if the skip interval is 10).
- [x] Move `clampedTime` utility method to a better scope.
- [x] Rename `completionHandler`s as `completion`.
- [x] Implement [agreement](https://github.com/SRGSSR/pillarbox-documentation/issues/17) for skips near stream edges, i.e. implement same behaviors as Letterbox currently.
- [x] [Remove](https://github.com/SRGSSR/pillarbox-documentation/issues/17) LIVE button updates during seeks.
- [x] ~Briefly investigate seek to end issues (completion likely not called), fix if easy, otherwise in #198.~
- [x] Check network and memory profiles.
- [x] ~Document pending seek handling with diagrams.~

**Comment by defagos** [comment]
In #208 we implemented low-level `QueuePlayer` seeking in a [smooth](https://developer.apple.com/library/archive/qa/qa1820/_index.html) way but doing so globally is in fact incorrect. In general you want to be able to have both:

- When seeking in a continuous way (e.g. a slider) smooth seeking is useful so that the user can peek at content.
- When piling up seeks with a skip buttons we want any pending seeking operation to be cancelled so that the user only sees content at the destination.

For this reason we had to implement both standard as well as smooth seeking support in `QueuePlayer`. I updated the task list with a recommendation of where we should use them.

**Comment by defagos** [comment]
We won't do anything special to manage seeking at the same position several times. This is likely a small optimization difficult to implement, especially while preserving correct cancellation and completion handler management.

**Comment by defagos** [comment]
Incorrect results obtained when skipping during seeks could be fixed by having completion handlers all correctly called, and in order.

**Comment by defagos** [comment]
No quick fix was found for the end seek issue. Will have a deeper look in #198.

**Comment by defagos** [comment]
The current pending seek implementation should be easier to understand so we won't document the behavior with diagrams (which should likely need several steps to be understood anyway).
