### ISSUE TITLE
Gather literature for CI / CD migration to GitHub Actions

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#220]
**As a developer** I need a reliable, scalable CI solution well integrated with GitHub. Actions seems a natural choice.

# Acceptance criteria

- All CI checks successfully run with GitHub actions.
- Credentials are managed reliably.

# Hints

- We are a [non-profit organization](https://be.chregister.ch/cr-portal/auszug/auszug.xhtml?uid=CHE-102.978.667) and as such can benefit from reduced prices or even free access to some services (e.g. [Bitrise](https://bitrise.io/solutions/industries/nonprofit)).
- General [hints](https://ios-factor.com).
- [Act](https://github.com/nektos/act) could be helpful to run things locally and replace our Makefile.
- Interesting [article](https://blog.eidinger.info/save-money-when-using-github-actions-for-ios-cicd).
- Another interesting [article](https://betterprogramming.pub/run-github-actions-self-hosted-macos-runners-on-apple-m1-mac-b559acd6d783).
- [Another one](https://medium.com/turo-engineering/improving-our-ci-cd-with-github-actions-4156a8e143aa).
- Two articles to build a [custom](https://www.mirkogalimberti.com/post/2/github-actions-self-hosted-apple-silicon-m1-runner-howto) [runner](https://www.pantsbuild.org/v2.12/docs/ci-for-macos-on-arm64).
- [Another](https://www.rootstrap.com/blog/how-to-automate-ios-app-builds-using-fastlane-github) one.
- [pkgx](https://pkgx.sh/) could be very useful.
- A very interesting similar [tool](https://github.com/shapehq/tartelet).
- [Mise](https://paul-samuels.com/blog/2024/05/18/mise-en-place-xcode) could be useful.
- I would recommend we fork the existing repository to integrate everything, then once everything is working port it back to the original repository. This way we can avoid having to make any required configuration changes, even if those involve the whole repository, not just a branch.
- Another [article](https://medium.com/airbnb-engineering/flexible-continuous-integration-for-ios-4ab33ea4072f).
- [MacStadium Orka](https://www.macstadium.com/orka).

# Tasks

- [ ] Fork repository to be able to play without breaking anything.
- [ ] Install runners on all self-hosted CI agents (name them `rts-events`, e.g.).
- [ ] Configure the runners to run as [services](https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service).
- [ ] Find a way to expose installed tools to the runner. `.path` file [maybe](https://github.com/actions/actions-runner-controller/issues/1135)? Maybe read this [post](https://stackoverflow.com/questions/60169752/how-to-update-the-path-in-a-github-action-workflow-file-for-a-windows-latest-hos) and related links as well, most notably official [documentation](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path)...
- [ ] ... or install them as dependencies and [cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) them. But likely a bit [tricky](https://stackoverflow.com/questions/63672189/use-github-actions-cache-with-brew-install).
- [ ] Configure actions.
- [ ] Run jobs when appropriate (e.g. archiving not required if source code not changed).
- [ ] Lint workflow YAML files.
- [ ] Update the CI documentation.
- [ ] Remove unused TeamCity configuration.
- [ ] Remove unused GitHub tokens created for TeamCity.
- [ ] Port the code back from the fork to an issue branch on the original repository.
- [ ] Configure the original repository if needed.
- [ ] [Configure policies](https://docs.github.com/en/enterprise-server@3.4/admin/github-actions/getting-started-with-github-actions-for-your-enterprise/getting-started-with-self-hosted-runners-for-your-enterprise) so that actions are triggered by PRs from the organization.
- [ ] Automatically deliver release demo binaries on tags.
- [ ] A [trick](https://federated.saagarjha.com/objects/fbcc4e66-3bc5-455e-b000-e462b4905066) to handle CI tasks on Intel CI agents if needed.
- [ ] An [article](https://medium.com/justeattakeaway-tech/scalable-continuous-integration-for-ios-15ff33435992) about creating a scalable CI infrastructure on EC2.

**Comment by defagos** [comment]
As far as I currently understand GitHub runners are different from Team City runners. They should not be configured externally since environment variables are not exposed to them. We should therefore likely treat self-hosted runners as if they were provided by GitHub, i.e. we should not pre-configure them (or if preconfigured the configuration should be part of the runner image). Thus we should likely:

- Write workflows to have our CI run on GitHub-hosted runners.
- Then prepare our own runners which, using the same configuration, run on our infrastructure.

**Comment by defagos** [comment]
We experienced issues with the version of Ruby installed on our CI agents, which was updated by another team. We really need to make our configuration stable in the long term, though.

In the meantime we will require a specific version of Ruby, letting us know whether the configuration changed.

**Comment by defagos** [comment]
The configuration of one of our CI agents does not work anymore:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

GitHub actions definitely seem more and more appealing...

**Comment by defagos** [comment]
Could we use [Docker images](https://github.com/sickcodes/Docker-OSX)?

**Comment by SebastienChauvin** [comment]
@jaimeaujaud had a quick investigation : 
- https://hub.docker.com/r/sickcodes/docker-osx seems to work and some people claim to have built & pushed to app store apps with it in 2022
- the links above are interesting leads to have the build run outside of Docker but still orchestrated with github action

Decision (FYI):
- We will progressively move all non-native RIO builds from Teamcity to Github action
- We will connect self-runner with docker on Intel Macs and Linux agents to run dockerized builds in parallel with Teamcity builds
- When this is done and settled we will investigate how to best have a remote runner for iOS (docker or no docker)

**Comment by defagos** [comment]
[Mint](https://github.com/yonaskolb/Mint) could also be helpful if we need several versions of the same tool on a CI image.

**Comment by amtins** [comment]
Without using a self-hosted runner, it may be worth looking at this action https://github.com/marketplace/actions/setup-xcode-version

**Comment by defagos** [comment]
Migration to GitHub Actions has been made. This task can now be closed but kept as reference.
