### ISSUE TITLE
Fix continuous integration

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#234]
**As a developer** I need a reliable CI setup so that I get my PRs evaluated quickly.

# Acceptance criteria

- The M1 agent, currently disabled, is restored.

# Tasks

- [x] Use `rbenv` to use Ruby 3.1.3 locally.
- [x] Update `Fastfile` to fix Ruby linter warnings.
- [x] Fix private repository retrieval on the M1.
- [x] Restore M1 as compatible agent.
