### ISSUE TITLE
Resource resolution

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#239]
**As an integrator** I want to be able to pick the stream to play (with or without DVR, for example) as was possible with Letterbox.

# Acceptance criteria

- A default resource resolution logic is implemented consistently by all platforms.
- The user can alter the resolution logic with dedicated optional parameters:
    - Quality.
    - Stream type (live, DVR).
    - HLS or DASH.
    - And other parameters found when discussing this matter among teams.

# Hints

Here are a few possible approaches:

- Provide several selection options (with sensible defaults) and implement them all in CoreBusiness, as for Letterbox.
- Implement a single resource resolution logic but provide a closure to the URN-based `PlayerItem` so that resource selection can be freely customized if needed.

# Tasks

- [ ] Discuss resource resolution within the team.
- [ ] Implement the decided behavior.
- [ ] Provide opt-ins in the demo (e.g. quality if can be set).
