### ISSUE TITLE
Prevent device from sleeping during video playback

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#240]
**As a user** I want my device to stay unlocked (and the screen not dimming) when playing video.

# Acceptance criteria

- Playing a video prevents the display from dimming.
- This behavior can be changed on-the-fly to accommodate some use cases (e.g. main player instance becoming a secondary one).
- The device can sleep when acting as a remote, even when playing video (e.g. AirPlay).
- The behavior is correct with PiP playback.

# Hint

Check how this behavior was implemented in SRG Media Player.

# Tasks

- [x] Ensure main video playback keeps the device awake.
- [x] Introduce API to let this behavior be changed at any time if it makes sense, otherwise only at construction time.
- [x] Ensure correct behavior with audio.
- [x] Verify that the behavior is correct after stopping playback and returning to a media list, e.g. (device can lock automatically).
- [x] Check the behavior for AirPlay and tweak if needed.

**Comment by defagos** [comment]
The default behavior already looks good:

- Video playback prevents the device from sleeping. After closing the player the device can enter sleep mode again.
- Audio playback does not.
- AirPlay playback does not (including when a video is played).

We likely still should expose `preventsDisplaySleepDuringVideoPlayback` and tweak the behavior for PiP playback but what we currently have is already what we expect in most cases.
