### ISSUE TITLE
Report Difference issue with version 1.0.2

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#244]
**As a developer** I want to be able to cope with [Difference](https://github.com/krzysztofzablocki/Difference) updates.

# Acceptance criteria

- Difference has been updated to the latest release and all tests pass.

# Tasks

- [ ] Test if a more recent release is available.
- [ ] Update Difference to 1.0.2 in project (or later).
- [ ] Run test using `equalDiff`, for example `testInsertItemAfterNextItem`. A stack overflow should occur (or maybe does not if a newer release has fixed the issue again).
- [ ] Investigate what goes wrong in `Difference.swift`.
- [ ] Report issue (or open PR) on the Difference repository.

**Comment by defagos** [comment]
The regression was introduced in this [PR](https://github.com/krzysztofzablocki/Difference/pull/32).

**Comment by defagos** [comment]
If we comment out `Player.elementsQueueUpdatePublisher()` implementation, replacing it with an `Empty` publisher, the crash disappears.

What is strange is that the crash is related to the `PlayerItem` (it also occurs if comparing items only without any player involved). I don't understand what happens yet but this might be a clue for a relevant failing unit test to write for Difference.

**Comment by defagos** [comment]
Investigating further I tried to restore one of the exit conditions, but not based on `displayType` availability, rather on child `label` availability:

```swift
var resultLines = [Line]()
let zipped = zip(expectedMirror.children, receivedMirror.children)
zipped.enumerated().forEach { (index, zippedValues) in
    let lhs = zippedValues.0
    let rhs = zippedValues.1
    let childName = "\(expectedMirror.displayStyleDescriptor(index: index))\(lhs.label ?? ""):"

    if lhs.label != nil {
        let results = diffLines(lhs.value, rhs.value, level: level + 1)

        if !results.isEmpty {
            let line = Line(contents: childName,
                indentationLevel: level,
                canBeOrdered: true,
                children: results
            )
            resultLines.append(line)
        }
    }
    else {
        print("--> nil for \(lhs)")
    }
}
```

We can observe that the recursion does not occur anymore and that some children (UUIDs in our case) end up in the `else` branch.

**Comment by defagos** [comment]
I investigated alternatives: Swift Testing, [MirrorDiffKit](https://github.com/Kuniwak/MirrorDiffKit) and [CustomDump](https://github.com/pointfreeco/swift-custom-dump).

SwiftTesting and MirrorDiffKit suffer from the same loop issue as Difference (recursive call leading to the stack max depth being reached). I guess this is likely related to introspection but this requires further investigations.

CustomDump works better but the display is still not that much readable IMHO. I attached an `archive/difference-replacement` branch but we won't merge it for the moment. We namely decided to stick with the Difference version we use. If we later encounter issues (e.g. compilation) we will simply remove the dependency altogether. I attached an `archive/difference-removal` branch showing how easy this is.
