### ISSUE TITLE
Fix Fastlane xcversion warning

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#245]
**As a developer** I want to be able to update to the latest Fastlane version when needed.

# Acceptance criteria

- Existing Fastlane deprecation warnings have been fixed.
- In particular `This action (xcversion) is deprecated` has been fixed.

# Tasks

- [x] Update Fastlane to the latest version.
- [x] Follow the [xcversion migration guide](https://github.com/xcpretty/xcode-install/blob/master/MIGRATION.md) to fix the corresponding warning.
- [x] Address other issues.
- [x] Update CI documentation (xcodes as required tool).

**Comment by defagos** [comment]
Floating version numbers are not supported by `xcodes` anymore.

Wr also discussed:

- Whether we could store the version number in a [separate file](https://docs.fastlane.tools/actions/xcodes/). For the moment we won't and we will adjust this later if needed.
- Whether we should install the specified Xcode version if missing. For the moment we won't (to avoid polluting the CI agents without noticing).
