### ISSUE TITLE
Add TikTok-like examples to the demo showcase

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#246]
**As a developer** I want to validate our implementation in modern scenarios like TikTok feeds.

# Acceptance criteria

- TitTok-inspired examples are provided in the demo.

# Tasks

- [ ] Investigate single player strategy with a single item loaded at any time, the player playing the content most likely being seen by the user. Add corresponding showcase entry if this makes sense.
- [ ] Investigate multiple player strategy with a single player per cell. Add corresponding showcase entry if this makes sense.
- [ ] Investigate single player strategy with a playlist to manage all loaded items. A limited number of items should be displayed until #178 has been addressed. Add corresponding showcase entry if this makes sense.
- [ ] Investigate player pool strategy where a player pool manages simultaneous playback of several items on screen, at the same time. Add corresponding showcase entry if this makes sense.

**Comment by defagos** [comment]
With improvements to playlist support (see #178) we can now simply load all content in a list and simply switch the index as a way to implement experiences described in this issue.
