### ISSUE TITLE
Add seek to default position support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#247]
**As a developer using Pillarbox** I want to be able to return to the default stream position with the player API.

# Acceptance criteria

- An API has been added to return to the default position (0 for an on-demand stream, live for a DVR stream, no-op for a livestream without DVR).
- This API replaces (extends) the existing skip to live API in the case of DVR streams.
- Tapping the current item in the playlist demo returns to its default position.
- The live button works in the same way for DVR streams in the demo and only appears for such streams.

# Tasks

- [x] A `canSeekToDefault` API is added (alternative signatures can be discussed). We should start from the existing `canSkipToLive` API.
- [x] A `seekToDefault` API is added (alternative signatures can be discussed). We should start from the existing `skipToLive` API.
- [x] Tapping the current item in the playlist demo returns to its default position.

# Hint

Playlist demo code:

```swift
@Published var currentMedia: Media? {
    didSet {
        guard let currentMedia, let index = items.keys.firstIndex(of: currentMedia) else { return }
        if player.currentIndex != index {
            try? player.setCurrentIndex(index)
        }
        else {
            player.seekToDefault()
        }
    }
}
```

**Comment by defagos** [comment]
As discussed with @waliid  the name `skipToDefault` was chosen since it conveys more meaning that simply `seekToDefault`. Skipping might namely be limited in some cases (e.g. near the live edge of a DVR stream) while seeking should always be possible within the stream.
