### ISSUE TITLE
Skipping several times fast leads to erratic behavior

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#256]
**As a user** I want correct skip behavior in all cases. This is currently not the case when tapping seeks several times in a row when reaching the stream end.

# Acceptance criteria

- The issue described above is fixed.

# Tasks

- [x] Reproduce the issue with a unit test.
- [x] Fix the issue.
- [x] Check network / memory and lanes.
