### ISSUE TITLE
Basic playback of a Swissinfo content in the demo app

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#28]
As a user I can play a Swissinfo content in the demo application with a minimalist user interface.

# Acceptance criteria

- The player plays the [following content](https://play.swissinfo.ch/play/tv/society/video/switzerland-says-sorry?urn=urn:swi:video:47459404).
- The demo application displays the video to the user.
- Playback starts without user intervention.
- The user can pause / resume playback with a button.
- The user can seek anywhere in the video with a slider.

# Tasks

- [x] Add basic queue player with basic playback API.
- [x] Add raw video layer view.
- [x] Add demo entry to play the SWI content.
- [x] Implement player states (to be determined).
- [x] Implement playback time observers.
- [x] Introduce test streams and document setup.

iOS only (tvOS is unspecified as we will use the native player UI anyway):

- [x] Display play / pause button in basic player layout.
- [x] Display slider.

**Comment by defagos** [comment]
For unit testing we cannot simply embed `m3u8` playlists since `AVPlayer` [refuses to play local](https://developer.apple.com/forums/thread/69357) playlists (they work fine with VLC, though).

But maybe there is still a way to serve files locally with `AVAssetDownloadURLSession ` or by storing them separately in a tiny web server.

**Comment by defagos** [comment]
Documentation for custom publishers:

- [Apple documentation](https://developer.apple.com/documentation/combine/processing-published-elements-with-subscribers).
- [Fantastic article series](https://jozsef-vesza.dev/tags/combine) which will also be very helpful to write a custom `BoundaryTimePublisher`.
- [... and its companion implementation](https://github.com/jozsef-vesza/AVFoundation-Combine/blob/master/Sources/AVFoundationCombine/Publishers/PlayheadProgressPublisher.swift).
