### ISSUE TITLE
Analytics tracker PoC

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#292]
**As a company** we need to be able to measure success for our products, both for internal needs as well as for legal reasons, using official trackers (comScore and TagCommander). 

**As an app developer** I also want to be able to measure success in ways that are specific to my product, using my own trackers.

# Acceptance criteria

- A way to define official and custom trackers is provided.
- Trackers can be registered with a player to measure consumption.
- Standard SRG tracking is performed for URN-based content.
- Trackers only print some basic events.
- Existing media composition labels are printed in the process by the correct tracker (comScore vs. Tag Commander).
- An API proposal is made and documented.

# Tasks

- [x] Add `Tracker` protocol.
- [x] Store trackers with played items.
- [x] Implement dummy SRG tracker, always used for URN-based content.
- [x] A way to provide metadata is introduced.
- [x] Update APIs to support optional trackers.
- [x] Document learnings.

**Comment by waliid** [comment]
# Player analytics class diagram

Here is a very light class diagram that doesn't represent at 100% the API provided by @SRGSSR/pillarbox but allows us to show the analytics part related to this proof of concept.

```mermaid
classDiagram

class Player {
    - storedItems: [PlayerItem]
    - currentItemTracker: ItemTracker?
}

class PlayerItem {
    - source: Source
    - trackers: [Tracker]
    + init(trackers: [Tracker] = [])
}

class ItemTracker {
    - item: PlayerItem
    - player: Player
    + init(item: PlayerItem, player: Player)
    + update(with metadata: Metadata)
    + detach()
}

class Asset {
    - metadata: Metadata?
}

class Source {
    - asset: Asset
}

class Metadata {
    - title: String?
    - subtitle: String?
    - description: String?
    - image: UIImage?
}

class Tracker {
    + attach(to player: Player)
    + update(with metadata: Metadata)
    + detach()
}

Player "1" --> "0..1" ItemTracker : uses
ItemTracker --> "1" PlayerItem : uses
Player "*" --> "*" PlayerItem : owns
PlayerItem --> "1" Source : has
PlayerItem "0..*" -- "0..*" Tracker : contains
Source --> "1" Asset : has
Asset "1" -- "0..1" Metadata : has

<<protocol>> Metadata
<<protocol>> Tracker

Tracker <|-- MappTracker
Tracker <|-- NpawTracker
Metadata <|-- MediaMetadata
Metadata <|-- SimpleMetadata

```

(Unfortunately, I wasn't able to draw `Player` & `CoreBusiness` packages)
