### ISSUE TITLE
Add generic tracker support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#299]
**As a developer** I need to be able to add standard trackers like comScore, TagCommander / Mapp or diagnostics support in a standard way. **As a developer integrating Pillarbox** I want to be able to use the same mechanism to integrate my own custom trackers.

# Acceptance criteria

- A tracker contract is available to implement any kind of tracker.
- Tests ensure the behavior is clearly defined.

# Tasks

- [x] Add `PlayerItemTracker` protocol with dedicated lifecycle.
- [x] Implement lifecycle with unit tests.
- [x] Retrieve miscellaneous minor code improvements made on the PoC branch.
- [x] Check that metadata updates work (no playback interruption, correct now info, several tracker update calls).
