### ISSUE TITLE
Tracker activation flag

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#300]
**As a developer integrating Pillarbox** I need to be able to enable or disable some trackers when not needed (e.g. in a multi-instance context).

# Acceptance criteria

- A tracker can be disabled or enabled when needed.

# Tasks

- [x] ~Maybe send metadata update **just before** the tracker is enabled. If an event must be immediately sent when the tracker is enabled we namely need the metadata to be available. Update UTs accordingly if this makes sense.~ 
Replaced by #328 
- [x] Each `Player` instance provides a way to enable or disable analytics for associated trackers.
- [x] Update tracker lifecycle methods if needed.
- [x] ~Implement an example of a tracker which is never disabled (e.g. diagnostics for QoS).~ 
- [x] Add a global demo setting to enable or disable all tracking.
- [X] ~Align API naming scheme between platforms where appropriate.~
Replaced by https://github.com/SRGSSR/pillarbox-documentation/issues/23
