### ISSUE TITLE
Make behavior consistent at the end of a playback

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#306]
**As a user** I want to have a consistent end of playback user experience, not only when playing a single item but also when having exhausted a playlist.

# Acceptance criteria

- When finishing playback of an item or a playlist the control center is empty.
- The demo player provides a good user experience, e.g. a way to restart playback at the beginning.

# Remark

Following our analytics tracker PoC (see #292) this issue is required so that trackers are detached at the proper time at the end of playback. This is why this issue must be implemented before #299.

# Hints

- We will keep the `.ended` state (related to the `AVPlayerItemDidPlayToEndTime` notification being received).

# Tasks

- [x] Update current item publisher (or related publishers / code) to avoid persisting the last item.
- [x] Check that failed items still behave correctly (e.g. playlist navigation to / from a failed item is possible).
- [x] Document item publisher behavior.
- [x] Add associated unit tests.
- [x] Update the main demo player to include a restart button (restart at the current item beginning for a single item, restart with the first item in a playlist).
- [x] Check sentinels.

**Comment by defagos** [comment]
Fixing the issue required two changes:

1. We updated how `QueuePlayer.replaceItems(with:)` works to avoid unnecessarily publishing `currentItem` changes to `nil`.
2. We introduced a publisher which can better tell what happens when the current item becomes `nil`. This can namely happen when a failure is encountered or when the playlist is exhausted, and knowing the reason is key to implement proper behavior at item end, as well as with failing items.
3. We combine this item change information with the position of the item in the list. Only if a failed item is at the end we should clear the current index, otherwise rely on what we know about the change to update the current index appropriately.

The following table lists the various possible cases for our new item change publisher:

| Previous item | Current item | Description | Publisher output (`ItemResult`) |
|:--:|:--:|:--:|:--:|
| A | B | A ended successfully and transitioned to a playable B | `.success(B)` |
| A + `ItemState(for: A) == .failed` | `nil` | A failed | `.failed(A)` |
| A + `ItemState(for: A) != .failed` | `nil` | A finished and was the last item | `.success(nil)` | 

When the publisher output is `.failed` we can then check whether the corresponding item is the last one and update the current index appropriately.

**Comment by defagos** [comment]
Sentinels still do work the same. Some issues might still remain but they are identical to those still present after #191 has been implemented.
