### ISSUE TITLE
Implement streaming analytics testing tools

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#310]
**As Mediapulse or member of the GD analytics team** I want to be sure that measurements stay reliable during the lifetime of mobile products. **As a Pillarbox developer** I want to be confident that no matter the change (code, OS update, etc.) I can reliably and efficiently check that analytics specifications are correctly fulfilled.

# Acceptance criteria

- Convenient test helpers are available to implement targeted integration test scenarios with comScore and Commanders Act.

# Tasks

- [x] Intercept comScore requests.
- [x] Intercept Commanders Act requests.
- [x] Provide comScore test helpers.
- [x] Provide Commanders Act test helpers.
- [x] Write comScore tests for initial play, pause and pause during playback.
- [x] Write similar Commanders Act tests (not all since a more complex state machine implementation is required here).

**Comment by defagos** [comment]
An idea to test several keys at the same time:

```
public func expectEqual(
        values: [String],
        for key1: Key, _key2: Key
        during interval: DispatchTimeInterval = .seconds(20),
        file: StaticString = #file,
        line: UInt = #line,
        function: String = #function,
        while executing: ((AnalyticsTest) -> Void)? = nil
    ) {

    }
```

with `Key` created from a key with an attached transformation, e.g. `.int("field")`, `.date("field")`, etc. Keys which must be tested as strings could simply be instantiated with the `"field"` directly if `Key` conforms to `ExpressibleByStringLiteral`.
