### ISSUE TITLE
Commanders Act stream tracking

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#311]
**As SRG SSR GD analyst** I want correct playback measurement for apps using Pillarbox.

# Acceptance criteria

- The Commanders Act SDK is integrated according to the specifications.

# Tasks

- [x] Write tests for:
  - [x] Play at start.
  - [x] Pause at start.
  - [x] Pause during playback.
  - [x] Playback end.
  - [x] Destroy player during playback.
  - [x] Destroy player after having played the entire content.
  - [x] Seek while playing / paused.
  - [x] Failure at playback start. 
  - [x] Failure during playback.
  - [x] Playback duration:
      - [x] Test with normal playback.
      - [x] Test with seek.
      - [x] Test with item transition.
      - [x] Test with livestream.
      - [x] Test with DVR stream.
  - [x] Behavior for livestreams: 
      - [x] No offset from live edge.
      - [x] Position set to the playback duration.
      - [x] ~Test that values are correct on stop.~
  - [x] Values for DVR streams:
      - [x] Offset from live edge (need to increase when the player is stuck buffering).
      - [x] Position set to the playback duration.
      - [x] Test that values are correct on stop.
      - [x] Test that values are correct if we close the player while stuck buffering.
  - [x] Buffer start / buffer stop (we need to stop advancing time when the player is stuck buffering).
  - [x] ~Metadata (and no tracking if no metadata).~ _Was not a requirement before (unlike for Mediapulse)_
  - [x] Enable / disable tracking on the fly.
  - [x] Metadata update.
  - [x] Bandwidth.
  - [x] Playback rate.
  - [x] Volume.
  - [x] ~Subtitles.~
  - [x] ~Audio tracks.~
  - [x] Heartbeats (on-demand / live / DVR) implemented with periodic time publishers.
- [x] Integrate Commanders Act SDK version 5.
- [x] Create test helpers to test sent data if needed.
- [x] Implement the corresponding tracker.
- [x] Provide media player name and version in streaming events.
- [x] ~Create manual testing documentation procedure, bundled with the project, for cases which need to be tested manually.~ _Could be tested automatically_
- [x] Check memory and network profiles.

**Comment by defagos** [comment]
The _failure during playback_ scenario is difficult to test automatically. Here is how it can be manually verified:

1. Enable `TCDebug` event logging.
2. Build and run the demo application.
3. Play some video.
4. Disable the network and seek to an unbuffered location.
5. Wait ~2 minutes until playback fails and check the Commanders Act event log.

**Comment by defagos** [comment]
Since we extrapolate some DVR values to lack for player information when disabling the tracker (e.g. if the player is closed during playback) some use case is quite difficult to test automatically as well. Here is how it can be manually verified:

1. Enable `TCDebug` event logging.
2. Build and run the demo application.
3. Play some DVR stream at the live edge.
4. Disable the network and let the player enter buffering.
5. Wait ~30 seconds and close the player. A `stop` event with `media_timeshift` having this duration should be observed in the console.

**Comment by defagos** [comment]
A similar use case for on-demand video:

1. Enable `TCDebug` event logging.
2. Build and run the demo application.
3. Play some on-demand stream.
4. Disable the network and wait until the player starts buffering. Check the playback position.
5. Wait ~30 seconds and close the player. A `stop` event with `media_position` having the playback position at which the player is stuck should be observed in the console.

**Comment by defagos** [comment]
For simplicity we decided not to pause or cancel heartbeats during buffering phases. This is an edge case for which continuing to emit hearbeats is simple and compatible with the current specifications we received.

**Comment by defagos** [comment]
Unlike SRG Analytics we use [`indicatedBitrate`](https://developer.apple.com/documentation/avfoundation/avplayeritemaccesslogevent/1388123-indicatedbitrate) instead of `observedBitRate` to better reflect the variant being played, not the average device bitrate.
