### ISSUE TITLE
SRG SSR hidden and page view tracking support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#312]
**As an app developer integrating Pillarbox** I want to be able to track page views according to the SRG SSR standards. I also want to be able to track various arbitrary events.

# Acceptance criteria

- Manual page view tracking is possible.
- Hidden tracking is possible.

# Tasks

- [x] Implement page view analytics for comScore.
- [x] Implement page view analytics for Commanders Act.
- [x] Implement hidden event analytics for Commanders Act.
- [x] Decide what must happen if an empty page title is provided.
- [x] Discuss if app overlap measurements are still needed and create a story if the answer is yes.

**Comment by defagos** [comment]
App overlap measurements are not needed anymore.
