### ISSUE TITLE
Tracking setup

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#327]
**As a developer integrating Pillarbox** I need to be able to setup tracking for my application (identifier, account, etc.), both for comScore and CommandersAct.

# Acceptance criteria

- comScore setup is possible as it was for Letterbox.
- CommandersAct setup is possible as it was for Letterbox.
- No app overlap measurements are performed but we know if this is still expected.

# Hints

Identifiers do not need to be made private as they can be sniffed easily and are publicly visible on GitHub since years anyway.

# Tasks

- [x] Share developer documentation and repository links.
- [x] Make a tour of what is currently done in SRG Analytics and Letterbox.
- [x] Update libraries to the most recent versions.
- [x] Add main tracker instantiation API.
- [x] Setup test infrastructure.
- [x] Add comScore configuration.
- [x] Add CommandersAct configuration.
- [x] Ask the GD whether app overlap measurements are still required or not. Create a dedicated issue if this is the case.

**Comment by defagos** [comment]
Links to the SDKs:

- [comScore](https://github.com/comScore/Comscore-Swift-Package-Manager)
- [CommandersAct](https://github.com/CommandersAct/iOSV5)

**Comment by defagos** [comment]
An idea for test helpers:
- Add a `ComscoreTestCase` subclass of `TestCase` which setups a test session id.
- Provide Circumspect test helpers on that class that automatically filter events for the session.
Same for CommandersAct.

**Comment by defagos** [comment]
According to @pyby app overlap measurements are not forwarded anymore to Mapp anyway, so it is likely we could remove them.

**Comment by pyby** [comment]
According to the current tag configuration used for SRGAnalytics SDK on Apple and Android, the event named "Installed Apps" is not forwarded to SRG SSR analytics tool.
![Screenshot 2023-04-04 at 10 23 14](https://user-images.githubusercontent.com/380522/229732634-7560763a-3c28-4c33-82be-e057274deabd.jpg)
