### ISSUE TITLE
Automatic page view tracking support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#332]
**As a user** I want to be able to easily implement page view tracking in my application.

# Acceptance criteria

- Automatic view tracking is possible as in Letterbox.
- Page view analytics are correctly collected in the demo.

# Tasks

- [x] Implement view tracking protocol for UIKit (with current automatic opt-out support).
- [x] Support lifecycle events automatically.
- [x] Implement support for containers.
- [x] Setup required infrastructure (swizzles, notifications) when analytics are started.
- [x] Support for scene delegate and app delegate based applications.
- [x] ~Stop automatic children tracking when a parent itself is tracked.~ Current SRG Analytics behavior preserved.
- [x] Add support for automatic propagation through standard UIKit containers:
  - [x] `UINavigationController`.
  - [x] `UIPageViewController`.
  - [x] `UISplitViewController`.
  - [x] `UITabBarController`.
  - [x] ~`UISheetPresentationController` (to be investigated first).~ _No special work required, works out of the box._
- [x] Add SwiftUI API.
- [x] Implement for all demo screens.
- [ ] Polish API naming.
- [x] Test automatic behavior in a tiny project using no scenes.
- [x] Test automatic behavior in a tiny project using multiple scenes.
- [x] Check that the sizing behavior of a tracked view is preserved.
