### ISSUE TITLE
Set demo application version number automatically

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#336]
**As a demo app user** I want to know which version of the application I am running.

# Acceptance criteria

- The demo version is automatically filled based on git history.
- No manual update operation is required.

# Hints

The version number can be found with:

```shell
git describe --tags
```

We can extract the version number only with:

```shell
git describe --tags --abbrev=0
```

or the version number and the number of commits since the tag with:

```shell
git describe --tags | cut -d "-" -f 1,2
```

We can likely use PlistBuddy to insert the version. The app version must likely remain stuck at the previous tag if we want a fully automated process, but full version information could be displayed in the app settings.

# Tasks

- [x] ~Set version number in application metadata.~
- [x] ~Check that the app can be delivered correctly.~
- [x] ~Display full version information in app settings.~

**Comment by defagos** [comment]
Naive options here:

- Disable automatic Info.plist generation and edit file with PlistBuddy (but generation is recommended).
- Generate `.xcconfig` file from commit information to have it pulled into Xcode settings and thus into the generated Info.plist (likely better if possible).

**Comment by defagos** [comment]
I prepared a branch but I am not sure this is a good idea. We would need to manage new versions on App Store Connect, slowing our releases down.

It is probably better to deliver the demo always in 1.0.0, both for nightlies and releases. Maybe we should adjust the icon badge to reflect the library version, or maybe remove the badge entirely.

Better discuss our options with @pyby.

**Comment by defagos** [comment]
I gave it another though and think it is best to just display the library version as badge, while keeping the demo in 1.0 all the time.

I opened a dedicated PR, we can discuss it among iOS developers to decide if this makes sense.
