### ISSUE TITLE
Avoid ghost starts

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#339]
**As Mediapulse** I want ghost starts to be avoided.

# Acceptance criteria

- Ghost starts are properly avoided.

# Tasks

- [x] Restore logic to avoid page views in the background.
- [x] Implement unchecked API (as in SRG Analytics) if really needed.
- [x] Update automatic view tracking to account for these API changes (`ignoreApplicationState` in previous SRG Analytics implementation).
