### ISSUE TITLE
comScore stream tracking

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#344]
**As Mediapulse** I want correct playback measurement for apps using Pillarbox.

# Acceptance criteria

- comScore stream tracking is integrated according to the specifications.

# Hints

Here are a few facts about our previous SRG Analytics implementation:

- Events that were implemented: play, pause, end, seekStart, bufferStart.
- `onUxActive` and `onUxInactive` were called since our player can support background playback.
- When notifying an event to comScore we were updating the current player position:
  - `startFromPosition` for on-demand streams.
  - `setDVRWindowLength` and `startFromDvrWindowOffset` for DVR streams.
- We were creating a new streaming analytics session when restarting playback of an item.

# Tasks

- [x] Write tests for:
  - [x] Play at start.
  - [x] Pause at start.
  - [x] Pause during playback.
  - [x] Playback end.
  - [x] Destroy player during playback.
  - [x] Seek while playing / paused.
  - [x] ~Restart.~
  - [x] Failure. 
  - [x] DVR offset for on-demand / live / DVR streams.
  - [x] Buffer start / buffer stop.
  - [x] Metadata (and no tracking if no metadata).
  - [x] Enable / disable tracking on the fly.
  - [x] ~Metadata update.~
- [x] Implement the tracker.
- [x] Deliver no IL merged analytics metadata when the chapter has none (most notably for audio content).
- [x] Check behavior:
  - Play some content in a playlist.
  - Delete the current item.
  - Resume playback with the item to which playback has transitioned. The new item should be tracked but currently isn't.
- [x] Check other possible item transitions in a playlist, write test and fix issues found
- [x] Check network and memory profiles.

**Comment by defagos** [comment]
Player deinit is a bit tricky to test:

- We need to wait 5 seconds at least before destroying the player. `SCORStreamingAnalytics` namely waits ~5 seconds before sending events so if it is destroyed earlier we won't receive any events.
- The `end` event is automatically emitted by `SCORStreamingAnalytics` when destroyed but since we don't provide any labels we cannot set a listener identifier to collect notifications. The `SCORStreamingAnalytics` reuses prior labels, though, so we can still provide a session identifier by calling `play()` within the same listening block, so that a listener identifier is correctly assigned first.

**Comment by defagos** [comment]
We cannot use metadata updates on `SCORStreamingAnalytics ` to supply update the listener identifier (see #345) as this emits an additional undesired `end` event, probably because the internal comScore state machine decides that a new media is being played in such cases.

Instead we can access its `SCORStreamingConfiguration` and tweak associated labels so that no metadata update is detected.

**Comment by defagos** [comment]
Non-relevant tests after closer inspection:

- Restart: Unlike SRG Letterbox we use `AVQueuePlayer` with `.continue` as `actionAtItemEnd`. Thus restarting means a new tracker, thus a new session.
- Metadata update: As discussed above we cannot update metadata during playback as this would generate unnecessary `end` events.

**Comment by defagos** [comment]
The network activity with seeks and buffering is good. Even with smooth scrubbing events are inhibited during user interaction, avoiding too many unnecessary `pause` / `play` transitions.

**Comment by defagos** [comment]
It is especially important to run each comScore test in isolation for the reasons mentioned above. When run as part of a test suite a test might namely work, while it might not when run individually. If a test runs fine individually, though, it will run fine as part of a test suite.

Moreover comScore does not send events when no network connection is available. Though we are playing offline test streams a network connection is therefore sadly required for our comScore integration tests to pass.
