### ISSUE TITLE
Improve behavior with non-started analytics

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#350]
**As a developer integrating Pillarbox** I want minimal work to be performed if analytics have not been started.

# Acceptance criteria

- Analytics calls are cancelled early when tracking has not been enabled.

# Hints

It is difficult not to start analytics in a test suite (because `Analytics` is a singleton), so it is likely not easy to test this behavior.

# Tasks

- [x] Test in the demo with / without analytics started.
- [x] ~Add `isStarted` computed property on `Analytics`, returning `true` iff the singleton has been started.~
- [x] ~Use the `isStarted` flag to inhibit events early.~
- [x] ~Use the `isStarted` flag to inhibit page views early.~
- [x] ~Use the `isStarted` flag to inhibit streaming events early.~
- [x] Check that a non-tracked app works well (no dedicated activity, no crashes).
