### ISSUE TITLE
Document analytics integration

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#355]
**As a developer integrating Pillarbox** I need documentation about analytics integration.

# Acceptance criteria

- Analytics setup is documented.
- Page view tracking is documented.
- Event tracking is documented.
- Stream tracking is documented.

# Tasks

- [ ] Document analytics setup.
- [ ] Document page view tracking.
- [ ] Document event tracking.
- [ ] Document stream tracking.
- [ ] Page view integration for CarPlay is documented.
- [ ] Split view page view measurements is documented.
- [ ] Document < 50% visibility rule for comScore (see #447 for use cases).

# Hints

See https://github.com/SRGSSR/pillarbox-documentation/issues/25.

**Comment by defagos** [comment]
Most of the documentation is already available. Two exceptions:

- We currently have no CarPlay helpers available but a draft issue exists. Documenting analytics integration will surely be part of the work we would do to better assist CarPlay integration.
- The Mediapulse specification document for player visibility (and the associated decision tree to actually decide whether a player must be tracked) is nowhere to be found on the documentation website anymore. Not sure the rule has disappeared but it its probably better to keep documentation simple and to address specific integrations on a case-by-case basis.
