### ISSUE TITLE
Basic livestream playback

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#36]
As a user I want to play all type of unprotected audio & video livestreams provided by SRG SSR.

# Acceptance criteria

- Demo available to play audio and video livestreams.
- Display Play / Pause buttons.
- Protected content (DRM / Token) not included.
- No timestamp management.

# Tasks

- [ ] Find if local delivery with Python is possible for UTs.
- [ ] Correctly identify livestreams (short enough time range).
- [ ] Update demo to add livestream examples (video / audio).
- [ ] Hide progress bar.

**Comment by defagos** [comment]
Useful [ffmpeg streaming documentation](https://trac.ffmpeg.org/wiki/StreamingGuide) which might offer a way to stream a local file (in a loop) as a livestream (or DVR livestream) locally.
