### ISSUE TITLE
Muted playback support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#362]
**As a developer integrating Pillarbox** I need a way to mute a player, especially if my experience involves autoplay or simultaneous playback of several streams.

# Acceptance criteria

- An API is provided to mute the player.

# Tasks

- [x] Add property to mute the player.
- [x] Make the player publish changes to the muted property.
- [x] Adjust `media_volume` analytics property.
- [x] Add mute button to the custom player layout.
