### ISSUE TITLE
Add API support for changing playback speed

### ISSUE THREAD

**Issue by waliid** [SRGSSR/pillarbox-apple#367]
**As a developer**, I want to be able to change the playback speed via an API.

# Acceptance criteria

- The API should provide a method/property to set the playback speed of the player.
- The playback speed can be adjusted to any valid value (from 0 to 2).
- The player should accurately reflect the updated playback speed.
- The API should handle errors and edge cases gracefully, such as invalid playback speed values.
- The playback speed shouldn't be automatically updated between elements of a playlist.
- The mechanism is compatible with the system player UI.

# Tasks

- [x] Create a public method/property in the player class for changing the playback speed.
- [x] Implement the logic to set the playback speed based on the provided value.
- [x] Test the API with various playback speed values to ensure it behaves as expected.
- [x] Handle any potential errors or edge cases that may arise when changing the playback speed.
- [x] Check that changing the playback speed with the system UI works.
- [x] Ensure that setting a playback speed when the player is paused does not resume playback.
- [x] Test behavior when using AirPlay.
- [x] Document known issue when chaining on-demand to livestream without DVR in playlists when the speed is > 1 (CoreMediaError Domain error -12785). Maybe a stream packaging issue but report to Apple if not the case. No issue if the livestream has been played first it seems and no issue with local test streams.

**Comment by defagos** [comment]
# API design

As discussed today with @waliid and then the team, we will make playback speed support much simpler than in Letterbox:

- `setPlaybackSpeed(_:)` sets the **desired** playback speed but this speed is not guaranteed to be applied (see rules below).
- No supported speed list will be hardcoded in the player. All speeds in `0<..2` will be supported. We might still need to discuss if a higher lower bound than 0 should be required, though.
- The effective allowed playback speed is applied as follows:
   - For on-demand time ranges the desired speed is always set on the `queuePlayer`.
   - For empty time ranges the speed is forced to 1.
   - For DVR time ranges the speed is set on the `queuePlayer` except in the vicinity of the time range end, i.e. from the live edge (threshold to be discussed).
- To account for changes required as the DVR live edge is reached we can use a boundary time observer. Since boundary time publishers only fire during normal playback and not during seeks, though, we need to use our `seekTimePublisher` as well. If it delivers a seek target time we need to consider this time to calculate the difference between this time and the time range end, otherwise we simply return the boundary time publisher which will act as signal to determine when the time range edge is reached. When any of these signals is received we force the `queuePlayer` rate to 1.

The result is that the desired playback speed is applied when possible, but if for some reason it changes we never switch it back to the previously desired value, unlike what we did with Letterbox. This way the speed experienced by the user is uninterrupted, for example:

- Within the same stream: If the user plays a DVR stream in the past at 2x, then reaches the live edge, the speed changes to 1x. If the user plays for a while and later seeks in the past, we will keep the speed at 1x (not restoring it at 2x unlike Letterbox), so that the  experience stays uninterrupted.
- In playlists: If the user plays an on-demand stream at 2x, then transitions to a live stream (forced at 1x), then transitions to an on-demand stream, the 1x speed is kept for the last on-demand stream as well.

In all cases the user can at any time pick up their device and adjust the speed back to its prior value if desired, but surprising speed changes are never experienced.

**Comment by defagos** [comment]
Transitions between playlist items involving a livestream might be unreliable at 2x speed. If playing an on-demand stream, followed by a livestream, the livestream might namely be skipped when playing at 2x, even during normal transitions between items.

This is likely due to an `AVQueuePlayer` issue which makes the livestream keep the 2x speed, even if we reset it to 1 as early as possible (when the previous item ends is even not sufficient). This leads the livestream to end abruptly, making playback continue to the next item (or end if there is no item afterwards).

There does not seem to be any mitigation so we should likely document this behavior as known issue while reporting it to Apple.

**Comment by defagos** [comment]
We need an implementation that fits our reactive approach:

- At any time we need to be able to store a speed and a range in which the playback speed can be picked. The speed might not be contained within the range, e.g. during the initialization phase where the only allowed range is `1...1` but a higher or lower speed might be desired. The speed and range are collected as a `PlaybackState` type whose mutation can be published, providing the reactive behavior we need. To ensure we only derive applicable rates the `PlaybackSpeed` must provide a `rate` property delivering the speed clamped to the valid range.
- To ensure state consistency we need a single state reduction pipeline. State reduction is obtained by applying updates, which occur:
   - Either when the user desires a different speed. This can be achieved with a speed setter which internally publishes its result to the reduction pipeline with a `PassthroughSubject`. Since setting a speed might not work (e.g. if the speed cannot be applied) the desired value must not be stored, which is why a stateless passthrough subject must be used.
   - Or the speed range is deduced from what is being played. Components to guess what speed range is allowed include the media time range, its item duration (from which a stream type is determined), as well as the current position (since speed is limited to 1 near the live edge of a DVR stream, whereas 2 is allowed away from the live edge).
- Updates can be modeled with a `PlaybackSpeedUpdate` enum. The state reduction inspects the speed to update and creates another speed as a result of the applied update. Update streams are simply combined with a merge publisher so that all changes are processed consistently in sequence. The end result is stored in an internal `_playbackSpeed` player published property.

The above never alters the `AVPlayer` rate. We therefore need:

- A second pipeline starting from `$_playbackSpeed` which updates the player rate in the sink.
- To support updates to the player rate as done when using `AVPlayerViewController` (which does not know about Pillarbox), we need a pipeline starting from a rate publisher. To avoid triggering too many update loops we can only process such updates when `AVPlayerViewController` is used, which can be determined by looking at the call stack.
