### ISSUE TITLE
Update analytics based on the current playback speed

### ISSUE THREAD

**Issue by waliid** [SRGSSR/pillarbox-apple#369]
**As a developer**, I want to update the analytics tracking to include the current playback speed.

# Acceptance criteria

- The streaming analytics events should include the current playback speed value.
- The analytics updates should be tested to ensure the playback speed values in the streaming events.

# Tasks

- [x] Update the analytics tracking code to include the playback speed.
- [x] Update Commanders Act tracker extrapolation to take into account speed (playing N seconds at speed 2 moves the playhead virtually from 2*N in `stop` position calculations).
- [x] ~Test the analytics tracking to verify that the playback speed is accurately captured.~
