### ISSUE TITLE
Basic DVR livestream playback

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#37]
As a user I want to play all type of unprotected audio & video DVR livestreams provided by SRG SSR. 

# Acceptance criteria

- Demo available to play audio and video DVR livestreams.
- Display Play / Pause buttons.
- Protected content (DRM / Token) not included.
- No timestamp management.

# Tasks

- [x] Find if local delivery with Python is possible for UTs.
- [x] Correctly identify livestreams (large enough time range, moving).
- [x] Create basic player configuration (defaut configuration with builder to tweak settings like DVR window e.g.).
- [x] Update demo to add livestream examples (video / audio).
- [x] Bind progress value to progress bar.
- [x] Have correct progress information reported.

**Comment by defagos** [comment]
I split unit tests to have a single class per file. Xcode automatically can display a test file associated with another one (it matches its name with a `Tests` prefix) but navigation is buggy (clicking somewhere in the main file makes the assistant randomly jump). Moreover swiftlint is a bit obscure about the expected ordering when multiple test classes are located in a single file..
