### ISSUE TITLE
Even smoother scrubbing / trick mode

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#383]
**As a user** I want the best possible seek experience wherever possible. Fact: If I use the system UI vs. the Pillarbox UI for some contents, the seek experience is much faster with the system UI.

Some examples:

- DRM protected contents at SRG SSR.
- SWI examples.

# Acceptance criteria

- The seek experience obtained with the custom player and its progress bar is on par with the system UI experience.

# Hints

- When using `AVPlayer` with a rate > 2 we can observe that I-frames are used. A naive implementation where we set the rate to 3 when starting seeking and reset it at the end shows improvements.
- Doing so in all cases seems to lead to poorer results with other contents so we need to be careful here. We can likely [find](https://stackoverflow.com/questions/36611178/why-avplayeritems-canplayfastforward-method-returns-false) when trick mode can be applied with `canPlayFastForward` and similar methods.
- We should study what `AVPlayerViewController` does to find further hints.
- The [HLS book](https://hlsbook.net) has more information about trick mode.

# Further analysis

Apple default UI has a very good forward / backward scrubbing experience. Checking network activity with the HEVC example shows they rely on i-frames when scrubbing. How can we achieve the same (is there an official way, e.g with an API or by adjusting the playback rate? Or are they using images displayed on the video layer?)

Interesting video: https://developer.apple.com/videos/play/wwdc2022/110379/

Maybe setting speed or tolerances might help: https://developer.apple.com/forums/thread/72815. Yes, it seems that rates > 2 request i-frames (as seen with Charles).

Also see: https://stackoverflow.com/questions/30346405/how-do-you-get-smooth-high-rate-playback-from-avplayer

Maybe see https://developer.apple.com/library/archive/technotes/tn2404/_index.html. `AVSampleCursor` seems used in AVKit implementation, as revealed by having a look at the binary. Maybe see https://gist.github.com/shaps80/ac16b906938ad256e1f47b52b4809512

![Image](https://user-images.githubusercontent.com/170201/226130060-171ebc3b-a57d-49b7-aa14-7b7a720b1cd9.jpg)

# Tasks

- [x] Investigate how trick mode has been implemented by Apple.
- [x] Implement trick mode in Pillarbox.
- [x] Improve scrubbing experience in all other possible cases (e.g. stepping) by tweaking tolerances.
- [x] ~Avoid issues when seeking to the end by avoiding tolerances out of the content time range.~
- [x] Check analytics (seeking probably should occur before the player is paused for efficient seeking).

**Comment by defagos** [comment]
We should better understand how Apple implemented trick play:

- Which rate is set during seeks.
- Which positions are reached.
- Which tolerances are applied.

This can likely be achieved with an instrumented `AVPlayer` subclassed used with `AVPlayerViewController` or `VideoView`.

**Comment by defagos** [comment]
Our _The Dig_ MP4 example can be finely navigated as follows:

- Set `rate` to 0 during seeks.
- Do **precise** seeks, not approximate ones.

So it is likely that to get a great behavior on all kinds of contents we have to tweak how seeks are made, maybe based on item capabilities.

**Comment by defagos** [comment]
It seems that I-frames are used for our _Switzerland says sorry!_ example if we set the rate to zero, tolerance before to zero and tolerance after to a non-zero value (maybe infinite is not the best option).

**Comment by defagos** [comment]
In all cases smooth seeking is a pre-requisite. We cannot have great behavior if seeks are cancelled and this is also how Apple implementation works (all seeks succeed during seeking).

**Comment by defagos** [comment]
The player fails with an error when seeking near / to the end of our _Switzerland says sorry!" example with an after (or before) tolerance, but this is also the case with Apple system player. So I guess there is either an issue with the stream or with `AVPlayer` itself.

The issue affects iOS 16 and 17 in the same way so this is not something new. Won't do anything yet, other contents seem to work fine.
