### ISSUE TITLE
Improved seek user experience

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#41]
**As a user** I want to have a good seeking user experience. **As an integrator** I want to have a simple way to connect a player to a standard system slider.

# Acceptance criteria

- Seek works fine without hiccups or issues.
- Integration in an app is simple.

# Tasks

- [x] Improve the progress reporting API.
- [x] Avoid seek bar hiccups while grabbing the slider and moving slowly.
- [x] Ensure correct behavior when loading with slow connection.
- [x] Ensure the slider is not seekable if there is no time range ~(and located at 1)~.
- [x] Update the demo.
