### ISSUE TITLE
Boundary time and asset property state publishers

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#42]
**As a developer** I need a complete toolbox to implement player internals in a reactive manner. **As an integrator** I need to have standard player APIs for accessing internals in a safe way.

# Acceptance criteria

- Boundary time observation is provided.
- Safe reactive access to asset properties is provided.

# Tasks

- [x] Investigate if signposts can be implemented to visualize player updates in Instruments (maybe a simple `handleEvents` suffices).
- [x] ~Cleanup playback property publisher when seeking (write tests first).~
- [x] Add boundary time publisher (similar to the existing periodic time publisher).
- [x] Implement asset property publisher with the modern iOS 15 async API.
- [x] Provide generic asset property publisher variants matching the iOS 15 async API ones.

**Comment by defagos** [comment]
I integrated [Timelane](https://timelane.tools) to be able to visualize player activity.

**Comment by defagos** [comment]
Rather than throttling playback property publisher updates when seeking, I removed target seek information since it is not really needed anymore after #41. I could therefore remove properties and only keep internal player `Pulse` information.
