### ISSUE TITLE
Add privacy manifest

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#422]
**As a developer integrating Pillarbox** I would like to have my app automatically reflect what is being collected in Pillarbox analytics.

# Acceptance criteria

- A privacy manifest (iOS 17) is provided by Pillarbox.

# Tasks

- [x] Check whether Instruments displays SDK calls in [Points of Interest](https://developer.apple.com/wwdc23/10060) tool.
- [x] Add privacy manifest.
- [x] Check that app privacy automatically merges this privacy manifest when deriving its own.
- [x] Ask 3rd party SDK developers for privacy manifests (see above WWDC talk). Maybe signatures as well.

# Hints

- https://developer.apple.com/videos/play/wwdc2023/10060
- https://developer.apple.com/news/?id=av1nevon
- https://developer.apple.com/app-store/app-privacy-details/

**Comment by defagos** [comment]
Our 3rd party analytics SDKs now provide privacy manifests:

- comScore since version 6.12.0
- Commanders Act since version 5.4.6.

In addition we should document what our Analytics SDK itself does (only user interactions at the moment, not linked to the user).
