### ISSUE TITLE
Report SwiftUI navigation and modal issues to Apple

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#429]
**As a demo user** I want to be able to use the demo without navigation user experience issues like crashes or hangs. I currently experience the following issues in the demo, though:

- Quickly navigating back with an edge gesture after dismissing a modal (e.g. returning to the show episode list, then back to the A-Z list) makes the app unresponsive.
- Taps to display the player and modal dismissal made randomly in quick succession either:
    - Re-open the previous item, even if another one is tapped.
    - Sometimes crash the player because if duplicate presentation.

# Hints

These issues seem entirely related to the use of `.sheet` for modal presentation and the use of `NavigationStack` for navigation.

# Acceptance criteria

- SwiftUI issues currently affecting the demo have been reported.
- A mitigation strategy has been discussed.

# Tasks

- [x] Reproduce the issue with a small sample project.
- [x] Report the issues separately to Apple.
- [x] Discuss the mitigation strategy to use `.fullScreenCover` instead of `.sheet`. Create a dedicated issue if accepted (close button and / or pull-to-close gesture have to be implemented in this case).

**Comment by defagos** [comment]
- Edge gesture issue reported as FB12460230.

**Comment by defagos** [comment]
I made a quick implementation with `.fullScreenCover`. Though the result is stable we need a close button and pull-down gestures can be added but without interactive dismissal possible (the view behind the covering view is not there until full dismissal). So I guess we should keep `.sheet` for now.
