### ISSUE TITLE
Add support for visionOS

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#435]
**As a developer** I would like to be able to provide native playback experiences using Pillarbox on visionOS.

# Acceptance criteria

- The Pillarbox demo runs natively on visionOS.

# Tasks

- [ ] Use `vtool` to add unofficial visionOS [compatibility](https://mastodon.social/@stroughtonsmith/110605868212230139) for comScore (starting from the tvOS binary most likely, as it should be closer to visionOS APIs).
- [ ] Perform a minimal comScore implementation in a sample project.
- [ ] Use `vtool` to add unofficial visionOS [compatibility](https://mastodon.social/@stroughtonsmith/110605868212230139) for Commanders Act (starting from the tvOS binary most likely, as it should be closer to visionOS APIs). 
- [ ] Perform a minimal implementation in a sample project.

Provided the bullet points above are successful with a stable result (at least stable enough):

- [ ] Ask comScore for official visionOS binaries.
- [ ] Ask Commanders Act for official visionOS binaries.

Then prepare the associated implementation work:

- [ ] Update SRG Data Provider and associated dependencies with visionOS support on dedicated feature branches.
- [ ] Update Pillarbox dependencies for visionOS compatibility.
- [ ] Update the packages so that they successfully compile on visionOS.
- [ ] Update the tests so that they successfully run on visionOS.
- [ ] Update the demo so that is successfully runs on visionOS.
- [ ] Update device type sent in analytics.
- [ ] Update the documentation.
- [ ] Update the Makefile with visionOS targets.
- [ ] Add new platform on App Store connect.
- [ ] Add corresponding CI tasks (UTs, packaging, nightly, release).
