### ISSUE TITLE
Use `xcodes` instead of `xcversion`

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#440]
**As a developer** I would like to adopt the new xcodes standard for Fastlane. This is currently not possible for Xcode beta releases.

# Acceptance criteria

- The Fastfile has been [updated](https://github.com/xcpretty/xcode-install/blob/master/MIGRATION.md) to use `xccodes` instead of `xcversion`.
- Beta releases are supported.

# Context

We already migrated to `xcodes` in the past (see #245) but sadly beta versions are currently not supported with this setup:

- Versions provided to `xcodes` command-line tool are exactly compared to version extracted from local installation information, there is currently [no semantic versioning support](https://github.com/XcodesOrg/xcodes/issues/266). If an Xcode beta was installed with `xcodes` comparison fails since extracted installation metadata is exhaustive and does not match the required information. If an Xcode beta was installed in another way (e.g. `xcinfo`) then matching will work as the extracted installation metadata is less rich and passes the check (only the major / minor / patch versions are checked, basically).
- The `xcodes` Fastlane plugin [fails](https://github.com/fastlane/fastlane/issues/21369) to support betas. Xcodes interprets versions as exact but parses only `15 Beta 3`, for example, which [fails](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/helper/xcodes_helper.rb#L21) Ruby Gem versioning validation. This is a regression from `xcversion` since [semantic versioning](https://github.com/fastlane/fastlane/issues/20866#issuecomment-1319016098) was supported.

## Workaround

A workaround is to use `xcversion` during the Xcode beta phase and `xcodes` for releases. We can provide the same `.xcode_version` file to both with `~> 15.0` as version during the Xcode 15 beta phase.

Pillarbox developer tool setup should not be modified as the long-term goal is to use `xcodes`.

A companion issue to support `Gem:Version` beta version format has also be [opened](https://github.com/XcodesOrg/xcodes/issues/306), with a dedicated PR.

## Next steps

Of course this is a short-term workaround, as `xcversion` is deprecated and likely to be removed someday. Some ideas:

- Monitor the already [reported issue](https://github.com/fastlane/fastlane/issues/21369).
- If we want to be compatible with semantic versioning we could maybe add support directly to `xcodes`. This would ensure that `xcodes` can be truly a replacement for `xcversion`.

# Tasks

- [ ] Check status of the issues listed above.
- [ ] Upgrade `xcodes` if the PR submitted in #442 has been approved.
- [ ] Revert to `xcodes` in Fastfile.
- [ ] Check that the local `.xcode_version` file is correctly configured.

**Comment by defagos** [comment]
We can still use `.xcode-version` and 15 as a version provided there is only a single beta of Xcode 15 installed.
