### ISSUE TITLE
Add custom label support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#443]
**As a developer Integrating Pillarbox** I might need to be able to send custom labels in page views, events or streaming events, depending on what data analysts require.

**As a Play developer** I namely am currently sending:

- `pac_page_id` in page view events, providing the identifier of the PAC page associated with a view event.
- `source_id` in media events, providing the identifier of the list some content was played from.
- `user_id` and `user_is_logged` to provide login status information, for Play RTS / maRTS only.

# Acceptance criteria

- Actual teams needs for custom labels (like e.g. those mentioned above) are supported.

# Tasks

- [ ] Discuss API considerations (single tracking API with service-specific data vs. service-specific tracking APIs, e.g.).
- [ ] Add support for custom global labels (if needed).
- [ ] Add support for custom page view labels (if needed).
- [ ] Add support for custom event labels (if needed).
- [ ] Add support for custom streaming event labels (if needed).
