### ISSUE TITLE
Organize code in packages

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#45]
**As an API user** I want to find APIs in the proper package for ease of use.

# Acceptance criteria

- UI types are moved to the `UserInterface` package.
- A new package (name to be determined) is introduced for convenience tools (publishers, bindings, etc.)

# Tasks

- [x] Move UI classes to `UserInterface`.
- [x] Decide package name
- [x] Create new package and configure project.
- [x] Move sources and tests to the new package.
