### ISSUE TITLE
Generate local stream for subtitles and audio tracks

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#456]
**As a developer** I need to be able to write reliably tests for subtitles and audio tracks.

# Acceptance criteria

- Audio track selection can be tested.
- Subtitle track selection can be tested.

# Tasks

- [x] Generate current streams without local source video file.
- [x] Generate stream without any audio track. [Might not be possible](https://github.com/SRGSSR/pillarbox-apple/issues/50#issuecomment-1236597506), though.
- [x] Generate streams with multiple audio tracks and subtitles.
- [ ] Install required tools on the CI agents.

Remark: Forced subtitles cannot be generated yet. If needed we can still point at an external stream in the meantime (e.g. Apple Bip Bop).

**Comment by waliid** [comment]
## How to install [shaka-packager](https://github.com/shaka-project/shaka-packager) manually?

### Steps:

1. Download a version (e.g. version *[v2.6.1](https://github.com/shaka-project/shaka-packager/releases/download/v2.6.1/packager-osx-x64)*)
2. Rename the binary (e.g. `shaka-packager`)
3. Move the binary to `/usr/local/bin`
5. Change the permissions (`chmod 755 shaka-packager`)
6. Enjoy!
