### ISSUE TITLE
`LayoutReader` and `InteractionView` interrupt the animation transaction chain

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#457]
**As a developer integrating Pillarbox in my user interface** I would like to be able to use `UIViewControllerRepresentable`-based views like `LayoutReader` and `InteractionView` as I would use a simple `ZStack`. But if I currently have animations in my layout then those might not behave as expected depending on where they are applied.

# Acceptance criteria 1

Animations must be correctly transferred through `InteractionView` (and `LayoutReader`). This means the following layout:

```swift
struct RectangleView: View {
    @State private var isLarge = false

    var body: some View {
        InteractionView {
            Color.yellow
            Rectangle()
                .frame(width: 100, height: 100)
                .scaleEffect(isLarge ? 2 : 1)
        }
        .animation(.easeInOut, value: isLarge)
        .onTapGesture {
            isLarge.toggle()
        }
    }
}
```

must be animated identically to the same code obtained by replacing `InteractionView` with a simple `ZStack`.

# Acceptance criteria 2

Animations must be correctly transferred through `InteractionView` (and `LayoutReader`) and have correct limited scope according to where they should apply. This means the following layout:

```swift
struct RectangleView: View {
    @State private var isLarge = true

    var body: some View {
        ZStack {
            Color.yellow
            Rectangle()
                .frame(width: 100, height: 100)
                .scaleEffect(isLarge ? 2 : 1)
        }
        .animation(.easeInOut, value: isLarge)
        .onTapGesture {
            isLarge.toggle()
        }
    }
}

struct ContentView: View {
    @State private var isHalved = false

    var body: some View {
        VStack {
            if isHalved {
                Color.clear
            }
            RectangleView()
            Button(action: toggle) {
                Text("Toggle")
            }
        }
    }

    private func toggle() {
        isHalved.toggle()
    }
}
```

must be animated identically to the same code obtained by replacing `InteractionView` with a simple `ZStack`:

1. Tap on the square first. The square must smoothly shrink and expand with an animation.
2. Tap on the _Toggle_ button. The transition must be abrupt as no animation modifier is applied.

# Investigation strategy

The two separate acceptance criteria above can be combined into a single problem more general than Pillarbox view implementations.

Given a view hosting a `UIHostingController` which itself hosts a SwiftUI view:

```swift
struct HostedView<Content>: UIViewControllerRepresentable where Content: View {
    @Binding private var content: () -> Content

    init(@ViewBuilder content: @escaping () -> Content) {
        _content = .constant(content)
    }

    func makeUIViewController(context: Context) -> UIHostingController<Content> {
        .init(rootView: content())
    }

    func updateUIViewController(_ uiViewController: UIHostingController<Content>, context: Context) {
        uiViewController.rootView = content()
    }
}
```

the following layout:

```swift
struct RectangleView: View {
    @State private var isLarge = true

    var body: some View {
        HostedView {
            Color.yellow
            Rectangle()
                .frame(width: 100, height: 100)
                .scaleEffect(isLarge ? 2 : 1)
        }
        .animation(.easeInOut, value: isLarge)
        .onTapGesture {
            isLarge.toggle()
        }
    }
}

struct ContentView: View {
    @State private var isHalved = false

    var body: some View {
        VStack {
            if isHalved {
                Color.clear
            }
            RectangleView()
            Button(action: toggle) {
                Text("Toggle")
            }
        }
    }

    private func toggle() {
        isHalved.toggle()
    }
}
```

must animated identically if we replace `HostedView` with a simple `ZStack`:

1. Tap on the square first. The square must smoothly shrink and expand with an animation.
2. Tap on the _Toggle_ button. The transition must be abrupt as no animation modifier is applied.

# Current visible effects

In the demo custom player we can observe that the slider and volume button are not animated when toggling the controls. This is due to the use of `LayoutReader` in our layout which, because of this issue, does not allow animation transactions to cross the associated view boundaries correctly. Simply removing the `LayoutReader` in the layout (or replacing it with a `ZStack`) namely solves the issue (at the expense of full screen detection, though).

# Tasks

Several mitigation strategies can be investigated:

- [x] ❌ Use `UIViewRepresentable` instead of `UIViewControllerRepresentable`.
- [x] ❌ Find a way to transfer the transaction to the inner wrapped view.
- [x] ❌ Transfer the observed animation value to the inner wrapped view.
- [x] ✅ Revisit implementation strategy to avoid SwiftUI - UIKit - SwiftUI containment, possibly with overlays, background modifiers, `ZStack` to stack content and detector views, etc.

We should also:

- [x] Report the above issue to Apple if there is no way to fix it without actually having it implemented in the SwiftUI layout engine itself.

**Comment by defagos** [comment]
We can try to transfer the transaction to the inner wrapped view as follows:

```swift
struct HostedWrapperView<Content>: View where Content: View {
    let transaction: Transaction
    @Binding private var content: () -> Content

    init(transaction: Transaction, @ViewBuilder content: @escaping () -> Content) {
        self.transaction = transaction
        _content = .constant(content)
    }

    var body: some View {
        ZStack {
            content()
        }
        .transaction { transaction in
            transaction = self.transaction
        }
    }
}

struct HostedView<Content>: UIViewControllerRepresentable where Content: View {
    @Binding private var content: () -> Content

    init(@ViewBuilder content: @escaping () -> Content) {
        _content = .constant(content)
    }

    func makeUIViewController(context: Context) -> UIHostingController<HostedWrapperView<Content>> {
        .init(rootView: HostedWrapperView(transaction: context.transaction) {
            content()
        })
    }

    func updateUIViewController(_ uiViewController: UIHostingController<HostedWrapperView<Content>>, context: Context) {
        uiViewController.rootView = HostedWrapperView(transaction: context.transaction) {
            content()
        }
    }
}
```

The issue is that the transaction is not scoped, therefore the second acceptance criteria fails as halving the rectangle view space without animation will still apply the animation that has been attached before.

**Comment by defagos** [comment]
The problem affects the SwiftUI - UIKit - SwiftUI containment chain and how transactions can be propagated. Using `UIViewRepresentable` instead of `UIViewControllerRepresentable` therefore does not fix the issue.

**Comment by defagos** [comment]
`LayoutReader` can be updated to avoid the containment issue entirely.

**Comment by defagos** [comment]
There is a conflict between the route picker view and tap gestures we encountered before. We should report it to Apple, see #458.

**Comment by defagos** [comment]
_SwiftUI animations do not flow down correctly across UIViewControllerRepresentable / UIHostingController boundaries_ reported to Apple as FB12663721.
