### ISSUE TITLE
Deploy Shaka packager to CI agents with Homebrew

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#499]
**As a developer** I need to be able to run tests involving subtitle and audio track packaging on our CI agents.

# Acceptance criteria

- A basic test involving subtitles passes locally as well as on the CI servers.

# Tasks

- [ ] Create Homebrew cask for Shaka Packager.
- [ ] Install Shaka Packager on the CI agents via Homebrew.
- [ ] Remove previous installation (see #500).
- [ ] Update stream generation script if needed (the official name of the command is likely [`package`](https://shaka-project.github.io/shaka-packager/html/documentation.html), not `shaka-package`).

**Comment by defagos** [comment]
The source code for Shaka packager is available but compiling from source is not feasible. So I guess we should provide a cask, like [Android command-line tools](https://github.com/Homebrew/homebrew-cask/blob/510b497e0a09963da36a037cea7e8e5618860482/Casks/android-commandlinetools.rb) for example.
