### ISSUE TITLE
Basic support for subtitles and audio tracks

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#501]
**As a user** I want to be able to see subtitles and audio tracks available for some content, as well as to select / deselect a track. 

# Acceptance criteria

- An API is provided to list available subtitles and audio tracks.
- An API is provided to list the current subtitle and audio track selection.
- An API is provided to select a track (or remove selection if this makes sense).
- Forced subtitles must not treated in a special way (will be addressed in #502).
- The behavior is correct when no subtitles or audio tracks are available.
- Up to non-supported features results are consistent with the Apple system player user interface.

# Hints

If this makes sense track management can be moved to a tracker management state object, which can be bound to a player like progress tracker or visibility tracker can. However this might not be justified here:

- Progress tracker makes it possible to isolate frequent updates. Here it is likely that only a couple updates are added if track management is built in the player itself.
- Visibility tracker was introduced to extract a UI-only behavior which makes no sense in the player itself.

# Documentation

See [official documentation](https://developer.apple.com/documentation/avfoundation/media_playback/selecting_subtitles_and_alternative_audio_tracks).

# Tasks

- [x] Add API to list available subtitles and audio tracks (forced subtitles not filtered).
- [x] Add API to get the current selection (forced subtitles not filtered).
- [x] Add API to change the current track selection (basic, no automatic mode).
- [x] Use MediaAccessibility where appropriate, most notably for interactive vs. non-interactive selection and, if not automatically taken into account, for retrieval.
- [x] Display menu in the demo.
- [x] Increase settings menu icon size.
- [x] Perform basic check with Play CH content.
- [x] Compare behavior between vanilla player UI and custom PB UI and ensure all scenarios match.
- [x] Check behavior over AirPlay (e.g. correct initial detection).
- [x] Provide menu components in the Player library if meaningful.
- [x] ~Attempt to build a test stream with `AUTOSELECT` set to `YES` for only some subtitles, if possible. Write a dedicated unit test that verifies we are not only relying on MediaAccessibility.~ _Shaka Packager manages this flag internally._

**Comment by defagos** [comment]
I introduced a `MediaSelector` type to implement the media selection logic. If there is later a need for more flexibility we could:

1. Create a `MediaSelector` protocol with the required selection methods.
2. Have the current `StandardMediaSelector` (renaming required) implement `MediaSelector`.
3. Provide a way for developers to supply their own type conforming to `MediaSelector` during player configuration.

**Comment by defagos** [comment]
Interesting use case to write as a unit test:

1. Play content supporting Japanese as subtitles (expect Japanese).
2. Play other content which does not support Japanese (expect Off according to Apple player implementation).
3. Play content in Japanese again. Japanese must still be the active subtitles (both displayed as well as returned from the API).

**Comment by defagos** [comment]
Here is the stack trace leading to `-[AVMediaSelection selectedMediaOptionInMediaSelectionGroup:]` being called when playback starts with `AVPlayerViewController`:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 4.1
    frame #0: 0x000000019e3caf38 AVFCore`-[AVMediaSelection selectedMediaOptionInMediaSelectionGroup:]
  * frame #1: 0x00000001b5905268 AVKit`-[AVPlayerController(AVMediaSelection) _selectedMediaOptionWithMediaCharacteristic:] + 132
    frame #2: 0x00000001b5907bb8 AVKit`-[AVPlayerController(AVMediaSelection) currentAudioMediaSelectionOption] + 40
    frame #3: 0x00000001b59c3fc4 AVKit`-[AVPlayerController currentEnabledAssetTrackForMediaType:] + 120
    frame #4: 0x00000001b59c48e8 AVKit`-[AVPlayerController _updateCurrentAudioTrackIfNeeded] + 64
    frame #5: 0x00000001b591da58 AVKit`__70-[AVObservationController startObserving:keyPaths:observationHandler:]_block_invoke + 60
    frame #6: 0x00000001b58cad98 AVKit`__105-[AVObservationController startObserving:keyPaths:includeInitialValue:includeChanges:observationHandler:]_block_invoke + 220
    frame #7: 0x00000001b58cac7c AVKit`-[AVProxyKVOObserver _handleValueChangeForKeyPath:ofObject:oldValue:newValue:context:] + 144
    frame #8: 0x00000001b58cab94 AVKit`-[AVProxyKVOObserver observeValueForKeyPath:ofObject:change:context:] + 196
    frame #9: 0x000000018b8f4e98 Foundation`NSKeyValueNotifyObserver + 252
    frame #10: 0x000000018b8f4d34 Foundation`NSKeyValueDidChange + 356
    frame #11: 0x000000018b8f4b64 Foundation`-[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 680
    frame #12: 0x000000018b8f4894 Foundation`-[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 64
    frame #13: 0x000000018b98b7e8 Foundation`_NSSetObjectValueAndNotify + 284
    frame #14: 0x0000000105c78f50 libdispatch.dylib`_dispatch_call_block_and_release + 32
    frame #15: 0x0000000105c7ab34 libdispatch.dylib`_dispatch_client_callout + 20
    frame #16: 0x0000000105c8afec libdispatch.dylib`_dispatch_main_queue_drain + 1084
    frame #17: 0x0000000105c8aba0 libdispatch.dylib`_dispatch_main_queue_callback_4CF + 44
    frame #18: 0x000000018c8ea5bc CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
    frame #19: 0x000000018c8e72f0 CoreFoundation`__CFRunLoopRun + 1996
    frame #20: 0x000000018c8e6a40 CoreFoundation`CFRunLoopRunSpecific + 600
    frame #21: 0x00000001cee2f5ec GraphicsServices`GSEventRunModal + 164
    frame #22: 0x000000018ecfdba0 UIKitCore`-[UIApplication _run] + 888
    frame #23: 0x000000018ecfd1dc UIKitCore`UIApplicationMain + 340
    frame #24: 0x0000000191c63544 SwiftUI`___lldb_unnamed_symbol215670 + 176
    frame #25: 0x0000000191c63388 SwiftUI`___lldb_unnamed_symbol215668 + 152
    frame #26: 0x000000019100c2b0 SwiftUI`___lldb_unnamed_symbol128913 + 128
    frame #27: 0x00000001046e2e80 Pillarbox-demo`static DemoApp.$main(self=Pillarbox_demo.DemoApp) at <compiler-generated>:0
    frame #28: 0x00000001046e306c Pillarbox-demo`main at DemoApp.swift:65:8
    frame #29: 0x00000001af988d44 dyld`start + 2104
```

**Comment by defagos** [comment]
The current implementation based on `currentMediaSelection` already correctly takes into account SDH and AD flag.

**Comment by defagos** [comment]
The current media selection is incorrectly reported over AirPlay, see #511.

**Comment by defagos** [comment]
I discovered empirically that there is no need to select a legible option on `AVPlayerItem`. Using `MediaAccessibility` API automatically ensures that this happens consistently. I could therefore avoid such calls in `AudibleSelectionGroup` selection implementation.

**Comment by defagos** [comment]
I implemented behavior similar to `AVPlayerViewController`:

- Though it can be possible disabling audio (if present) is not an option.
- Subtitle selection relies on `MediaAccessibility`.

As said above we could allow custom `MediaSelector` implementations should the need to have different behaviors be needed.
