### ISSUE TITLE
Forced subtitles support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#502]
**As a user** I want forced subtitles to be automatically enabled when appropriate. I never want to see them or be able to select them directly.

# Acceptance criteria

- Forced subtitles are automatically enabled based on the currently selected audio language.
- Forced subtitles are never returned from usual public player APIs.
- Forced subtitles cannot be selected via the public player API.
- Forced subtitles are not displayed in the demo.

# Documentation

- [Team discussion](https://github.com/SRGSSR/pillarbox-documentation/issues/44).
- https://developer.apple.com/library/archive/releasenotes/AudioVideo/RN-AVFoundation/index.html#//apple_ref/doc/uid/TP40010717-CH1-DontLinkElementID_3
- https://github.com/videojs/http-streaming/pull/1329
- [Official documentation](https://developer.apple.com/documentation/mediaaccessibility/macaptionappearancedisplaytype).
- Possibly [useful API](https://developer.apple.com/documentation/avfoundation/avmediaselectiongroup/1387351-playablemediaselectionoptions).

# Tasks

- [x] Filter forced subtitles from subtitle lists.
- [x] Ensure forced subtitles cannot be selected from the public API, even if they were retrieved in some other way (e.g. directly from the queue player asset).
- [x] Automatically enable forced subtitles based on the currently selected audio language, when no subtitle track has been explicitly selected.
    - [x] Enable when setting subtitles to Off.
    - [x] Enable when setting subtitles to Automatic (if automatic selection does not enable unforced subtitles).
    - [x] Update when changing the audio language, both for Off and Automatic selection already applied to subtitles.
- [ ] Check behavior over AirPlay.
- [x] Document packaging requirements, most notably the use of `AUTOSELECT` for forced subtitles.

**Comment by defagos** [comment]
In fact forced subtitles are quite [easy](https://developer.apple.com/forums/thread/43424) to implement:

- Subtitles must be marked as `AUTOSELECT`.
- We set the media accessibility preferences to `.forcedOnly`.
- We call `selectMediaOptionAutomatically(in:)` to enable automatic selection.

`AVPlayer` then behaves correctly. What we need is therefore only to filter forced subtitles and to provide documentation about how packaging must be made.

Still providing the ability to implement custom `MediaSelector`s can be helpful but we can keep things simple for the default implementation, providing that the packaging is done right.

**Comment by defagos** [comment]
Over AirPlay:

- When changing options on mobile with the TV selection menu open, the TV selection is not updated visually but the player correctly switches to the newly selected option.
- When changing options on TV with the mobile selection menu open, the mobile selection is correctly updated for _Off_ and unforced options. Since the TV system UI displays forced subtitles ([incorrectly](https://developer.apple.com/forums/thread/43424) IMHO) selecting a forced subtitle makes menu item selection disappear on device, a minor annoyance, though.

**Comment by defagos** [comment]
For reference there is an interesting `AVMediaSelectionOption.associatedMediaSelectionOption(in:)` API which is able to find related options in different groups, e.g. forced subtitles. Not useful but still interesting to know.
