### ISSUE TITLE
Automatic subtitle selection

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#503]
**As a user** I want automatic subtitle selection to be available. Automatic selection must take care of selecting the most appropriate subtitle selection based on the current audio language.

# Acceptance criteria

- An API is available to enable automatic subtitle selection.
- A corresponding option is available in the demo.

# Documentation

- [Team discussion](https://github.com/SRGSSR/pillarbox-documentation/issues/44).

# Tasks

- [x] Understand what automatic subtitle selection actually is.
- [x] Understand possibly [related APIs](https://developer.apple.com/documentation/avfoundation/avplayer/1387178-appliesmediaselectioncriteriaaut), most notably preferred settings and automatic behavior.
- [x] ~Generate new test streams if needed (e.g. stream with `DEFAULT` for some language or with `AUTOSELECT` not available for all languages).~
- [x] Add API to enable automatic subtitle selection.
- [x] Add corresponding option to the demo player menu.
- [x] Check behavior over AirPlay.

**Comment by defagos** [comment]
I had a look at what is returned by `preferredMediaSelection` when AD / SDH settings are enabled or disabled but the results are not affected. This property isn't therefore a cheap way to get the subtitles or audio tracks to prefer based on accessibility settings.

**Comment by defagos** [comment]
We need to clearly identify what _Automatic_ means. After discussions with @amtins and @StaehliJ it appears that our [SRG Media Player](https://github.com/SRGSSR/srgmediaplayer-apple) was likely taking too many decisions and that the definition of this automatic mode should be simpler.

It is likely that:

- This is related to the _AUTOSELECT_ playlist option.
- According to some [non-official Akamai documentation](https://techdocs.akamai.com/msod/pdfs/msod-stream-packaging-user-guide.pdf) automatic mode might select a best match only within _AUTOSELECT_ options.

We should therefore:

- Think about several use cases.
- Tweak streams to see how packaging affects automatic selection, on iOS, tvOS and macOS. Warning: Safari and QuickTime have different behaviors it seems.

**Comment by defagos** [comment]
See [comment elsewhere](https://github.com/SRGSSR/pillarbox-apple/issues/501#issuecomment-1671945189) for an important remark about `AUTOSELECT` behavior and relationship with MediaAccessibility.

**Comment by defagos** [comment]
Automatic selection requires `appliesMediaSelectionCriteriaAutomatically` to be set to `true` (the default). Our implementation will use this default behavior. The rest works correctly provided playlists are [properly configured](https://github.com/SRGSSR/pillarbox-documentation/issues/45).

**Comment by defagos** [comment]
Some remarks:

- We cannot create tweak `AUTOSELECT` with Shaka Packager since this flag is set internally. So the sample stream set was not extended.
- The implementation was done in #516. Please refer to this issue for more information. For automatic selection based on accessibility settings please refer to #504.

**Comment by defagos** [comment]
We finally understood how _Automatic (Recommended)_ works. Note that for a rendition to be selectable automatically, most notably in this mode, it needs to be flagged with `AUTOSELECT=YES` in the master playlist.

Here is how _Automatic (Recommended)` works:

- For audible rendition selection, the system finds the first language that matches one of the preferred languages defined in the system settings, in order of appearance. If not it uses a default option (the one with `DEFAULT=YES` is preferred, if any).
- For legible rendition selection, the result depends on the selected audio language:
    - If the selected audio language appears in the preferred languages defined in the system settings, no subtitles will be displayed. The user is supposedly able to understand this language after all.
    - If the selected audio language does not appear in the preferred languages defined in the system settings, the first subtitles matching one of the preferred languages, in order of appearance, are used. Otherwise a default option is used  (the one with `DEFAULT=YES` is preferred, if any).

Note that this automatic selection logic is affected by accessibility settings, though the idea remains the same.
