### ISSUE TITLE
Accessibility for subtitles and audio tracks

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#504]
**As a user who requires accessibility features** I want the best possible playback experience tailored to my needs.

# Acceptance criteria

- Audio description tracks are favored if the corresponding accessibility setting has been enabled.
- SDH subtitles are favored if the corresponding accessibility setting has been enabled. The user experience is identical to Apple system player UI, i.e. the list does not present SDH and non-SDH subtitles were redundant.

# Documentation

- [Team discussion](https://github.com/SRGSSR/pillarbox-documentation/issues/44).

# Tasks

- [x] Provide AD audio tracks first if enabled in accessibility settings.
- [x] Provide SDH subtitles first if enabled in accessibility settings. Match the result obtained for the system player and our custom menu with Apple Dolby Atmos sample stream.
- [x] Document stream packaging recommendations (characteristics and autoselect).

**Comment by defagos** [comment]
Likely already implemented in #502 since the system automatically takes into account these settings.

**Comment by defagos** [comment]
AD already works well but SDH still needs some work so that the result is identical to the system player UI. Likely something very similar as support for forced subtitles.

**Comment by defagos** [comment]
I implemented the feature on the `sdh-support` branch but this branch relies on #533 being merged. Once this PR has been merged we can open the issue branch and cherry-pick the commits.

We have a slight difference with Apple implementation, which shows CCs when the Accesssibility CC+ SDH flag has not been enabled. IMHO our implementation is better since it matches the setting description.

Writing tests is a nightmare, though. I don't see how we can achieve something meaningful but this is something we can discuss next week with @waliid.

**Comment by defagos** [comment]
[As for forced subtitles](https://github.com/SRGSSR/pillarbox-apple/issues/502#issuecomment-1683623361) changes made on the Apple TV are partially reflected to the device but there is nothing we can do to fix this issue. It is still a minor issue IMHO.

**Comment by defagos** [comment]
Play CH test streams have only `public.accessibility.describes-music-and-sound` and won't therefore be correctly filtered based on the SDH / CC accessibility setting. Packaging should be updated to [add](https://developer.apple.com/documentation/http-live-streaming/hls-authoring-specification-for-apple-devices#Accessibility) the `public.accessibility.transcribes-spoken-dialog` as well.
