### ISSUE TITLE
Provide hooks for track customization

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#507]
**As a developer integrating Pillarbox** I want to be able to reliably override the default track selection.

# Acceptance criteria

- It is possible to force audio and subtitle selection based on the really available options for an item.
- Overriding works in playlists containing several items.
- The default initial selection of an item can be altered (also in playlists) but the user should be able to change it afterwards.

# Hints

- We should likely not have a customization hook per item but rather let apps [customize](https://github.com/SRGSSR/pillarbox-apple/issues/501#issuecomment-1671968177) `MediaSelector` instead. If an app needs to override the selection logic it won't be per item but likely based on app-managed settings.

# Tasks

- [x] Add hook or similar mechanism to override media selection options at startup.
- [x] Ensure the behavior with playlists is fine.
- [x] Add an example to the showcase (muted playback with always visible subtitles, e.g.).
- [x] Write unit tests with player already loaded with an item and setup for language selection afterwards.
- [x] Write unit tests with player empty, setup for language selection and loaded with an item afterwards.
- [x] Document selection issue reported to Apple (FB13070742) as known issue.
- [x] ~Check that there are not leaks (in particular the transition demo seems to leak. Maybe because of sheet presented from sheet?).~ _Leak on iOS 17 beta, no issue on iOS 16_
- [x] ~Expose `MediaSelector` for customization?~ _Not yet_
- [x] Fix following issue:
    - Override subtitles and / or audio to ja / it in demo `PlaybackView`.
    - Play some content without these languages (but others) and attempt to change subtitles afterwards. Selection does not work.

**Comment by defagos** [comment]
Here is an implementation concept based on the current implementation:

- Run all `MediaSelector`s.
- Once all selectors have been run provide a call that receives the current `MediaSelection` as well as the `MediaSelectionContext` so that the app can override the delivered selection.

We should also maybe provide a way to replace the default `MediaSelectors` per characteristic. This way we should have full flexibility.

**Comment by defagos** [comment]
We can likely use the following to specify a preferred language before playback starts, e.g. for subtitles:

```
let criteria = AVPlayerMediaSelectionCriteria(preferredLanguages: ["en"], preferredMediaCharacteristics: nil)
queuePlayer.setMediaSelectionCriteria(criteria, forMediaCharacteristic: .legible)
```

It might be enough to expose this API so that apps can force a language before playback starts.

**Comment by defagos** [comment]
# Use cases

- Test streams: The Morning Show (trailers from seasons 1 & 2). These are extremely well packaged streams with a lot of features (AD, SDH, original version flag, keyframes). They conform to what we expect regarding autoselection as well.
- Preferred device languages: FR, EN

## No overrides

Setup:

- Custom player
- No override
- No accessibility settings

Expected result:

- Audio starts with 1st device language (FR).
- Audio can be changed. Reopening the player starts with FR again.
- Subtitles can be freely selected (other language, off, auto) and are persisted automatically.

## Audio override

Setup:

- Custom player
- Override **audio** with DE
- No accessibility settings

Expected result:

- Audio starts with DE.
- Audio can be changed. Reopening the player starts with DE again. New audio choice is persisted for the player session (append to audible criteria).
- Subtitles can be freely selected (other language, off, auto) and are persisted automatically (append to legible MA).

## Subtitle override

Setup:

- Custom player
- Override **subtitles** with DE
- No accessibility settings

Expected result:

- Subtitles starts with DE.
- Audio can be changed. Reopening the player starts with DE again. New audio choice is persisted for the player session (append to audible criteria).
- Subtitles can be freely selected (other language, off, auto) and are persisted automatically (append to legible MA and clear the legible criteria).

🚧 Learnings:

- We must write a UT for this case: Start with override then select .off / .auto. Must deliver .off / .auto as selected value.

# No override in playlist

Setup:

- Playlist player, same media loaded twice
- No override
- No accessibility settings

Expected result:

- Audio starts with 1st device language (FR).
- Audio can be changed. Reopening the player starts with FR again. Moving to the next item preserves audio selection.
- Subtitles can be freely selected (other language, off, auto) and are persisted automatically. Moving to the next item preserves subtitle selection.

# Audio override in playlist

Setup:

- Playlist player, same media loaded twice
- Override **audio** with DE
- No accessibility settings

Expected result:

- Audio starts with DE.
- Audio can be changed. Reopening the player starts with DE again. Moving to the next item preserves audio selection.
- Subtitles can be freely selected (other language, off, auto) and are persisted automatically. Moving to the next item preserves subtitle selection.

# Subtitle override in playlist

Setup:

- Playlist player, same media loaded twice
- Override **subtitles** with DE
- No accessibility settings

Expected result:

- Subtitles starts with DE.
- Audio can be changed. Reopening the player starts with DE again. New audio choice is persisted for the player session (append to audible criteria). Moving to the next item preserves audio selection.
- Subtitles can be freely selected (other language, off, auto) and are persisted automatically (append to legible MA and clear the legible criteria). Moving to the next item preserves subtitle selection.

# Remarks

- We need to test that preferences are appended to criteria so that fallbacks are in place.
- Document the clearing behavior (similar to Apple media selection criteria documentation).

**Comment by defagos** [comment]
A remark about selection:

- For legible renditions we use Media Accessibility to append recent language user choices. This is persisted at the system level and restored between playback sessions.
- For audible renditions there is no system mechanism but we can still persist audio choices during a playback session (most notably between playlist items) by appending language choices to the current media selection. This provides for a smoother experience, especially when playing several episodes of the same TV series with similar renditions available.

**Comment by defagos** [comment]
It is likely that the `DEFAULT` attribute is still used a bit by `AVPlayer`, most notably when there are no media selection criteria explicitly set. To be confirmed.

**Comment by defagos** [comment]
A few things about `AVPlayer.setMediaSelectionCriteria(_:forMediaCharacteristic:):

- Setting `criteria` to `nil` resets to default system-based values. The system takes into account language and accessibility preferences.
- Setting `criteria` to an` `AVPlayerMediaSelectionCriteria` instance which has either its preferred language, resp. characteristic parameter `nil` is **not** equivalent as using default system-based preferences. In this case `nil` means none.

The above is true for audible and legible characteristics, and for all usual accessibility behaviors (AD, SDH).

**Comment by defagos** [comment]
Automatic selection has been [documented](https://github.com/SRGSSR/pillarbox-apple/issues/503#issuecomment-1696845818) on the dedicated thread.

**Comment by defagos** [comment]
The `MediaSelector` protocol now provides a way to implement custom selectors. If there is a need in the future we could add an `AVMediaCharacteristic` to `MediaSelector`-conforming classes dictionary to our player configuration, letting developers write and register their own selectors if they are not happy with our default implementations.

Since implementing a selector can be quite tricky it is likely better to wait until there is a real need before we expose this API.
