### ISSUE TITLE
Audio track and subtitle analytics

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#508]
**As an ADI analyst** I want to be able to know whether audio tracks or subtitles have been enabled or not, and which ones.

# Acceptance criteria

- Track-related fields are properly sent in Commanders Act streaming analytics.

# Tasks

- [x] Discuss forced subtitles. Should we send the subtitle language? (likely not since there is no involved user selection)
- [x] Discuss automatic selection. Should we send the subtitle language? (likely yes since there is a selection involved) If yes then add a method to get the low-level selection, e.g. `activeMediaOption(for:)`.
- [x] Send `media_audio_track` in Commanders Act analytics (`UND` if none).
- [x] Send `media_subtitle_selection` and `media_subtitles_on` in Commander Act analytics (`UND` if none).
- [x] Ensure forced subtitles are not sent.

**Comment by defagos** [comment]
We asked ADI for information, most notably regarding forced subtitles.

**Comment by defagos** [comment]
Confirmed by ADI:

> Are both fields mandatory or could media_subtitle_selection possibly be enough?

Yes, both mandatory

> Play Suisse is displaying [forced subtitles](https://www.3playmedia.com/blog/what-are-forced-narrative-subtitles/#:~:text=Forced%20subtitles%20clarify%20only%20the,toggled%20on%20by%20the%20viewer.), i.e. subtitles which are not meant to be selected by the user but are present as a way to transcribe dialogs in a foreign language (e.g. if you watch a movie with German audio and the characters are in a US town, dialogs heard in English will be translated in German as forced subtitles, but standard German dialogue won’t). Forced subtitles should be considered as being part of the video directly, though they aren’t to spare encoding / storage costs. They are therefore never meant to be selected manually and must rather be enabled automatically depending on the current audio track. Thus our question: Should we treat forced subtitles like any other subtitles or should we ignore them entirely in streaming analytics?


They should be ignored since they are not the usual type of subtitles a user switches on. If this is tracked it would compromise the data of the real subtitles. This is to be done as long as it does not mess up the rest of the `media_subtitle_selection` of “normal” Play Suisse subtitles.

**Comment by defagos** [comment]
The specifications we have implemented are a best effort, as they were during the Letterbox area. We namely never notify audio or subtitle selection changes, each event merely reflects the current value when it is sent.

With Pillarbox asynchronously responding to changes the play event is recorded before selections are applied, thus subtitles will not be seen as enabled in initial play events, most notably. This status is updated in subsequent events like `pos`, though, thus this should be acceptable.

If this proves to be an issue in the future:

- Maybe the specifications should be improved (e.g. a dedicated event should be sent).
- Or our tracker implementation should combine playback state, seeking state as well as media selection availability.
