### ISSUE TITLE
Report AirPlay media selection issues to Apple

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#511]
**As a Pillarbox developer** I want to avoid introducing nasty workarounds for corner cases. Player item `currentMediaSelection` is currently broken over AirPlay resulting in minor bugs. This issue should be reported to Apple.

# Acceptance criteria

- `currentMediaSelection` issues have been reported to Apple.

# Hints

- `currentMediaSelection` reports updates during playback but does not deliver the initial value. Current workaround is to wait until the player is ready to play, at which point reading the property delivers the current value. A publisher can then be used to get further updates resulting from media selection updates triggered by the user.
- `currentMediaSelection` is incorrect over AirPlay, which can simply be observed by periodically logging the value for the current item. As a result the following fails with Pillarbox as well as the vanilla player and player UI:
    - Open Apple 16:9 basic example.
    - Pick Japanese SDH subtitles so that the selection is saved with MediaAccessibility.
    - Close the player.
    - Open the player. Subtitles are correctly set in Japanese and marked as such in the selection menu.
    - Enable AirPlay from the Control Center.
    - Open the player. Subtitles are not incorrectly reported as English SDH. 

# Tasks

- [ ] Check behavior with various iOS / tvOS version combinations in the following scenarios (report what language is returned by `currentMediaSelection` and which subtitles, if any, are visible on screen):
  - [ ] Pillarbox player, custom UI.
  - [ ] Pillarbox player, system UI.
  - [ ] Vanilla player and UI.
- [ ] Write bug report.
- [ ] Document as known issue in Pillarbox documentation.

**Comment by defagos** [comment]
This is a tvOS bug. It was partially fixed in tvOS 18 (tested with tvOS 18 beta):

- The reported subtitle selection is now correct on the casting device...
- ... but the subtitles are not displayed on the receiver.

**Comment by defagos** [comment]
Same behavior with tvOS 26 and tvOS 27 beta 4. No subtitles are enabled on the casting device.
