### ISSUE TITLE
Add support for user consent

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#524]
**As a SRG SSR executive** I want user consent management to be implemented consistently in all SRG SSR mobile and TV products.

# Acceptance criteria

- User consent can be sent to Commanders Act so that it can be taken into account properly.
- comScore can be enabled or disabled on the fly, most notably for users in the EU.

# Hints

- [Documentation](https://confluence.srg.beecollaboration.com/display/SRGPLAY/Project+-+User+consent).
- [Similar issue for SRG Analytics](https://github.com/SRGSSR/srganalytics-apple/issues/66).

# Tasks

- [ ] Add closure to request the most recent Commanders Act user consent status for a list of services.
- [ ] Add closure to request the most recent comScore user consent status (see implementation guide, section 2.5).
- [ ] Send user consent to Commanders Act in `consent_services`.
- [ ] Send user consent to comScore (likely according to the implementation guide, section 2.5).
