### ISSUE TITLE
Add debugging-oriented player view layout

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#542]
**As a Pillarbox developer** I would like to be able to quickly have a look at what is being played.

# Acceptance criteria

- A demo player layout is available displaying various debugging information (e.g. current tracks, bitrates, etc.).

# Hints

- On Apple TV debugging options can be enabled from the Developer settings. They could inspire us. Maybe there is also something similar available for iOS nowadays, making this task irrelevant.
- 17.4 adds `AVVideoPerformanceMetrics` which might be useful.

# Tasks

- [ ] Add debbugging-oriented demo player layout.
- [ ] Add to selectable demo layouts.
- [ ] Add button to download and display the playlist within the app directly.
- [ ] Content of the error log (might display non-critical bandwidth-related stream issues in real time, e.g.).

**Comment by defagos** [comment]
Now irrelevant since most of the suggested debugging tools have been implemented recently:

- Playback HUD overlay on iOS (demo only since we are tweaking a setting).
- Metrics collector.
- Metrics debugging view (demo only at the moment but could be moved to the Monitoring package).

Only the playlist download feature is missing but I honestly don't think it would be useful (proxy tools are better and provide for a more comfortable experience).
