### ISSUE TITLE
Cleanup packages

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#564]
**As a developer integrating Pillarbox** I would like to have minimal footprint, at least avoiding unnecessary artifacts.

# Acceptance criteria

- Superfluous packages have been removed.
- Superfluous dependencies have been removed.

# Tasks

- [x] Remove `UserInterface` and `Diagnostics` packages.
- [x] Update build scripts.
- [x] Remove superfluous 3rd party dependencies.
