### ISSUE TITLE
Update to Xcode 15 / iOS 17 / tvOS 17 final

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#566]
**As a Pillarbox developer** I want the project to be compiled with the most recent Xcode version and to work well with the most recent iOS / tvOS version.

# Acceptance criteria

- The project works fine on Xcode 15 and iOS / tvOS 17.
- The code has been modernized.

# Tasks

- [x] Adopt new Xcode previews and improve display for each of them.
- [x] Remove preprocessor directives testing compiler version (5.9).
- [x] ~Adopt new language features (e.g. return switch).~
- [x] ~Use URL macro.~ _None officially provided_
- [x] Check all remaining bug reports and update status.
- [x] Update CI agents and Fastlane configuration.
- [x] Create SwiftLint update task.

**Comment by defagos** [comment]
No bug we reported during the iOS / tvOS 17 beta phase has been fixed, sadly. I updated their status but we cannot do much more for the moment.

**Comment by defagos** [comment]
I started [`if` and `switch` adoption](https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md) but for the moment:

- The linter forces us to have a return in each case.
- In some cases this feels a bit awkward.

My current recommendation: Wait until swiftlint implements dedicated rules, update our linter configuration and run an automatic fix. This way we will adopt good practices for free.

**Comment by defagos** [comment]
SwiftLint update task created as #568.

**Comment by defagos** [comment]
Though the leak reported in FB13126425 was sadly not fixed.

We can still avoid leaks when using `AVPlayer` as view state by conforming `AVPlayer` to `ObservableObject`, thus storing the player instance as `@StateObject` instead of `@State`. I therefore updated our vanilla player example so that it does not leak anymore.
