### ISSUE TITLE
Update SwiftLint for Swift 5.9

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#568]
**As a Pillarbox developer** I would like to benefit from language enhancements and associated new best practices.

# Acceptance criteria

- SwiftLint is updated to a new version with rules supporting language enhancements introduced by Swift 5.9.

# Tasks

- [ ] Check whether a SwiftLint version supporting Swift 5.9 has been released.
- [ ] Update local and CI agent setup.
- [ ] Update ruleset (e.g. rule for [`if` and `switch` expressions](https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md) if available).
- [ ] Run rules to automatically apply improvements.
