### ISSUE TITLE
Set minimum deployment target to iOS / tvOS 16

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#59]
**As an integrator** I want to be able to integrate Pillarbox in projects running iOS 16, tvOS 16 and above.

# Acceptance criteria

- The project can be integrated in projects running iOS 16 and tvOS 16 only.
- The demo runs on iOS 16 and tvOS 16.

# Tasks

- [x] Update package format to 5.7.
- [x] Update package file to iOS 16 and tvOS 16.
- [x] Update demo to iOS and tvOS 16.
- [x] Update readme.
- [x] Use modern Xcode 14 project format.
- [x] Move to `NavigationStack`.
