### ISSUE TITLE
Improve media selection API

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#595]
**As a developer integrating Pillarbox** I want to be able to locally observe media selection properties so that only related parts of my user interface relate to its changes.

# Hints

See #584. Media properties should likely not need to be observed as essential player state since they are used only for very specific purposes (mostly settings menu implementation). For this reason having them in core properties is likely superfluous.

# Acceptance criteria

- Local subscription to media selection properties is possible.

# Tasks

- [x] ~Investigate API to have media selection in extended properties.~
- [x] ~Implement basic getter methods on media selection properties and rely on them in the `Player+MediaSelection` implementation.~
- [x] ~Update menu implementation.~

**Comment by defagos** [comment]
After thinking about this issue I am not convinced we should change how media selection is handled. From an API perspective there would be little value to have getters on published media selection properties, since interesting information depends on the player anyway (media selection criteria are namely retrieved from the player and are required).

But I still think that not being able to use standard observability for menu implementation (and our `mediaOption(for:)` binding) is an API issue. I will therefore propose we cache media selection criteria at the player instead, thus mitigating the performance issues observed in #584. The criteria are changed very rarely by the user, so having them cached for the lifetime of the player is not a real issue in practice.
