### ISSUE TITLE
Picture in Picture PoC

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#605]
**As a Pillarbox developer** I want to have a better understanding of how picture in picture could be implemented in Pillarbox so that any SwiftUI- or UIKit-based application is able to easily implement this feature.

# Acceptance criteria

- A basic SwiftUI integration example is available.
- A basic UIKit integration example is available.
- An API proposal is made.
- A basic overview of the required components is provided.

# Hints

- [Adopting Picture in Picture in a Custom Player](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player)
- [Adopting Picture in Picture in a Custom Player](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_standard_player)

# Expected behaviors to implement / work correctly

- Enter PiP when throwing the app to the background.
- Manual PiP with dedicated button.
- Move to PiP via button, send app to the background, then resume from PiP overlay (must not glitch).
- Automatic PiP exit when switching to an app and returning while the player is still visible.
- Should be able to exit from PiP if navigating to the currently playing item (instead of interrupting playback to play the same content).

# Tasks

- [x] Integrate with the SwiftUI demo.
- [x] Create an example with UIKit.
- [x] Make it work with the system UI.

**Comment by defagos** [comment]
Possible integration scenarios for PiP to consider for the final implementation:

- `VideoView` in SwiftUI iOS app.
- `VideoView` in UKit iOS app.
- `SystemVideoView` in SwiftUI tvOS app.
- `SystemVideoView` in UKit tvOS app.

**Comment by defagos** [comment]
A first PoC has been pushed onto the `605-picture-in-picture-poc` branch. Here are a few learnings extracted from this PoC and which could be useful for our future implementation.

# Relationship with player layers

[SRG Media Player](https://github.com/SRGSSR/srgmediaplayer-apple) implemented lazy view instantiation (and storage) at the controller level. This now appears to be fundamentally flawed:

- We could not share the same controller between several video layers (only one view would display images).
- The PiP controller had to be stored by the controller, one for each instance, even though actually one PiP controller can be active at any time within an app.
- PiP, essentially a temporary borrowal of an `AVPlayerLayer` by an `AVPictureInPictureController`, was implemented as a controller behavior, while fundamentally it only needs to collaborate with its layer.
