### ISSUE TITLE
Add PiP support to `SystemVideoView`

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#610]
**As a developer integrating Pillarbox** and the standard system UI I want to be able to add PiP support to my application.

# Acceptance criteria

- PiP can be enabled in the demo (examples with the system UI and demo-wide opt-in).
- Expected PiP behaviors work well:
  - Enable when transitioning to the background or switching to another app (without interruption).
  - Enable with dedicated button.
- Player UI controls are correct.

# Tasks

- [x] Wrap `AVPlayerViewController` in `VideoView` view controller representable.
- [x] Provide lifecycle customization API.
- [x] Implement correct dismissal and restoration, in particular:
    - [x] Automatic restoration when returning to the same content.
    - [x] Correct _reset_ when dismissing without PiP or using the PiP overlay close button.
- [x] Ensure it works well everywhere (most notably custom player and playlist).
- [x] Restore full screen if selecting the content already being played in PiP.
- [x] Ensure that the behavior is correct when PiP is started from a maximized state (double-ended arrow at the top left pressed).
- [x] Provide PiP as opt-in for the view if this makes sense (i.e. if additional integration work is required for the opt-in).
- [x] Ensure that controls at the top left are correct (no need for custom close button anymore).
- [x] Ensure that resources do not leak. In particular when moving from PiP enabled for player A by playing content with another player B (reference counting strategy to manage global models?).
- [x] ~Improve example names (`VideoPlayer` examples vs. other examples which use our own system view). Maybe we could have simple `AVPlayerViewController` vanilla wrapping and `VideoPlayer` sections for comparison.~
- [x] Check whether we can use the same view model for the system and the custom players.
- [x] Check if FB11934227 is still an issue with the new updated implementation and remove the associated comment if not the case anymore.
- [x] Disable PiP button if a parent view is not enabled for PiP.
- [x] Check behavior with `preventsDisplaySleepDuringVideoPlayback`. Create story if needed.
- [x] ~Improve PiP lifecycle protocol:~
    - [x] ~Remove Boolean from completion (always pass `true` internally).~
    - [x] ~Think about an `async` variant instead if feasible / meaningful.~

**Comment by defagos** [comment]
@waliid discovered that the usual `AVPlayerViewController` full screen button is still present and interactive on `VideoPlayer`, though it can be seen. This is a bug we have to report to Apple. We can likely assume that the button should be visible since `VideoPlayer` should not differ much from wrapping `AVPlayerViewController` in a `UIViewControllerRepresentable`.

For this reason our `SystemVideoView` will be updated as follows:

- Replace `VideoPlayer` with a `UIViewControllerRepresentable` wrapping an `AVPlayerViewController`. This means the view will always display a button at the top left, either a full screen or a close button.
- Remove support for content overlays (not used yet anyway).
- Document our `VideoPlayer` view behavior as intentionally matching the one of `AVPlayerViewController`, that means:
    - Inline integration leads to a full screen button being displayed.
    - Full screen integration leads to a close button being displayed.

**Comment by defagos** [comment]
The approach of sharing `AVPlayerViewController` between view instances has a great advantage (same for `AVPlayerLayer` sharing we will do for the custom PiP integration with `AVPictureInPictureController` instead of `AVPlayerViewController`. No matter the views between which playback is moved through PiP, restoration will never kill the PiP overlay abruptly. The player layer will always move between maximized display and PiP overlay. This is a great improvement over what we had with Letterbox.

**Comment by defagos** [comment]
The system video view has two modes:

- Full screen display: In this case the player can only be closed. When used in apps (e.g. tv+) the player is dismissed when PiP is entered.
- Inline display: In this case the player has a maximization button. Starting PiP must not dismiss the player in this case, `AVPlayerViewController` only exits full screen while detaching the video overlay.

We should document these use cases. We should also document that the use case _start inline, maximize, move to PiP with dismissal_ is not supported. Dismissal is namely only intended for full screen use.

Our demos should also be updated to have both these use cases properly implemented.

**Comment by defagos** [comment]
FB11934227 is still an issue with the new implementation.

**Comment by defagos** [comment]
The screen is prevented from sleeping while playing in PiP. No further `preventsDisplaySleepDuringVideoPlayback` investigation needed yet.
