### ISSUE TITLE
Add basic PiP support to `VideoView` without restoration

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#611]
**As a developer integrating Pillarbox with a custom UI** I want to be able to enable basic PiP without restoration in an easy way. _Basic PiP_ means that no PiP button is provided for dismissal / restoration but that an application can still automatically enable PiP when sent to the background or when switching to another app.

**As a Pillarbox user** I want to be able to continue video playback even when leaving the app.

# Acceptance criteria

- Basic PiP support is provided by `VideoView` through an API which is simple to use.

# Tasks

- [x] Add internal singleton object to manage main PiP instance controller lifecycle.
- [x] Implement layer sharing between `VideoView` and PiP manager.
- [x] Ensure that basic PiP works well in the demo when the custom player layout is used.
- [x] Check that no resources are leaked.

**Comment by defagos** [comment]
As soon as a PiP controller is bound to a layer there are seek performance issues when a Bluetooth headset is connected.

This issue does not only affect Pillarbox and can be experienced with Letterbox as well. This is likely a system issue, even though it is better mitigated by Apple player UI somehow.

**Comment by defagos** [comment]
The performance issue has been reported as #622.

**Comment by defagos** [comment]
PiP is automatically merged back when returning to the app (active app state notification). There is a catch, though. If we switch to another app and back to the playing app fast, PiP won't be correctly merged. This is because the `AVPictureInPictureController.stopPictureInPicture()` method has no effect if the PiP is still starting.

We could listen to all PiP delegate events to save the current state and defer the stop request in such cases, but this is likely too much logic for something that could be considered a corner case. So for the moment I suggest we keep everything simple and do nothing.

I also considered reporting an API improvement to Apple so that stopping PiP during start effectively has an effect, but I doubt this request would be easy to defend (the PiP lifecycle is there to implement such behaviors after all).
