### ISSUE TITLE
Enhance PiP support for tvOS

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#613]
**As a Pillarbox user** I want to be able to use PiP on tvOS.

# Acceptance criteria

- PiP works in all relevant demos (custom player, playlist, multi-player).
- tvOS-specific swap works.

# Tasks

- [x] Ensure exiting PiP implementation works on tvOS.
- [x] Upgrade the implementation to support swap.
- [x] Check that no resources are leaked.

**Comment by defagos** [comment]
Apparently our work on #610 automatically provides correct PiP support for tvOS.

**Comment by defagos** [comment]
Works pretty well in the latest nightly with #628 merged.

**Comment by waliid** [comment]
I also ran some tests, and everything seems to be working quite well.

**Comment by waliid** [comment]
Before **closing** this task, I would like to **finish** and **test** the story related to [playlists](https://github.com/SRGSSR/pillarbox-apple/issues/618) on `tvOS`.

**Comment by defagos** [comment]
Since we aren't using the system UI for the playlist demo there is no PiP available, so I guess everything works as it should.
