### ISSUE TITLE
Document PiP integration

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#616]
**As a developer integrating Pillarbox** I want to know how I can integrate PiP in my app.

# Acceptance criteria

- Basic PiP integration (no PiP button, no dismissal / restoration) is documented.
- Advanced PiP integration (dismissal and restoration) is documented.

# Tasks

- [x] Add to feature list.
- [x] Document basic integration.
- [x] Document step-by-step advanced integration, e.g.:
    - Enable PiP support for view.
    - Add PiP button to the UI.
    - Share model associated with the view somehow.
    - Register corresponding cleanup closure.
    - Implement delegate in application routing management (app delegate, router, etc.).
    - Implement dismissal in will start method.
    - Implement restoration.
    - Handle same content playback in view model for an optimal result (avoid replacing).
- [x] Document the special case of the system UI (only advanced integration).
- [x] Document manual validation tests for basic integration:
    - [x] Send app to the background and return. Playback should resume full screen without interruption.
    - [x] Switch to another app, then to the app back again. Playback should resume full screen without interruption.
- [x] Document manual validation tests for advanced integration:
    - [x] Press on PiP button, then on the PiP overlay exit button. Playback should resume full screen without interruption.
    - [x] Press on PiP button, then tap on the same content again. Playback should resume full screen without interruption.
    - [x] Press on PiP button, then tap on another content. Playback should resume full screen with playback moving to the new content during the restoration animation.
    - [x] For system UI integration PiP, tapping on the PiP button after having maximized the UI (a feature only available if the player is initially not covering the whole screen) must continue in the PiP overlay without interruption.
    - [x] If several players implemented PiP in the same app, PiP playback that is initiated in a player must resume full screen with the same PiP overlay merged to the other player view.
- [x] ~Illustrate all the above use cases with videos.~
- [x] Document unsupported cases (e.g. continuous PiP experience between system and custom player views) and corner cases (e.g. starting PiP in custom player view and opening a system player view with PiP support; should the latter cancel PiP or not?).
- [x] Document system UI full-screen vs. non full-screen behaviors in the context of PiP (inline must not dismiss the view in PiP).
- [x] Add #622 to the list of known issues.

**Comment by defagos** [comment]
I have not added any videos yet. This is likely best done when we transition to DocC.
