### ISSUE TITLE
Fix playlist demo PiP support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#618]
**As a Pillarbox demo user** I want an uninterrupted PiP playback experience, also when using playlists examples.

# Acceptance criteria

- The advanced integration use cases mentioned in #616 all work with the playlist examples.

# Tasks

- [x] Introduce a shared playlist view model as for the `PlayerView`. See what was done in #610 for the `PlayerView`.
- [x] Update routing for correct dismissal and restoration.
- [x] Validate all advanced integration use cases.

**Comment by waliid** [comment]
# Issue with `WillAppearView`

To effectively manage the Picture in Picture life cycle, we introduced `WillAppearView`. 
This view is placed in the background of the view that calls the `onWillAppear` modifier. 
However, this modifier call, results in unexpected behavior.

Here is the piece of code responsible for the issue:

```swift
func onWillAppear(perform action: @escaping () -> Void) -> some View {
    background {
        WillAppearView(action: action)
            .background(Color.cyan)
    }
}
```


![Image](https://github.com/SRGSSR/pillarbox-apple/assets/3347810/b6366f72-41a4-4a97-9952-04b6913b36f3)


The unexpected behavior arises because the button actions are not triggered as expected, likely due to issues with the responder chain. When a button is pressed, the view captures the event, preventing the button action from being triggered.

**Comment by waliid** [comment]
## Workaround

Adding a background for the `Toolbar`. However, a notable drawback with this workaround is that it needs to be implemented on the client side.

**Comment by defagos** [comment]
Not seing any undefined behavior here, or at least the behavior seems pretty much well defined to me (the background modifier applies to the parent frame, so if you apply the will appear modifier to the whole playlist view it is normal you see it though when applying a color).

So, what do you mean by _undefined_ in this case?

**Comment by waliid** [comment]
How do you explain that without modifying the background (without adding WillAppearView), the playlist buttons remain usable? 
As soon as we add WillAppearView as the background, the buttons remain usable but less conveniently.

I don't know if the interaction on the view controller view should be disabled or if the toolbar should have a background color. 🤷‍♂️

**Comment by waliid** [comment]
I used this [trick](https://www.hackingwithswift.com/quick-start/swiftui/how-to-control-the-tappable-area-of-a-view-using-contentshape) for the moment.

**Comment by defagos** [comment]
I tested briefly but did not notice that buttons were less usable. I understand.

Some mitigation ideas that might avoid client-side fixes:

- Set `allowsHitTesting(false)` like we do for tracked views.
- Use a background but set `ViewWillAppear` view frame to 1px ⨉ 1px (even 0px ⨉ 0px but I doubt this would work).
