### ISSUE TITLE
Improve menu buttons

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#619]
**As a user** I want to have a similar experience to the system one when developers have integrated standard Pillarbox menus.

Starting with iOS 17.2 the menu is expanded or collapsed depending on some criteria. For example all options are unrolled when the player is displayed in landscape orientation.

# Acceptance criteria

- The menu button provided by Pillarbox has identical behavior to the one in the system player UI, as seen on iOS 17.2. 

# Tasks
 
- [ ] Identify how button visibility / collapse to a single more button is handled by the system player.
- [ ] Identify which buttons are available in all cases (e.g. there is a new back to lve button for livestreams).
- [ ] Expand or collapse icons depending on setting availability.
