### ISSUE TITLE
Improve UT reliability

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#62]
**As a developer** I want unit tests to be as reliable as possible. Multiple seek tests in particular are not that reliable:

```
DequeuePlayerNotificationTests.testMultipleSeeksWithCompletionHandlerDuringPlayback
DequeuePlayerNotificationTests.testMultipleSeeksAsyncDuringPlayback
```

# Acceptance criteria

- Unit test suites run reliably for iOS and tvOS.

# Tasks

- [x] Locally run the tests repeatedly with Xcode repeat feature.
- [x] Check CI Xcode version used. Upgrade if not the latest Xcode 14 beta.
- [x] Attempt to improve the UT implementation.
- [x] ~Otherwise increase the number of retries with a test plan.~

**Comment by defagos** [comment]
Test run locally fine with excellent reliability (no single failure in 100 repetitions).

**Comment by defagos** [comment]
Upgrading our CI to Xcode 14 beta 6 didn't change anything.

Since the failing UTs really are not testing anything except `AVPlayer` behavior in presence of multiple seeks, I deleted the entire unit test suite instead of creating a test plan to retry flaky tests.
