### ISSUE TITLE
Hide controls when animating in and out of PiP

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#626]
**As a user** I want a nice experience when animating in and out of PiP.

# Acceptance criteria

- Controls are hidden when transitioning from / to PiP.

# Tasks

- [ ] Publish state from `PictureInPicture`.
- [ ] Hide UI in demos implementing PiP when transitioning.
- [ ] Avoid showing controls when returning from PiP.
- [ ] Return `isPossible` as `false` when transitioning out of PiP? (would avoid button flickering)

**Comment by defagos** [comment]
Not really relevant anymore. Apps can use our `PictureInPictureButton` which uses these states internally. No need to hide controls during animation as well since we could implement very fast transitions in and out of PiP.
