### ISSUE TITLE
Add basic demo for stories and multiplayer

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#67]
**As a developer** I need to be able to identify pain points early, especially regarding performance. Having demos for a story-like integration and for simultaneous playback would be valuable.

# Acceptance criteria

- A basic demo for stories is available.
- A basic multiplayer demo is available.
- Demos to connect a player to a view are available.

# Tasks

- [x] Add story demo.
- [x] Add demo in which a player can be attached or detached from a view.
- [x] Add demo in which a player can be instantiated and attached to a view, or nilled.
- [x] Add multiplayer demo (different contents).
- [x] Add multiplayer demo (same content but displayed in view A, B or A & B).

**Comment by defagos** [comment]
`TabView` with the `.page` style may preload additional tabs, especially when loaded for the first time or when changing the swipe direction. So using appearance methods to play / pause playback is not an option.

**Comment by defagos** [comment]
Interestingly, having a view take the `Player` as input and keeping a reference to it (e.g. `VideoView` or `Slider`) prevents the player from being deallocated early. We can see remaining stream activity as we scroll through stories fast, whereas we would only expect a few streams to be active at any time. This needs to be understood and fixed.
