### ISSUE TITLE
Handle buffering and seeking states

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#68]
**As a user** I want the player to see when the player is seeking or buffering.

# Acceptance criteria

- Seeking and buffering states are supported.
- The player displays a basic spinning wheel when in these states.

# Tasks

- [x] Carefully study buffering-related APIs.
- [x] Add seeking and buffering states (might be the same).
- [x] Check behavior after network loss or when returning from background.
- [x] Add basic UI in demo.
- [x] Add empty player demo.
- [x] Add failure demo.
- [x] Ensure correct behavior for the empty and failure cases (write tests first).
- [x] ~Implement basic HTTP error management (must avoid exceptions thrown in this case when getting the media composition).~
- [x] ~Write unit tests for seek behaviors at the player `state` level ([omitted](https://github.com/SRGSSR/pillarbox-apple/pull/66) when implementing these behaviors in the first place).~

**Comment by defagos** [comment]
There are three item properties related to buffering:

- `isPlaybackLikelyToKeepUp`.
- `isPlaybackBufferEmpty`.
- `isPlaybackBufferFull`.

Of these three properties only the first seems to be required for proper buffering detection. I exposed the other ones for the player (as we must follow item changes) and we'll see whether this yields the desired behavior.

Unlike what we did with Letterbox, I think we should embrace `AVPlayer` behavior and treat buffering as a state separate from the playback state, so that we can be paused and buffering or playing and buffering, for example. This avoids blending these two states and losing information in the process.

Moreover initial loading and seeking report buffering in the same way. I therefore think there is no need for a seeking state either.

**Comment by defagos** [comment]
I tested the new buffering state but, as it is separate from the main player item state (or playback state) no other seek-related tests will be written (to address one of the tasks listed in this issue).

**Comment by defagos** [comment]
I improved test helpers to check for publisher success or failure. Media composition retrieval errors are not properly extracted yet (we should extract 404 earlier instead of a parsing error) but the pipeline still fails, so the current implementation suffices. We'll improve it anyway when working on error management.

**Comment by defagos** [comment]
Behavior with network loss is correct (player is stuck buffering) and so is behavior when returning from background.
