### ISSUE TITLE
Improve monoscopic 360° navigation

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#704]
**As a Pillarbox demo user** I would like to be able to navigate 360° content using inertia: I should be able to swipe the screen and lift my finger with the orientation still changing for a while, in an animated way.

**As a developer integrating Pillarbox** I want to be able to implement animated experiences like this one, or interfaces where I can change the orientation with 90° increments in orthogonal directions, e.g., with an animation between these fixed positions.

# Acceptance criteria

- Inertia has been added to the demo monoscopic 360° navigation.

# Tasks

- [ ] Investigate how this can be implemented (fully client-side? Synchronized animation required from SceneKit code?).
- [ ] Implement in demo.
- [ ] Add button to reset orientation to the default value with an animation.

**Comment by defagos** [comment]
Here are a few rough ideas, without a clue if they lead anywhere:

# Extrapolated position

To get the position with inertia we can likely use drag gesture predicted information:

```swift
.onEnded { value in
    translation = CGSize(
        width: initialTranslation.width + value.predictedEndTranslation.width,
        height: initialTranslation.height + value.predictedEndTranslation.height
    )
    initialTranslation = translation
}
```

# Animation

The animation must likely be applied in the SwiftUI code when the `orientation` changes (in our demo code the `translation`). Maybe a bridge needs to be made with our monoscopic view representable. Some hints:

- [Animating SceneKit content](https://developer.apple.com/documentation/scenekit/animation/animating_scenekit_content).
- SwiftUI animation properties can be [read](https://github.com/rcarver/swift-matched-animation). This could maybe be useful to use the same settings for a SceneKit animation, if needed.
