### ISSUE TITLE
Provide demo test and sample streams with constants

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#71]
**As a developer** I want to have consistent demo and test streams which I can easily update in a single spot if needed.

# Acceptance criteria

- Demo and test streams are available through constants.

# Tasks

- [x] Introduce constants for demo and test streams.
- [x] Update demo and test to use these streams.
- [x] Maybe introduce constants for the duration of streams (e.g. 120 seconds) which can be consistently updated as well.
