### ISSUE TITLE
Force simulator language for UTs

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#757]
**As a Pillarbox developer** I need tests to run reliably on CI agents so that I can work efficiently.

# Acceptance criteria

- Tests run successfully for iOS and tvOS on all CI agents.

# Hints

Tests involving subtitles currently fail on the RIO Mac mini M1, probably because of the simulator language used. We should force it to English.

# Tasks

- [x] Force simulator language.
- [ ] Successfully run iOS tests on all CI agents.
- [ ] Successfully run tvOS tests on all CI agents.
