### ISSUE TITLE
Backward playlist navigation

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#76]
**As a user** I want to be able to move to the next item in a playlist, but also to move back to previous items.

# Acceptance criteria

- The API has been updated to support navigation to a previous item in a playlist.
- The demo provides a basic playlist example with forward / backward navigation.

# Tasks

- [x] Check behavior when playback of the last item ends normally. Is the current item turned to `nil`? Can we prevent it? (see issue below)
- [x] Add `canAdvanceToNextItem` and `canReturnToPreviousItem` APIs? Possible? (depends on answer above).
- [x] Implement better thread-safety (`@MainActor` only checks overridden or subclass methods). Avoid subclass and use composition  for the deque. Expose the raw player since we don't want to forward every method and we still need to do KVO on the player. Alternative: Have `Player` play this role and rename `DequePlayer` as `RawPlayer`, which will only deal with seeking (still required for consistent behavior since seeking can be triggered by the system). Think whether `@MainActor` should be replaced with a manually managed serial queue instead for the reasons mentioned above.
- [x] Update main player API accordingly (expose playlist management methods).
- [x] Update demo.
- [x] ~Reset started playlist items at the beginning when navigating away? (opt-out?)~ _See comments below_
- [x] Create player item constructor for dummy items by name, replacing e.g. `AVPlayerItem(url: URL(string: "https://www.server.com/item1.m3u8")!)` with `AVPlayerItem(name: "item1")`.
- [x] Have inserts and moves return a bool.
- [x] Check documentation generation.
- [x] Make slider not draggable (i.e. progress not updatable) when `currentItem` is `nil`.
- [x] ~Add API for `AVPlayerActionAtItemEnd`.~ _Premature, see comments below_
- [x] Check backwards navigation works in background (probably required: Insert previous item after current one and advance).
- [x] Fix demo issue with URN resource loading which does not work correctly, leading to an incorrect behavior (demo works fine with URLs, though).
- [x] ~Fix race conditions with `propertyPublisher` reported after the playlist API has been moved to `Player`.~ _See comments below_
- [x] ~When a resource loader is used for items in a playlist, all items apparently have to be retrieved before playback of the first item can start. This must be mitigated if possible (maybe a shared resource loader is the key, since we currently have one per item).~ Opened as #81 since probably a combination of item storage for playlist backward navigation and incorrect resource loadind.
- [x] Check memory profile and network activity when navigating in the playlist.

**Comment by defagos** [comment]
I had to remove the [leak fix introduced for the simulator](https://github.com/SRGSSR/pillarbox-apple/pull/53) as the `removeAllItems()` method on `DequeuePlayer`, marked as `@MainActor` and which must be overridden to implement the dequeue, cannot be called from `deinit` as it is [non-isolated](https://forums.swift.org/t/deinit-and-mainactor/50132/5).

The leak only affects our MP4 example in the simulator anyway.

**Comment by defagos** [comment]
There is a [bug](https://stackoverflow.com/questions/73199596/xcode-14-beta-4-warnings-about-unused-return-values-even-when-using-discardab) in Xcode 14 leading to unused return value warnings for types on the `@MainActor`, even when `@discardableResult` is used.

**Comment by defagos** [comment]
The resource loader issue seems to be fixed when running on iOS 16.1. If this is confirmed this means the minimum deployment target should be set to 16.1.

**Comment by defagos** [comment]
The behavior at the end of playback, whether we have a single item or several, is to set the `currentItem` back to `nil`. This can likely be controlled with `AVPlayerActionAtItemEnd`.

**Comment by defagos** [comment]
No additional checks are performed for `RawPlayer` `seekCount` mutation. `AVPlayer` should be used from the main thread anyway, so there is no need to implement thread-safe calls to the seek method anyway (and thus to the `seekCount` property).

**Comment by defagos** [comment]
`AVPlayerActionAtItemEnd` is very interesting and works well:

- `.advance` is the current behavior without any kind of setup. Items in the playlist are automatically chained. After the last item has been played the player current item becomes `nil`. Videos displayed in an attached layer disappear and seeking back into the content is not possible anymore.
- `.pause` pauses playback at the end of the current item. Moving to the next item does not restore the rate to its previous value, which makes sense. The item does not become `nil`, of course, therefore videos remain displayed in an attached layer and seeking back into the content remains possible.
- `.none` does nothing at the end. Playback stays paused and the item is preserved. Videos remain displayed in an attached layer and seeking back into the content remains possible. This is how `AVPlayer` behaves (though `actionAtItemEnd` itself can only be used with `AVQueuePlayer`).

Using `AVPlayerActionAtItemEnd` to control playlist behavior is the way to go as it provides everything we need, but implementing anything at this stage is premature. We namely need to understand the experience we want to achieve and what flexibility we want to provide at the API level. We also likely need to understand how item chaining works with tvOS continuous playback support.

Note that Letterbox currently uses `AVPlayer` and thus behaves like `.none` when ending playback. We also implemented item chaining ourselves but we now know this was a bad idea. Still, is the current Letterbox playlist behavior something we still want to have as default (i.e. we would set `actionAtItemEnd` to `.advance` for all items in the playlist, except for the last one set to `.none`)? Or do we want to avoid forcing any kind of rigid behavior and let users choose what they want with a dedicated API (or directly with `actionAtItemEnd`)?

For all these reasons I crossed the `AVPlayerActionAtItemEnd` item off the todo list attached to this issue, but what is sure is that this is the API to use. We must not manage item chaining manually anymore as we did in Letterbox, but we must first agree on what we want to achieve.

**Comment by defagos** [comment]
I won't implement any item restart when returning to partially played items. Items bear their current time so this is likely expected behavior, and implementing a behavior might be restrictive (e.g. we might want to an other item at a specific time, see ExoPlayer behaviors described above). Either an explicit API is required or clients can decide and seek themselves, but for the moment behaviors have not been discussed. So implementing some behavior is premature for the time being.

**Comment by defagos** [comment]
I tested that playlist navigation works in background. Since integrating control center buttons is out of scope (and having a partial buggy integration in the demo would be misleading), I simply enabled background audio and added two audio URNs to the demo playlist. Then:

- I tested that `advanceToNextItem()` works in the background (fired with a timer after a while).
- That the same is true for `returnToPreviousItem()`.

This is not so surprising since the application is still active in the background. The real issue with Letterbox occurs at the end of playback but this is something that is automatically addressed in Pillarbox thanks to the use of `AVQueuePlayer`.

**Comment by defagos** [comment]
A remark about states (as can be seen with Timelane): The player stays in the playing state when transitioning between items. This is different from Letterbox but is correct from a player point of view. Transition between items (e.g. for analytics purposes) can still be detected, e.g. through `currentItem` transitions. For the moment we can keep this behavior as expected, and revise it at a later time if we need more intermediate states to be emitted when transitioning between items.

**Comment by defagos** [comment]
Regarding network activity, short playlist items might be buffered in advance, i.e. more than the master playlists is fetched. This is handled by `AVQueuePlayer`.

I discovered that, if a resource loader is used, playback does not start until all master playlists have been retrieved, which negatively scales as the number of items in the playlist is increased. This explains why the playlist example I added is slow to start. I will add an item to fix this issue if possible in the issue task list.

**Comment by defagos** [comment]
Interesting findings by adding a delay in the resource loader media composition pipeline:

- Setting `automaticallyLoadedAssetKeys` to `["playable"]` for items with a resource loader helps the queue player start playback earlier.
- With this configuration dismissing the player after playback has started but not all resources have been loaded (visible with Charles e.g.) there is a leak.

I guess that our resource loader implementation is currently not optimal.

**Comment by defagos** [comment]
The resource loading issues above, rising if we want to improve playlist playback startup time, are likely related both to how a resource loader must be implemented and to the fact we redundantly store items in a deque. This requires further investigation and a small PoC to better see what happens and find a solution.

Until then I avoided setting `automaticallyLoadedAssetKeys`. This adds playback start overhead but avoids leaks. I opened #81 for further investigation.
