### ISSUE TITLE
Improve Control Center display in presence of errors

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#767]
**As a user** I want the Control Center to display relevant information (and still be usable) when errors are encountered.

# Acceptance criteria

- The Control Center displays metadata for failed items (URL-based).
- The Control Center displays metadata for failed items (URN-based).
- The user can navigate forward and backward, even on failed items.
- In presence of an error populate the Control Center to ensure the user does not leave the app and can navigate forward or backward in a playlist.
- In presence of an error display the metadata we have (e.g. title and artwork if available) as well as _Error: message_ on one Control Center text line (probably the 2nd). If we don't have any title we just display the error text.
- Have the play button remain active and perform a retry.

# Tasks

- [x] Always deliver Control Center metadata, never return `nil` from the [associated method](https://github.com/SRGSSR/pillarbox-apple/blob/main/Sources/Player/Asset.swift#L152-L166), and provide at least one key, even if empty. This prevents failing items in playlists from displaying metadata from the previous playable item in the Control Center.
- [x] Make `propertiesPublisher` and `itemUpdatePublisher` deliver their current value on subscription by using `share(replay:)` from CombineExt. This will be removed ASAP by #773 with no API change.
- [x] Replace `currentPublisher()` with this shared publisher. Remove `Current`.
- [x] Rewrite `itemUpdatePublisher` so that it merges update streams, either from stored items or from item transitions (similar to what `queueItemsPublisher()` does).
- [x] Replace `$storedItem` with this shared publisher. Remove `smoothCurrentItemPublisher()`.
- [x] ~Check if we could get rid of the `@Published` asset property, replacing it with an `assetPublisher()` to avoid misuse (e.g. accessing the non-updated `asset` property vs. getting published changes before the object itself is updated).~
- [x] Rename `Player+Current.swift` to something more appropriate or move the code.
- [x] Take into account asset errors in Control Center metadata.
- [x] Take into account item errors (as fallback if no asset error is found) in Control Center metadata.
- [x] Fix incorrect analytics events sent when moving the item currently being played.
- [x] Tweak button availability in the Control Center when an error is reported:
    - [x] Make skip buttons (possibly slider interactions) unavailable when an error is reported.
    - [x] Implement play button retry in case of failure.
- [x] Fix playlist navigation issue after `stop(on:)` has been received. In such cases we should not add items after the stopped item, otherwise the `AVQueuePlayer` will skip the failed item and play them. This can be reproduced in playlist demos as follows:
    - Have a playabable item, followed by an invalid MP3, followed by another item.
    - While playing the 1st item, tap on the invalid MP3. Playback incorrectly continues with the 3rd item, while the error for the 2nd item is still visible.
- [x] ~Format error messages as _Error: Message_.~
- [x] Remove error publisher if possible. Since we now can know when playback is stopped on a failed item (`itemTransition`), we can likely make error management a bit simpler.
- [x] Update `removeAll(from:)` to remove items in reverse (otherwise "from 0" leads to current index changes).
- [x] Check that all use cases work:
    - [x] Single playable items (M3U, MP3).
    - [x] Failing items.
    - [x] Recovery of playable items after network error (M3U, MP3).
    - [x] Playlists with playable items.
    - [x] Playlists with failed items (M3U, MP3).
- [x] Check network activity, leaks and UI refreshes.
- [x] Check analytics.

**Comment by defagos** [comment]
As discussed with the team:

- In presence of an error we still populate the control center to ensure the user does not leave the app and can navigate forward or backward in a playlist.
- In presence of an error we display the metadata we have (e.g. title and artwork if available) as well as _Error: message_ on one control center text line (probably the 2nd). If we don't have any title we just display the error text.
- The play button remains active and performs a retry.

**Comment by defagos** [comment]
We have found an issue with analytics in playlists. When the current item is moved we currently (and incorrectly) trigger an update because of `Current` being changed (the item does not change but its index changes), which is incorrect.

We likely should drop `currentPublisher` and `Current` in favor of the very similar `itemUpdatePublisher` but this raises challenges we recently encountered with asset delivery ordering, possibly related to incorrect use of `multicast` in the associated publisher implementation, usually associated with URL-based items delivering `Just` the URL immediately.

This requires further investigations. Probably:

1. Solve the ordering issue by careful analysis of how `multicast` works and appropriate fixes if neded. Ensure all tests pass and that URL and URN-based examples all play fine.
2. Drop `currentPublisher` in favor of `itemUpdatePublisher` and ensure all tests pass and that URL and URN-based examples all play fine.
3. Fix the Control Center issue. We should likely derive asset and error delivery from `itemUpdatePublisher` delivered `PlayerItem` and `AVPlayerItem`, combining them to obtain the result we desire

**Comment by defagos** [comment]
A remark: The `MPNowPlayingSession` is associated with one or more players. If these players do not play for some reason the Control Center might not display metadata, even if we fill it correctly. This means that some examples like the _Unauthorized URL_ might sometimes display an error in the Control Center, sometimes no metadata at all.

**Comment by defagos** [comment]
When revisiting our error management we stumbled upon an issue affecting MP3 playback after an MP3 failed to play. When attempting to replace the failed MP3 with another playable MP3 no sound plays. We had to introduce some cleanup of the player queue first to avoid this issue.

This issue has been reported to Apple as _AVPlayer MP3 playback issue: Replacing an MP3 with another one after playback failure does not work correctly_ under FB13650115.
