### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#776]
**As a user** I want all strings to be properly localized.

# Acceptance criteria

- All strings are localized in all SRG SSR official languages.

# Tasks

- [x] Create project on CrowdIn.
- [x] Attach comments and screenshots.
- [x] Send translation requests to translators.
- [x] Fix broken playback error reporting introduced in #780 (error message not displayed anymore after playback failed, e.g. after a seek to an unbuffered location without network available).
- [x] Fix error message translation issues. Most notably, when no network is available, URN and URL examples do not return the same message (for URL examples the message is not localized). This is due to the error log being checked before the item error. Just checking the item error first does not work, we probably have to be more careful (maybe only check the error log when the main item error suggests it).
- [x] Check behavior on iOS 16.
