### ISSUE TITLE
Replace Tag Commander SDK with V5

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#78]
**As a developer** I need to check that the Tag Commander V5 SDK can be integrated with our player ecosystems. Integration in Pillarbox is enough to give an answer.

# Acceptance criteria

- The [Tag Commander V5 SDK](https://github.com/CommandersAct/iosv5) is integrated in Pillarbox (Core 5.1.1, ServerSide 5.1.2). This SDK includes support for tvOS.
- iOS and tvOS demos build and run successfully.
- iOS and tvOS demos can be distributed via TestFlight.

# Tasks

- [x] Package the new SDKs with SPM (new repositories probably). Package both SDKs with a single manifest and repository if possible.
- [x] Integrate in package manifest.
- [x] Briefly test calling the API from the code (no commit).
- [x] Report to Tag Commander team.
- [x] Demos can be successfully built and distributed via TestFlight.

**Comment by defagos** [comment]
We cannot use a single repository or manifest because the SDKs have separate version numbers.

**Comment by defagos** [comment]
I distributed TCCore with our existing internal repository and updated the documentation accordingly (@pyby for info). I created a [new repository](https://github.com/SRGSSR/commanders-act-apple/settings/delete) for TCServerSide which replaces TCSDK.

I updated the packaging documentation accordingly, as the zipped XFramework files can now be retrieved directly from Tag Commander.

**Comment by defagos** [comment]
I made a basic server-side implementation with a single dummy event sent. The application links and archives correctly and I can see network activity with Charles. Platform information sent in network requests is correct.
