### ISSUE TITLE
Set minimum version to 16.1

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#79]
**Don't do if #81 solves issues on iOS 16.0, as this would not be required.**

Also see #76.

# Tasks

- [x] ~Update in package manifest.~
- [x] ~Update Fastfile to use Xcode 14.1.~
- [x] ~Update in demo.~
- [x] ~Update documentation.~

**Comment by defagos** [comment]
#81 solves issues related to itself, but not related to 16.0. I am pretty confident this was an iOS 16.0 bug which is fixed in 16.1, so we need to keep this task and do it once the update has been released.

**Comment by defagos** [comment]
The issue was on our side, likely because we were replacing the current item somehow. Fixed in #106, no need to move to 16.1.

**Comment by defagos** [comment]
There is stil an issue with iOS 16.0 which does not appear in iOS 16.1. If we preserve the item current position while navigating the items, the player will struggle to restore the position:

1. Open the playlist example.
2. Move to the 2nd item and play for a while.
3. Return to the 1st item and play it through.
4. The player struggles to restore the position in the 2nd item.

This requires further investigation but for this reason we must reopen and consider the move to 16.1 again.

**Comment by defagos** [comment]
The struggling issue is not related to iOS 16.1. I have issues on some devices but not on other ones. I will open a dedicated issue and close the present one.
