### ISSUE TITLE
Update type erasure implementation in metadata PoC

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#807]
**As a developer** I must prepare our current implementation to better support custom metadata recipes in the future.

# Acceptance criteria

- Type erasure is minimal.
- The code works as before. All tests pass.

# Tasks

- [x] Recover PoC implementation from #804.
- [x] Recover valuable API improvements from derived PoC branches.
- [x] Implement minimal type erasure as can be seen in sample project associated with #804.
- [x] Improve naming scheme, e.g. `PlayerMetadata -> PlayerItemMetadata` and `Player.Metadata -> PlayerMetadata`.
