### ISSUE TITLE
Fix resource loading conflicts with playlist management

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#81]
**As a user** I want a good user experience with any kind of content.

# Acceptance criteria

- Playback starts fast.
- Playback never unexpectedly continues in background after closing the player.

# Hints

A custom resource loader was implemented in #60 to load content from URNs and deque playlist support was added with #76. When combined these two features show several issues:

- On iOS 16.0 navigating back does not work (navigation is made forward). This works on iOS 16.1 but maybe this is not an actual iOS issue but rather an artefact of our implementation, leading to unreliable behavior.
- When adding some delay to the media composition pipeline (e.g. 4 seconds) playback only starts when resource loading requests for all items in the playlist have been made. Loading the item from an asset with `automaticallyLoadedAssetKeys` set to `["playable"]` makes the player start early but, if the player is closed while some items are still not loaded, the player leaks (sound continues in the background). This last issue disappears if we avoid storing items redundantly in `storedItems` so there might be something else at play here as well.

Remarks:

- We could share resource loaders among items (lazy instantiation and reuse, per environment).
- Resource loading cancellation is not called often it seems.
- The issue seems similar to the leaks we sometimes experience with Letterbox after closing the player. Letterbox also stores the item internally and has a resource loader working in a similar way so we might find a way to improve Letterbox at the same time.

# Tasks

Probably better investigated in a project implemented from scratch. An idea:

- [ ] Create app with simple modal player powered by `AVQueuePlayer`.
- [ ] Implement resource loader which delivers `https://url/to/playlist.m3u8` urls as `custom://url/to/playlist.m3u8`, just replacing the scheme with a large delay.
- [ ] Check the behavior on iOS 16.0 and 16.1.
- [ ] Check what happens when the items are redundantly stored in a list next to the player.

The rest of the tasks will probably follow from this initial investigation:

- [ ] ...

**Comment by defagos** [comment]
Some learnings and checks:

- Cancelling delayed publishers works as expected and does not lead to _dangling_ publishers, so the approach applied to simulate slow requests is not responsible of creating the reported issue.
- As [documented](https://developer.apple.com/documentation/avfoundation/avasset/1388722-cancelloading) `AVAsset.cancelLoading()` does not cancel resource loading but only asynchronous property loading.
- The fact that playback takes more time to start when using `AVPlayerItem.init(asset:)` is to be expected, as the [default behavior[([automaticallyLoadedAssetKeys](https://developer.apple.com/documentation/avfoundation/avplayeritem/1588087-playeritemwithasset)) without `automaticallyLoadedAssetKeys` parameter is to wait until the duration is known. Using `AVPlayerItem.init(asset:automaticallyLoadedAssetKeys:)` with better parameters (or none) is therefore key to ensure fast startup.

**Comment by defagos** [comment]
SRG Media Player already calls `-[AVAsset cancelLoading]` so no improvement PR can be made. Remaining issues in Letterbox likely have another cause.

**Comment by defagos** [comment]
I doubt `AVAssetResourceLoadingContentInformationRequest` can be [filled](https://developer.apple.com/documentation/avfoundation/avassetresourceloadingcontentinformationrequest) in a meaningful way, as we are not getting media data, rather only the playlist (provided as a redirect).

**Comment by defagos** [comment]
Tests work fine if we load items without `automaticallyLoadedAssetKeys` (checked with a global find & replace; won't be tested automatically since would add only noise).
