### ISSUE TITLE
Document metadata integration

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#819]
**As a developer integrating Pillarbox** I need helpful documentation showing me how I can integrated metadata with my custom player user interface, or with the standard player user interface.

# Acceptance criteria

- Metadata mapping protocol implementation and adapter are documented.
- Metadata integration with custom and system player UIs is documented.
- Now playing information customization is documented.

# Hints

Maybe a diagram of Pillarbox customization (data source, resource loading, analytics, UI) could be useful at this point.

# Tasks

- [x] Document protocol implementation and adapter usage.
- [x] Document metadata integration with player UIs.
- [x] Fix or update existing tutorial.
