### ISSUE TITLE
Build a `UIMenu` for chapters

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#824]
**As a user** I would like to be able to navigate chapters with a lightweight user experience similar to Quick Time on macOS. **As a developer** I would like to have a quick way to integrate chapter navigation in any user interface.

# Acceptance criteria

- A `UIMenu` is provided to automatically display chapters associated with a content, if any.
- The menu displays titles and associated thumbnails (if possible).
- The menu is integrated in `SystemVideoView`.

# Tasks

- [ ] Investigate if displaying an image is possible with a `UIMenu`.
- [ ] Implement the menu.
- [ ] Integrate in the standard menu (if chapters are available).
- [ ] Integrate in `SystemVideoView`.

**Comment by waliid** [comment]
We have tried using a `Menu` but the render is not really conclusive, hence we have decided to close this issue.

Here are our results:

| iOS | MacOS |
|--------|--------|
| ![iOS](https://github.com/SRGSSR/pillarbox-apple/assets/3347810/67063cac-93c8-4831-8ed6-90eb3cc010b6) | <img width="1241" alt="macOS" src="https://github.com/SRGSSR/pillarbox-apple/assets/3347810/c7f9f0f8-54b9-4bc7-ba16-5e12754e349f"> |
