### ISSUE TITLE
Content proposal support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#843]
**As a tvOS user** I would like to have a nice continuous playback experience between items in a playlist.

# Acceptance criteria

- A content proposal can be offered during closing credits.
- The content proposal UI can be customized with SwiftUI.
- The demo implements a content proposal experience on tvOS. For SRG SSR content providing closing credits information the proposal is made during the credits, otherwise at the end of playback.

# Hints

- [Official documentation](https://developer.apple.com/documentation/avkit/presenting_content_proposals_in_tvos).
- Successfully tested on `845/credits-support-investigation`. What is required:
     - Adding next content proposal to items (possible based on item metadata when recreating player items during queue player queue sync).
     - Creating a content proposal view controller.
     - Attaching an `AVPlayerViewDelegate` to manage content proposal display.
     - (not checked but likely) Calling `advanceToNext` when approving the content proposal.

# Tasks

- [x] Attach next content proposals to items.
- [ ] Add API to let users customize content proposal presentation.
- [x] Update playlist player on tvOS to just display the full-screen system UI.
- [ ] Implement content proposal layout in demo.

**Comment by defagos** [comment]
We implemented this feature partially but realized it is probably too half-baked for our needs:

- The content proposal API must be applied on the current item, mixing metadata from the next content.
- Some presentation information (e.g. acceptance delay) are really UI-related but defined on `AVPlayerItem`.
- The player desired frame lives in a UIKit world, making it difficult to interface with custom SwiftUI interfaces (except with hardcoded layouts).
- The accept / reject behavior is half-baked and inconsistent (delegate calls, some of it also available on content proposal view controllers).

**Comment by defagos** [comment]
We should have a look at this feature again, with tvOS 26 and recent changes made to our implementation. Maybe something is now possible or meaningful that wasn't before.
