### ISSUE TITLE
Support opening and end credits

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#845]
**As a user** I want to be able to skip opening credits. I might also want to later have a content proposal during the end credits.

# Acceptance criteria

- The opening and end credits are supported.
- Media composition opening and end credits are mapped correctly.
- The tvOS system player UX provides a button to skip opening credits.
- The custom iOS player UX provides a button to skip opening credits.
- The iOS system player UX provides a button to skip opening credits if possible.

# Tasks

- [x] Implement support in player metadata.
- [x] Add opening credits skip button to the tvOS system player UX.
- [x] Add opening credits skip button to the custom iOS player UX.
- [x] ~Add opening credits skip button to the iOS system player UX if possible.~
- [x] Implement time range API which to avoid `timeRange.timeRange` access.
- [x] Add manually crafted example with opening and closing credits to the demo.

**Comment by defagos** [comment]
If naively following the [official documentation](https://developer.apple.com/documentation/avkit/customizing_the_tvos_playback_experience#3820232) and periodically updating `contextualActions` associated with an `AVPlayerViewController`, the button flickers.

To avoid flickering it suffices to provide a stable identifier with each `UIAction`. This way the player view controller can detect if there is a change or not.

In our case, and even if this might not cover all cases, we will use the title as identifier. This will not cover cases where buttons associated with consecutive time ranges offer the same label but a different handler, but such cases are rather unlikely to happen (and if they happen we will figure out another approach).

**Comment by defagos** [comment]
There is no contextual action support for the `AVPlayerViewController` on iOS. We will therefore mark the API as available on tvOS only and update it if Apple later extends it to iOS as well. We could have introduced a button ourselves but this would have been fragile.
