### ISSUE TITLE
Document metadata integration

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#849]
**As a developer integrating Pillarbox** I need documentation about metadata integration in my app.

# Acceptance criteria

Metadata integration is explained in the documentation. Most notably:

- How to use metadata when crafting user interfaces.
- How to associate chapters with content being played.
- How to associated blocked / credits time ranges with content being played.

# Tasks

- [ ] Document how metadata is delivered.
- [ ] Document how user interfaces can display metadata.
- [ ] Document chapter support.
- [ ] Document blocked and credits time ranges.
- [ ] Document tvOS system UI behaviors.
