### ISSUE TITLE
Handle blocked time ranges

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#851]
**As an editor** I want content that must not be available (e.g. legal, commercial or geoblocking reason) not to be playable (skipped). **As a user** I still want to be able to play content containing blocked time ranges.

# Acceptance criteria

- Content that is blocked for a reason (legal, commercial, geoblocking, etc.) cannot be played / seen.
- Content that is partially blocked can be played where not blocked.
- Nested blocked ranges are supported.

# Tasks

- [x] Skip over blocked time ranges during playback.
- [x] Prevent seeks into blocked intervals early.
- [x] Prevent from starting at a blocked position.
- [x] Add manually crafted example with blocked intervals to the demo.
- [x] Parse blocked segment in IL metadata.
- [x] Set blocked time ranges as interstitials.
- [x] Check corner cases (e.g. blocked range starting at zero).

**Comment by defagos** [comment]
tvOS interstitials cannot be nested (otherwise the behavior is erratic). Possibly nested time ranges have to be flattened first.

**Comment by defagos** [comment]
There is a minor issue with some content with blocked time ranges at the very end (e.g. Ramdam `urn:rts:video:13041988`). In this case the progress is stuck at 1 after replaying the content.

This is due to issues with the low-level seek not completing with `finished` set to `true`, an issue already encountered in the past. For the moment it is better to consider it as a known issue and not to introduce silly workarounds for what is ultimately a corner case.
