### ISSUE TITLE
Date support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#888]
**As a developer integrating Pillarbox** I want to be able to seek to a specific date, provided such information is returned in a stream.

# Acceptance criteria

- Seeking to a date is possible for streams delivering date information.
- Progress information can be obtained as a date for streams delivering date information.
- The demo displays dates for livestreams when available (similar to the system UI).

# Hints

- Dates can appear in-on demand streams and livestreams.

# Tasks

- [x] Provide current date and seek to date APIs (no need to provide tolerances or smooth seeking, just bridge with `AVPlayer` APIs).
- [x] Provide date information on `ProgressTracker`.
- [x] Display date position for livestreams that provide date information.
- [x] Make time / date APIs more consistent (usually `func` but we sometimes use `var`).
- [x] Ensure same consistency for metrics retrieval (also document metrics retrieval at any time in corresponding article).
- [x] ~Check that we can start playback at some date (make dedicated API available if needed).~

**Comment by defagos** [comment]
Some findings:

- Our on-demand sports streams contains date information.
- The system UX displays date information only for livestreams, even if available in an on-demand stream (different on tvOS where display can always be toggled between both).
- Date information is available from `AVPlayerItem`, not from `AVPlayer`. Since discontinuities might arise we probably need to use stream date and time information to store a mapping between player time and date, updated when appropriate. This mapping can then be used as reference for calculations since we need to use our seek to time APIs, as seek to date APIs are more limited (tolerances e.g.) and do not support smooth seeking.

**Comment by defagos** [comment]
To be able to start playback at a specific date we would need to update `PlayerItemConfiguration` to support a `StartLocation`, either `position(Position)` or `date(Date)`, but in the date case we cannot deal with blocked time ranges correctly unless we implement full equivalence between date and time, as we did in SRG Media Player.

This requires storing a fixed date vs. time reference, with no guarantee it remains valid in time, and introduces a lot of complexity (e.g. time ranges should be expressible with either dates or positions, like we did in SRG Media Player).

For this reason we decided not to support playback start at a specific date for the moment. This keeps things simple until this feature is really requested, at which point we might decide to implement a simple solution (ignoring blocked time ranges which are applied at a 1/10th interval anyway) or a more complex one (if it really makes sense). But since blocked time ranges are more of a workaround introducing too much complexity is probably not justified.
