### ISSUE TITLE
Repeat modes

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#899]
**As a user** I want some playback experiences to provide me with repeat modes:

- Repeat one: When enabled, repeats the current content in a playlist.
- Repeat all: When enabled, repeats the whole playlist at the end.

# Hints

- [ExoPlayer](https://developer.android.com/reference/androidx/media3/common/Player#REPEAT_MODE_ALL()) API documentation for inspiration.

# Acceptance criteria

- An API is available to set the repeat mode (can be none).
- A repeat mode toggle button (none, one, all) has been added to the playlist demo.
- Advancing to the next / returning to the previous item wraps around the playlist in _repeat all_ mode.
- Advancing to the next / returning to the previous item in _repeat one_ mode moves to the next / previous item, as usual.
- In all repeat modes the playback experience is gapless.

# Hints

Maybe `AVPlayerLooper` might be helpful (maybe not).

# Tasks

- [x] Check with `AVQueuePlayer` and `AVPlayerLooper` how repeat modes interact with `actionAtItemEnd` so that we can better understand how our implementation should behave.
- [x] Add repeat modes:
    - [x] Update behavior when syncing queue items with content updates.
    - [x] Update (can) advance to next APIs (properly handle single-item queues).
    - [x] Probably force an `AVPlayerQueue` item queue update when the repeat mode is changed.
- [x] Update the playlist demo with a dedicated button.
- [x] ~Make sure each individual loop is a separate comScore analytics session.~
- [x] Check tacker behavior.
- [x] Check network activity (e.g. preload of next stored item).

**Comment by defagos** [comment]
Two ideas to tackle this issue:

1. Use item end notification to apply the behavior. Probably requires internal queue player `actionAtItemEnd` to be tweaked (not the external value) to have playback paused before applying the behavior, otherwise the item might be consumed early.
2. Use `AVPlayerLooper` to manage _repeat one_ behavior, and inject the first `AVPlayerItem` in the `AVPlayerQueue` at the end of the playlist to have pre-buffering work.

**Comment by defagos** [comment]
SF Symbols provide several `repeat` icons that can be useful for UI integration.

**Comment by defagos** [comment]
`AVPlayerLooper` is interesting but limited. Some facts:

- It can only repeat one item at a time and can replay only a specific range.
- When using `AVPlayerViewController` or `VideoPlayer` the seek bar is restricted to the repeated range. The seekable time ranges, though, remain the same, so there is no secret way of truncating the playlist we don't know about.

**Comment by defagos** [comment]
I guess [no special work](#951) is required for comScore. Still we have to check the behavior of trackers in general, though it is likely no special work is actually required.

**Comment by defagos** [comment]
According to #951 we can reuse the same comScore session id after having ended but not left the current item. So for loops obtained by enabling "repeat one" behavior we can reuse the same session as well.

**Comment by defagos** [comment]
Previous / next APIs wrap around playlist ends when the repeat mode is set to `.all`, even if there is only a single item in the list. This is consistent with other apps like Spotify and Android ExoPlayer behavior as well. Applications can still decide to disable the button when a single item is loaded by testing the number of items in the queue.
