### ISSUE TITLE
Update to Tag Commander V5

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#90]
**As a member of the analytics team** I want results to be gathered with the [new Tag Commander platform](https://github.com/CommandersAct/iOSV5/tree/master/TCServerSide#migration-v4-to-v5) requiring version 5 of the SDKs to be running in mobile applications.

# Acceptance criteria

- The TagCommander SDK has been updated.
- Integration documentation has been updated if needed.
- The SDK is available on GitHub.
- Integrators have been notified about the change and the deadline.
 
Remark: Server-side tags need to be migrated as well for the whole integration to work. Handled by the GD.

### Hints

- Migration to V5 is [documented](https://github.com/CommandersAct/iOSV5/tree/master/TCServerSide#migration-v4-to-v5). In particular the events are now not anonymous data dictionaries but are specifically defined with their associated data.
- The list of available events is [documented](https://community.commandersact.com/platform-x/developers/tracking/events-reference).

# Tasks

- [ ] Update SDK.
- [ ] Ask for source key to use.
- [ ] Update instantiation.
- [ ] Update request interceptor.
- [ ] Update hidden event implementation.
- [ ] Update page view implementation.
- [ ] Update stream tracking implementation.
- [ ] Update integration documentation.
