### ISSUE TITLE
Playlist UI component

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#901]
**As a developer** integrating Pillarbox I need a simple UI component (without any view) to help me keep playlist model objects from my app with the player item playlist managed by a player.

# Acceptance criteria

- A UI component is provided to help manage playlist sync.
- The UI component is used in the current playlist demo.

# Tasks

- [x] Replace `currentIndex` API with `currentItem` API to be able to bind a `Player` to a `List` directly.
- [x] Update playlist demo implementation.
- [x] Get rid of `Template` demo stuff if possible.
- [x] Provide `List` convenience constructor with a player parameter?

**Comment by defagos** [comment]
There is likely no need for any playlist component. We can rather bind `Player` directly to a `List`. This requires:

1. `PlayerItem` must be `Hashable`.
2. `currentItem` should be bindable to a `List`.

The only remaining question is how we can make it easy for a list of model objects to be kept in sync with the list of `PlayerItem`s. Probably making `PlayerItem` conform to `Identifiable` is the easiest way.

**Comment by defagos** [comment]
No need to conform to `Identifiable`, and in fact it would make the API more error-prone to use when connected to a `List`. `List` namely supports identifiable types and expects that the selection state stores associated identifiers. In our case we want to work with items, both for the list of items as well as for the selection. In such cases it suffices to use `\.self` as `id` when creating the `List` to get the desired behavior, and this is enforced by making `PlayerItem` **not** `Identifiable`. Otherwise the code would compile but no selection would be made, as the type of `currentItem` and of the identifier, naturally `UUID` for `PlayerItem`, would not match.
