### ISSUE TITLE
Gather metrics for QoS

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#903]
**As a QoS backend developer** I need standard data to be delivered for reporting purposes. **As a Pillarbox developer** I need to gather such data on device first so that I can send them later to the backend.

# Acceptance criteria

- Session, error and event information is extracted.
- No need to have the data sent to the backend yet.

# Hints

- Format is discussed [elsewhere](https://github.com/SRGSSR/pillarbox-documentation/issues/70).
- Interestic best practices are shared on a [related issue](https://github.com/SRGSSR/pillarbox-apple/issues/897).

# Design considerations

- We must deliver metrics based on `AVPlayerAccessLogEvent`s.
- Metrics at any point in time must be built from **all values of past immutable access log events**, not from a single event. This way metrics provide consolidated information at the time of the measurement. This approach of returning total values is also how Android [provides](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/PlaybackStats) metrics.
- We introduce two publishers for metrics:
    - A publisher that delivers metrics based on immutable historical data.
    - A publisher that delivers metrics based on immutable historical data as well as real-time updates (last mutable log event).
- With these publishers we can gather metrics in a variety of ways, for QoS or representation purposes.
- Some events in the access log seem dummy (no real data, no date). Those will be ignored.

# Tasks

- [x] Build metrics from access log events.
- [x] Provide publishers for historical and real-time metrics.
- [x] Provide derived values that might be interesting (bandwidth according to most recent event, Apple WWDC talk KPIs).
- [x] Avoid redundant calculations (we can likely cache existing results into a `MatricsSpapshot` based on immutable information, storing the date of the last immutable event as a marker in a cached result and the associated metrics).
- [x] Maybe use a shared publisher for the historical values and store its snapshot internally in the player properties. This way we could implement a getter that delivers current metrics and the associated increment with respect to the last store immutable snapshot. This would also make access from a player item tracker easy and consistent.
- [x] Provide player / item time in snapshots.
- [x] Try to implement a custom `PlayerItemTracker` using this information somehow (do not commit).

**Comment by defagos** [comment]
Here is a sample from an access log obtained after a seek:

```
#Version: 1.0
#Software: AppleCoreMedia/1.0.0.21F79 (iPad; U; CPU OS 17_5 like Mac OS X; en_us)
#Date: 2024/06/10 08:43:53.053
#Fields: date time uri cs-guid s-ip s-ip-changes sc-count c-duration-downloaded c-start-time c-duration-watched bytes c-observed-bitrate sc-indicated-bitrate c-stalls c-frames-dropped c-startup-time c-overdue c-reason c-observed-min-bitrate c-observed-max-bitrate c-observed-bitrate-sd s-playback-type sc-wwan-count c-switch-bitrate
2024/06/10 08:43:00.000 https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 212.60.37.26 0 13 130.000 0.000 46.871 42598168 111623915.000 2494507 1 0 0.234 1 8 - - 76942770.438 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 0.000 0.000 0 108378005.000 2494507 0 0 - 0 - - - 77318239.694 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 0.000 0.000 0 108378005.000 2494507 0 0 - 0 1 - - 77318239.694 VOD 0 -
2024/06/10 08:43:48.048 https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 212.60.37.10 0 3 30.000 102.120 0.305 10549800 117777566.000 2494507 0 0 0.087 0 8 - - 73529376.973 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 102.120 0.000 0 113280291.000 2494507 0 0 - 0 - - - 70583225.922 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 102.120 0.000 0 113280291.000 2494507 0 0 - 0 1 - - 70583225.922 VOD 0 -
2024/06/10 08:43:49.049 https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 212.60.37.10 0 1 10.000 174.460 0.178 6291456 115454232.000 2494507 0 0 0.119 0 8 - - 68184704.266 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 174.460 0.000 0 112920487.000 2494507 0 0 - 0 - - - 66794819.554 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 174.460 0.000 0 112920487.000 2494507 0 0 - 0 1 - - 66794819.554 VOD 0 -
2024/06/10 08:43:49.049 https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 212.60.37.10 0 5 50.000 221.500 0.689 17814752 122858753.000 2494507 0 0 0.070 0 8 - - 64462993.645 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 221.500 0.000 0 117596093.000 2494507 0 0 - 0 - - - 60828301.026 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 221.500 0.000 0 117596093.000 2494507 0 0 - 0 1 - - 60828301.026 VOD 0 -
2024/06/10 08:43:51.051 https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 212.60.37.10 0 4 40.000 81.920 0.504 16141344 125863568.000 2494507 0 0 0.069 0 8 - - 62693318.424 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 81.920 0.000 0 123317185.000 2494507 0 0 - 0 - - - 59410794.797 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 81.920 0.000 0 123317185.000 2494507 0 0 - 0 1 - - 59410794.797 VOD 0 -
2024/06/10 08:43:52.052 https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 212.60.37.10 0 4 40.000 31.100 0.480 14113376 128656552.000 2494507 0 0 0.074 0 8 - - 59157117.548 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 31.100 0.000 0 125460621.000 2494507 0 0 - 0 - - - 56258782.500 VOD 0 -
- - https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 - - 0 0.000 31.100 0.000 0 125460621.000 2494507 0 0 - 0 1 - - 56258782.500 VOD 0 -
2024/06/10 08:43:53.053 https://swi-vod.akamaized.net/videoJson/47603186/index-f1-v1-a1.m3u8 433881E5-6464-46AE-9174-51953FBEC9B4 212.60.37.10 0 1 10.000 102.120 0.018 3185848 125712532.000 2494507 0 0 0.080 0 1 - - 55581308.664 VOD 0 -
```

We can observe it is possible to have several entries with the exact same date.

**Comment by defagos** [comment]
Some important remarks:

- An access log with N entries contain N-1 immutable entries, followed by a mutable one which gets updated with the current information.
- The entries are ordered by date.
- Not all entries contain a `playbackStartDate`. It is likely that entries that were opened but are discarded, e.g. during seeks, still are recorded with an empty start date for some reason. Those can likely be ignored. Not that the last entry in the log might not contain a `playbackStartDate` during a seek but will once the seek is over (mostly on HLS content, with MP4 all entries seem to contain a playback start date).
