### ISSUE TITLE
Swift 6 compatibility

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#908]
**As a developer** I would like to benefit from improvements made with Swift 6.

# Acceptance criteria

- Swift 6 support has been enabled (not to be delivered before Xcode 16 is officially available).

# Tasks

- [x] Update version in package manifest.
- [ ] Fix issues.
- [ ] Update Swift version in the demo.
- [ ] Fix issues.
- [x] Enable explicit modules in the demo target.
- [ ] Report issues found to Apple, if any.
- [ ] Think about publishers and guarantees (e.g. should publishers provided by Player always publish on the main thread? Offer no such guarantee?)

**Comment by defagos** [comment]
There is an issue with structs and strict concurrency checking:

```swift
public struct Flags {
    public static let none = Self(isEnabled: false)       // Static property 'none' is not concurrency-safe because non-'Sendable' type 'Flags' may have shared mutable state
    public let isEnabled: Bool
}

struct Flags2 {
    public static let none = Self(isEnabled: false)       // No issue
    public let isEnabled: Bool
}

struct Flags3 {
    static let none = Self(isEnabled: false)                  // No issue
    let isEnabled: Bool
}
```

I am not really understanding why this happens with a constant and since global instantiation is [guaranteed to be safe](https://developer.apple.com/videos/play/wwdc2024/10169/). But this might be worth a deeper look and possibly a bug report if appropriate.

**Comment by defagos** [comment]
I investigated further how we could implement Swift 6 concurrency checking in Pillarbox, especially in the PillarboxPlayer package.

Current thoughts:

- I am not sure we should blindly adopt `@MainActor` everywhere. `AVPlayer` is marked as `@MainActor` but almost all its public API is marked as nonisolated since iOS / tvOS 16, which means that most of the API can be used off the main thread. AVFoundation documentation was updated accordingly.
- Instead we should probably focus in making `Player` (and other types) `@Observable`. It namely seems that no additional work is required for SwiftUI updates to be performed on the main thread. This would also make `Player` more flexible and would avoid `@MainActor` spreading through the codebase like a disease.
- We can use `weakAssign(to:on:)` to plug publishers to properties of the observable object, without switching threads. If we want to have stronger guarantees about execution onto a single thread we could have `Player` manage its own dispatch queue and receive publisher output on them consistently.

I will write a small prototype to evaluate the feasibility of this approach and attach it here.

**Comment by defagos** [comment]
I opened an [issue](#931) for thread-safety. `Player` should likely not be annotated as `@MainActor` unnecessarily, we should rather document that in the meantime it is safe to be used on the main thread only.

**Comment by defagos** [comment]
A fix was required to our Core `Binding` extension because key paths are non-sendable. Read more about:

- [`isolated(any)`](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0431-isolated-any-functions.md), which has been added to binding getter / setter closures.
- [How to fix the issue](https://github.com/swiftlang/swift/issues/68943) by constraining our helper to sendable bindings, which in turn requires the wrapped type `T` to be itself sendable.
