### ISSUE TITLE
Provide metric event for fatal errors

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#924]
**As a player developer** I want to understand when fatal errors occur.

# Acceptance criteria

- Fatal errors are provided in player metrics.

# Tasks

- [x] Capture asset loading errors.
- [x] Capture resource loading errors.
- [x] Check metric log in all possible use cases:
    - [x] URL playback.
    - [x] Failing URL playback (+ retry).
    - [x] Failing URN playback (+ retry).
    - [x] Playlist automatic / manual item switch between playable items.
    - [x] Playlist automatic / manual item switch between a playable and a non-playable item (URL / URN).
    - [x] Error during playback (only tested manually).
    - [x] Retry after network failure during playback.
- [x] Check analytics (current tracker refactoring).
- [x] Check memory profile.

**Comment by defagos** [comment]
There were several challenges involved with the present issue:

- Associate metric events with the item being played, so that we can identify what happens exactly during playback of an item. We must avoid mixing events from different items at all costs.
- Provide a flexible API so that developers can follow a single event stream if desired, or a stream of events chunked per item.

Here is a possible strategy to solve these challenges:

- To allow both single as well as chunked stream behavior, we can implement a publisher of event publishers internally. This way we can either prodice a single event stream (map + switch to latest) or a stream of event arrays per current item (map + scan + switch to latest).
- The defining moment when a new publisher must be produced by this publisher of publishers is when the current item changes. This moment can be extracted from our shardd queue update stream.
- Events are produced by `PlayerItem` and `AVPlayerItem`. In our previous implementation we only instantiated an event log at the `PlayerItem`, passing it down to associated `AVPlayerItem`s through the `AssetContent`, so that all related items could publish events into the same log. This never was satisfying, though:
    - The `AVPlayerItem` event log had to be optional, even though an event log could always be there. Dealing with an optional when sending a log event was clunky.
    - We had to capture the log but there was no formal guarantee its value would be correct at the time of the capture. 
- A queue event is produced when the current item changes, but also when its associated `AVPlayerItem` changes (note that the `PlayerItem` and `AVPlayerItem` from a `Queue` are always consistent since both are related by id). This is why we cannot simply slice the stream on its `items`. Each change offers three possibilities:
    - There is no item, in which case an empty stream is produced.
    - There is a new item, in which case a new stream of events is produced.
    - When the `AVPlayerItem` changes (e.g. loading to loaded or failed) we must **never** produce a new stream but associate the

**Comment by defagos** [comment]
The strategy outlined above does not work. We namely cannot hook to an existing publisher before a subscription has been established, thus we miss events which have been emitted before the subscription.

Instead we can produce a stream for the current item or a stream of changes from a single stream consolidating updates. When an update happens we can namely determine which events have been collected and which are new.

This strategy requires cleaning up the event streams, but fortunately this is easy (since each event is unique we can add an internal unique id to make an event hashable / equatable, making cleanup and collection diffs easy).
