### ISSUE TITLE
Document QoS support

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#928]
**As a developer integrating Pillarbox** I want to better understand what QoS-related features are available if I need them. **As a quality engineer** I want to better understand the tools and metrics at my disposal. **As a stream packaging team member** I want to better understand the tools, local or remote, that I can use when checking the streams I deliver.

# Acceptance criteria

- QoS local tools are documented.
- QoS APIs are documented (e.g. `MetricsCollector`).
- QoS remote tools are documented.

# Tasks

- [x] Document `MetricsCollector` usage.
- [x] Document local tools (stats overlay in the demo, metrics view).
- [x] Document PillarboxMonitoring.
- [x] Update feature list.
- [x] Organize APIs in sections for all types.
- [x] Group metric APIs.
- [x] Add privacy report to Monitoring framework.
- [x] API naming (resource / asset).
