### ISSUE TITLE
Create basic QoS tracker

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#929]
**As a Pillarbox developer** I need to prepare payloads that I will later be able to send to our QoS backend.

# Hints

The data format is [documented elsewhere](https://github.com/SRGSSR/pillarbox-documentation/issues/70).

# Acceptance criteria

- A QoS tracker is available that logs performance metrics to the console when playing SRG SSR content.

# Tasks

- [x] Discuss if client-related errors (e.g. network errors) must be collected by our tracker or not.
- [x] Add Telemetry package (or similar name) that contains a generic QoS tracker compatible with our QoS backend.
- [x] Implement all required payloads and log them to the console.
- [x] Add a way to display a unique support identifier in case of errors and display it in the custom player UI.

# (19.07.2024) Issues with current implementation

Write UTs and fix:

- `media_position` must not be affected by the playback speed. We cannot therefore use info from the access log, this value must be computed manually.
- Automatically chaining items in a playlist incorrectly emits events after `eof`. Probably removing the `where` clause in `case (.none, _) where event != .play, (.eof, _) where event != .play:` suffices.
- `media_position` is missing in `stop` events when navigating the playlist manually because of incorrect use of upcoming item properties (with `.invalid` stream type).
