### ISSUE TITLE
Update Swift linter to version 0.50

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#93]
**As a developer** I want to make linting as strict as possible to minimize errors and improve coding style consistency.

# Acceptance criteria

- The Swift linter is updated with the most recent rules available for Swift 5.7.

# Tasks

- [x] Update swiftlint to 0.50 on all CI agents.
- [x] Update ruleset with [new rules](https://github.com/realm/SwiftLint/releases/tag/0.50.0-rc.1). Run `swiftlint rules` to find them.
- [x] Attempt to remove manually disabled rules in code (e.g. method ordering) which were introduced because of swiftlint issues which might have been fixed in 0.50.
- [x] To avoid going through all rules each and every time we revisit the linter configuration, all rules should likely appear in the file, either as explicitly enabled, or as explicitly disabled.

**Comment by defagos** [comment]
0.50 is only available in RC. I still began the update with a new rule for 0.49.1, but this will have to wait a little bit.

**Comment by defagos** [comment]
The rule `private_subject` leads to false positives for subjects defined in a local scope (not as property). This should be reported as swiftlint issue but can be disabled individually where needed.
