### ISSUE TITLE
Incorrect negative metrics when enabling / disabling AirPlay

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#936]
**As an engineer** I want correct reliable data that can be plotted with confidence. There is currently an issue affecting metrics when AirPlay is enabled or disabled, reproduced as follows:

- Play some content.
- Open the metrics debugging view.
- Connect to AirPlay and observer that data volume / media requests suddenly provide a negative contribution, likely equal to the current total.

# Acceptance criteria

- The issue described above has been fixed.

# Tasks

- [x] Fix issue by resetting metrics when external playback is toggled.
- [x] Document behavior of metrics when external playback is toggled.
- [x] Document that metrics provided by player properties have increment equal to total.
- [x] File radar.

**Comment by defagos** [comment]
This is what I consider a bug. The access log is namely cleaned up when enabling or disabling external playback, even though it shows some continuity (e.g. the User Agent visible in the extended log data always informs about the casting device, never the receiver).

Fortunately I think there is an easy way to solve this issue:

1. Introduce a `snapshot()` method on `MetricsState` to save the current `MetricsValues` as base value, replacing `.zero`.
2. Detect external playback status changes and perform a snapshot each time.

This should ensure we never lose past history, eliminating negative values.

If the radar I will open is fixed in a later iOS version we will just have to drop the snapshotting mechanism to get correct behavior. Of course, we need to stay vigilant if for some reason we see large bumps in values later when enabling or disabling external playback. This would be a sign that the issue was fixed.

**Comment by defagos** [comment]
The snapshot strategy does not work. To be reliable we would need to be able to snapshot values right before AirPlay is enabled, but at the time we get the status change it is sometimes not too late, but sometimes it is, in which case we snapshot nothing and get negative values afterwards.

Notifications like `AVAudioSession.routeChangeNotification` and KVO on `isExternalPlaybackActive` suffer from the same issue,

An alternative to consider: Reset to `.empty` reference state when toggling external playback. Totals will diminish but negative values will disappear.

**Comment by defagos** [comment]
I filed  a suggestion _`AVPlayerItemAccessLog` should not be cleared when toggling external playback_ under FB14820936.

**Comment by defagos** [comment]
I got feedback regarding the suggestion above. Since some statistics are hardware specific (`c-rssi`, `c-startup-time`, `c-stalls` for example) the team in charge decided it was less confusing for developers to keep sender / receiver access log sessions separate.

This totally makes sense. I therefore closed the issue and we will have to keep our current implementation as is.
