### ISSUE TITLE
Metrics and local content playback

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#940]
**As a developer** I need to check that metrics collected are correct for content played locally.

# Acceptance criteria

- Correct metrics (might be empty) are delivered for a local content.

# Tasks

- [x] Add local (small) video to the demo.
- [x] Check metrics and fix identified issues, if any.

**Comment by Chuysalgafo** [comment]
> **As a developer** I need to check that metrics collected are correct for content played locally.
> 
> # Acceptance criteria
> 
> - Correct metrics (might be empty) are delivered for a local content.
> 
> # Tasks
> 
- [ ] > - [ ] Add local (small) video to the demo.
- [ ] > - [ ] Check metrics and fix identified issues, if any.

**Comment by Chuysalgafo** [comment]
> > **As a developer** I need to check that metrics collected are correct for content played locally.
> > 
> > # Acceptance criteria
> > 
> > - Correct metrics (might be empty) are delivered for a local content.
> > 
> > # Tasks
> > 
- [ ] > - [ ] > - [ ] Add local (small) video to the demo.
- [ ] > - [ ] > - [ ] Check metrics and fix identified issues, if any.
> 
>

**Comment by Chuysalgafo** [comment]
> **As a developer** I need to check that metrics collected are correct for content played locally.
> 
> # Acceptance criteria
> 
> - Correct metrics (might be empty) are delivered for a local content.
> 
> # Tasks
> 
- [ ] > - [ ] Add local (small) video to the demo.
- [ ] > - [ ] Check metrics and fix identified issues, if any.

**Comment by Chuysalgafo** [comment]
> **As a developer** I need to check that metrics collected are correct for content played locally.
> 
> # Acceptance criteria
> 
> - Correct metrics (might be empty) are delivered for a local content.
> 
> # Tasks
> 
- [ ] > - [ ] Add local (small) video to the demo.
- [ ] > - [ ] Check metrics and fix identified issues, if any.

**Comment by defagos** [comment]
We added a local video to the demo. Metrics are correct, though we only have asset and resource loading metric events in this case.

@waliid also started investigating how we could add access to the photo library. This approach is better than adding an embedded video to the demo.
