### ISSUE TITLE
Revisit player item tracking

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#944]
**As a developer integrating Pillarbox** I want to be able to more reliably implement custom trackers, avoiding retain cycles or incorrect data extraction. **As a Pillarbox developer** I want to avoid time extrapolations to be redundantly implemented in custom trackers, most notably with #929 in sight.

# Acceptance criteria

- Custom player item tracking has been made simpler.
- Existing comScore and Commanders Act trackers have been updated accordingly.

# Tasks

- [x] Update tracking implementation.
- [x] Provide a way to expose track selection from `PlayerProperties`.
- [x] Update existing trackers.
    - [x] comScore.
    - [x] Commanders Act.
        - [x] Merge implementation.
        - [x] Heartbeats.
        - [x] Playback duration (must not be read from access log since, use clock time).
- [x] Polish `Player.swift` publisher grouping.
- [x] Think about the use case of position tracking (e.g. playback history).
- [x] Update documentation.

**Comment by defagos** [comment]
It is important to provide a bit of context since this task was quite challenging, from an API design perspective as well as in its implementation.

# API design considerations

A tracker can be enabled or disabled at any time, with dedicated life cycle methods in `PlayeritemTracker`. Currently metadata and properties are provided with dedicated life cycle methods and represent the most recent values, which is perfectly fine.

Initially we intended to add a method called when a single metric event is received, but this does not work well with the fact that the tracker can be enabled or disabled at any time. Events which would not have been captured would be missed, but a tracker could need them. For this reason it is required that the entire metric event history is provided with each call to the update method. If only the most recent event is needed it suffices to extract the last event.

# Timing extraction

Timing extraction is tricky as well. Initially we intended to extract timings with surgical insertion of measurement operators in existing pipelines, but this strategy fails. large pipelines are mostly shared and reused but smaller ones can be reused, in which case measurements would be recorded several times.

Moreover we have to precisely control _when_ a measurement is started, which is not possible with such pipelines.

For this reason it is better to have separate measurement-oriented pipelines that are instantiated once and deliver associated metric events (as well as metric events we are interested in). Measurement start at subscription time, which we can precisely control by having a dedicated object, instantiated when an item becomes the current one. This way all our times measure the perceived user experience as soon the player takes an item into account.

# Asset and resource loading measurements

To a single `PlayerItem` correspond several `AVPlayerItem`s. For this reason we must not instantiate a new `PlayerItem`-related metric pipeline when only an associated `AVPlayerItem` changes, otherwise we would reset timing measurements. 

To achieve this goal we can assemble the metric event publisher of a `PlayerItem` with a subject. The subject can be rewired on-the-fly to another `AVPlayerItem` metric event publisher when needed.

# Playback duration measurements for Commanders Act analytics

We cannot use access log information as it does not take into account playback speed. For this reason we had to introduce a small stopwatch tool for wall clock time measurements.
