### ISSUE TITLE
Improve metrics info view

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#959]
**As a developer** I want to be able to inspect a running playback session with our metrics viewer. This requires the session identifier to be visible on device.

# Acceptance criteria

- The metrics info view displays the session id, if any metrics tracker is associated with the item being played.
- The session id can be simply copied.

# Tasks

- [x] Revisit session id extraction.
- [x] Provide API on `Player` instead of `PlayerItem`.
- [x] Display session id in info view.
- [x] Add copy / paste support.
- [x] Add tests.
