### ISSUE TITLE
Send data to Pillarbox QoS backend

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#961]
**As a Pillarbox QoS backend developer** I need to receive QoS data from Pillarbox player so that I can create dashboards based on real data.

# Hints

Android and web players will send monitoring data for URLs and URNs. We won't do the same on Apple platforms since this would force monitoring at the PillarboxPlayer level (apps can still decide to attach a tracker if needed).

# Acceptance criteria

- Metrics data associated with SRG SSR content is visible on Pillarbox metrics dashboards.

# Tasks

- [ ] Associate instances with SRG SSR content, sending data to the official endpoint.
- [x] Ensure QoS trackers can never be disabled by enabling the corresponding flag (#926).
- [x] Remove explicit link with `PillarboxMonitoring` from demo target.
- [x] Remove `PlayerItemTests` Core Business unit tests to avoid sending monitoring data in UTs?
- [x] ~#1040~ Will be done later.
