### ISSUE TITLE
Update metrics tracker to most recent specifications

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#966]
**As a QoS / QoE engineering** I want to be able to configure charts based on our [official specifications](https://github.com/SRGSSR/pillarbox-documentation/blob/91-add-discussed-monitoring-specifications/Specifications/monitoring.md).

# Acceptance criteria

- The implementation has been updated to 1.0.0 specifications.

# Tasks

- [x] Add version information
- [x] Use lower-case for UUIDs.
- [x] Send timestamps in milliseconds.
- [x] Introduce configuration object (less awkward).
- [x] Update buffered duration field name.
- [x] Provide correct player position information for DVR and live streams.
- [x] Implement heartbeat.
- [x] Add tests to the monitoring package (or decide what to do with current dummy suite).
- [x] Add test infrastructure for event capture and test behavior:
    - [x] No stop if not enabled.
    - [x] Start before an error.
    - [x] Heartbeats.
