### ISSUE TITLE
Browse through AVFoundation / AVKit APIs

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#97]
**As a developer** I need to know which tools are available natively from the player I use. Those have been extended in recent years and some might be extremely handy in implementing features we desire.

# Acceptance criteria

- `AVFoundation` APIs have been covered.
- `AVKit` APIs have been covered.

# Tasks

- [x] Read `AVFoundation` framework headers.
- [x] Read `AVKit` framework headers.
- [x] Read `AVFoundation` [documentation](https://developer.apple.com/documentation/avfoundation).
- [x] Read `AVKit` [documentation](https://developer.apple.com/documentation/avkit).
- [x] Link useful documentation in our [wiki](https://github.com/SRGSSR/pillarbox-apple/wiki/Links).
- [x] Produce a list of which APIs could be investigated / used for some features. Also see [comments](https://github.com/SRGSSR/srgletterbox-apple/issues/252) written in the Letterbox PoC issue.

**Comment by defagos** [comment]
# `AVPlayer` APIs

Some old and new APIs which might be useful someday:

- `setRate(_ rate:time:atHostTime:)`: Could this be helpful for setting a relationship between stream time and clock time in DVR streams?
- `preroll(atRate:)` for faster startup in some cases?
- `automaticallyWaitsToMinimizeStalling`, though how this flag is set should also take into account whether a resource loader is attached to the asset and what it does (see associated documentation).
- `timeControlStatus` and `reasonForWaitingToPlay`.

# `AVPlayerItem` APIs

- `configuredTimeOffsetFromLive`, `recommendedTimeOffsetFromLive` and `automaticallyPreservesTimeOffsetFromLive` to fine-tune behavior when playing livestreams.
- `forwardPlaybackEndTime` and `reversePlaybackEndTime`: Could these be useful to implement behavior at content edges with `|rate| > 1`, e.g. when approaching the live edge at high playback rates?
- `timebase`: Could it be useful to learn about the relationship between stream time and clock time?
- `step(byCount:)`: For skip forward / backward?
- `canUseNetworkResourcesForLiveStreamingWhilePaused`: Could it be used to reduce network usage when playing DVR streams without negatively impacting the user experience?

**Comment by defagos** [comment]
Guess that's enough for now. We readily use a number of new APIs (control center, async loading, live offset preservation, etc.) and can keep the above list as reference.
