### ISSUE TITLE
Update to last version of QoS specs

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#973]
**As a QoS / QoE engineering** I want to be able to configure charts based on our [official specifications](https://github.com/SRGSSR/pillarbox-documentation/blob/91-add-discussed-monitoring-specifications/Specifications/monitoring.md).

# Hints

Our most recent [discussions](https://github.com/SRGSSR/pillarbox-documentation/issues/90).

# Acceptance criteria

- The implementation has been updated to match most recent specifications.

# Tasks

- [x] Update version number.
- [x] Always provide stall information.
- [x] Add media type.
- [x] Provide timestamp as player position for livestreams.
- [x] Check if we are able to extract VPN information without nasty trick or external dependency.
- [x] Send AirPlay status.
- [x] Revisit position information.
- [x] Add VPN flag.
