### ISSUE TITLE
Update to latest version of QoS specs

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#975]
**As a QoS / QoE engineering** I want to be able to configure charts based on our [official specifications](https://github.com/SRGSSR/pillarbox-documentation/blob/91-add-discussed-monitoring-specifications/Specifications/monitoring.md).

# Hints

Our most recent [discussions](https://github.com/SRGSSR/pillarbox-documentation/issues/90).

# Acceptance criteria

- The implementation has been updated to match most recent specifications.

# Tasks

- [x] Update stream type constants.
- [x] Open new session after fatal error.
- [x] Improve implementation by building data with dedicated methods and common payload with a single one.
- [x] Make sure that the session id returned in case of error is associated with the failed session.
