### ISSUE TITLE
Improve resource loading

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#98]
**As a developer** I think there is still room for improvement in how resource loading is performed.

# Acceptance criteria

- The resource loader delegate implementation has been improved to fix potential issues.

# Tasks

- [x] Fix `-[AVAssetResourceLoadingRequest finishLoading] was sent to an instance of AVAssetResourceLoadingRequest that was already finished. Ignoring.`
- [x] Check whether automatically loaded keys have an impact on startup performance on a 16.1 device with delayed media composition retrieval.
- [x] Check network and memory profile.

**Comment by defagos** [comment]
The impact of loading asset keys before the item is ready to play is different between device and simulator (16.1 beta), as can be seen with Charles:

- Add a significant delay to the media composition pipeline (5 seconds e.g.).
- Use default behavior when loading an item from an asset (remove `automaticallyLoadedAssetKeys` parameter).
- Inspect network traffic with Charles while playing the playlist URN demo.

With the simulator the whole playlist needs to be loaded before playback can start, while on device playback starts much earlier.

It is therefore likely that the work in #

**Comment by defagos** [comment]
I guess the warning appears because the `resourceLoader(:shouldWaitForLoadingOfRequestedResource:)` is called twice for the same URN and returns `true` while the first request, which might take a while (especially if we are delaying the request for test purposes), is still running.

This issue is thus likely related to the fact we now share resource loaders. Two options to fix the issue IMHO:

- Stop sharing resource loader delegates. Introduce an `AVPlayerItem` subclass which stores one resource delegate per item.
- Keep shared resource loaders, add a `uuid` parameter to the custom URL used to load the resource, extract it and use it to store the cancellable in the request map.

**Comment by defagos** [comment]
To reproduce the warning above, just add a large delay to the resource loader and swipe back and forth fast between stories in the corresponding demo.

**Comment by defagos** [comment]
Default automatically loaded keys work well on a 16.1 device with delayed resource loading. Playback namely start after only part of the playlist has been retrieved.
