### ISSUE TITLE
iOS / iPadOS / tvOS 18 compatibility

### ISSUE THREAD

**Issue by defagos** [SRGSSR/pillarbox-apple#989]
**As a developer** I need Pillarbox to be compatible with new major versions of Apple operating systems.

## Hints

Here is a list of the issues we noticed and of work that needs to be done.

## Fixes on our side

- ✅ Version plugin: Deprecation errors if package version set to 6.0.

## Upgrade work

- Update pbxproj to use folders instead of groups (https://iosdev.space/@kern/113012885194302061). Can only be done after Xcode 16 release.
- Update CI to build with Xcode 16 (ready on a #988).

## Xcode 16 / iOS 18 / iPadOS 18 bugs or regressions

- ✅ DocC warnings (some symbols not found, working correctly with Xcode 15).
- High-speed gesture not working: _System gesture gate timed out is logged to the console_.
- 🤔 Settings picker is incorrectly displayed as `toolbarTitleMenu` at the root level of the _Lists_ section (_iPadOS 18: New tab bar presentation and inline navigation title / toolbar title menus do not work well together_ filed under FB14924375).
- ✅ Startup time incorrect after seeking (✅ local / ✅ AirPlay)
- Playback fails very fast if buffer gets empty (e.g. start playback and enable airplane mode immediately)
- Podcastator: Speed / Timer menus do not open anymore when player displayed as a sheet.

# Acceptance criteria

- Pillarbox is compatible with iOS / iPadOS / tvOS 18.
- Issues which cannot be fixed on our side have been reported.
- The project builds with Xcode 16.

# Tasks

- [x] ~Update Xcode project to synced folders.~
- [ ] Fix high-speed gesture.
- [ ] Fix settings combo.
- [ ] Fix speed / timer menus in Podcastator.
- [ ] Document unresolved issues under known issues if appropriate.
- [x] Fix compilation warnings.

**Comment by defagos** [comment]
Though we won't update the Swift Package version to 6.0 yet here is here is the required change:

```swift
import Foundation
import PackagePlugin

@main
struct PackageInfoPlugin: BuildToolPlugin {
    func createBuildCommands(context: PackagePlugin.PluginContext, target: PackagePlugin.Target) async throws -> [PackagePlugin.Command] {
        [
            .prebuildCommand(
                displayName: "Provide package information as a generated Swift file",
                executable: try context.tool(named: "PackageInfo").url,
                arguments: [
                    context.package.directoryURL.path(),
                    context.pluginWorkDirectoryURL.path()
                ],
                outputFilesDirectory: context.pluginWorkDirectoryURL
            )
        ]
    }
}
```

See #908.

**Comment by defagos** [comment]
The Xcode project cannot be updated to synced folders since they are not supported by xcodeproj / fastlane yet, see #988.

**Comment by defagos** [comment]
All issues are not our own and have been reported. To avoid unnecessary work we will wait until iOS / tvOS 18 updates are released to see what is fixed and what isn't (since those are really minor annoyances).

**Comment by defagos** [comment]
Compilation warnings were fixed in #1105.

**Comment by defagos** [comment]
The menu issue in Podcastator can still be reproduced in 18.2.1.

**Comment by defagos** [comment]
We will close the issue since there is really nothing more we can do on our side. Let us hope that future versions of iOS fix those issues.

**Comment by defagos** [comment]
The long press gesture issue has been resolved in iOS 18.4 beta 1.
